"use strict";

// Flat ESLint config (ESLint 9/10).
// Adapted from Deadlock-UI-Mods/Minigames for QOLLOCK Panorama runtime.
//
// PURPOSE: Static bug net against undefined variables (no-undef), dead code,
// syntax hazards, and Panorama ASI continuation-line pitfalls.
// Deliberately NARROW: correctness only, no cosmetic style enforcement.

// Panorama's JS runtime globals (Deadlock Source 2 engine)
const PANORAMA_GLOBALS = {
    $: "readonly",
    panorama: "readonly",
    Game: "readonly",
    GameUI: "readonly",
    GameEvents: "readonly",
    // Engine concommands & C++ functions exposed to Panorama in Deadlock
    CitadelExitUpgradeShop: "readonly",
    CitadelEnterUpgradeShop: "readonly",
    CitadelToggleUpgradeShop: "readonly",
    CitadelOpenUpgradeShop: "readonly",
    CitadelShopModsActivate: "readonly",
    EItemSlotType_Favorites: "readonly",
    CitadelOpenBuildBrowser: "readonly",
    CitadelHudHeroBuildsToggleFavoriteSelector: "readonly",
    CitadelBuildBrowserRefresh: "readonly",
    CitadelHudHeroBuildsCreateNewBuild: "readonly",
    CitadelHudHeroBuildsDeleteSelectedBuild: "readonly",
    CitadelHudHeroBuildsEditSelectedBuild: "readonly",
    CitadelHudHeroBuildsSaveEdits: "readonly",
    CitadelHudHeroBuildsDiscardEdits: "readonly",
    DismissAllContextMenus: "readonly",
    DropInputFocus: "readonly",
    Entities: "readonly",
    CitadelUIHideTextTooltip: "readonly",
};

// Bare globals published by QOLLOCK infrastructure scripts (ql_utils, ql_shared_presets,
// ql_bridge, ql_state, ql_panelcache, ql_config, etc.) across the Panorama context.
const QOLLOCK_GLOBALS = {
    QOL: "writable",
    QOL_UTILS: "writable",
    QOL_WARN: "writable",
    QOL_INFO: "writable",
    QOL_ERROR: "writable",
    QOL_DEBUG: "writable",
    Utils: "readonly",
    State: "writable",
    QOL_STATE: "writable",
    QOL_STORAGE_KEY: "readonly",
    QOL_USER_EDIT_REV_ATTR: "readonly",
    QOL_PANEL_ID_HUD: "readonly",
    QOL_REGISTER_FEATURE: "readonly",
    QOL_FEATURE_REGISTRY: "writable",
    QOL_COMPACT_DEFAULT_HERO_OPTIONS: "readonly",
    STORAGE_KEY: "readonly",
    USER_EDIT_REV_ATTR: "readonly",
    BUILD_SAVE_REQUEST_ATTR: "readonly",
    BUILD_SAVE_STATE_ATTR: "readonly",
    BUILD_SAVE_MSG_ATTR: "readonly",
    BUILD_SAVE_TOKEN_ATTR: "readonly",
    BUILD_SAVE_FORCE_ATTR: "readonly",
    BUILD_CLEAR_REQUEST_ATTR: "readonly",
    BUILD_CLEAR_STATE_ATTR: "readonly",
    BUILD_CLEAR_MSG_ATTR: "readonly",
    BUILD_CLEAR_TOKEN_ATTR: "readonly",
    HERO_HINT_ATTR: "readonly",
    PLAYER_HEALTHBAR_ACCENT_COLOR_STORAGE_KEY: "readonly",
    PLAYER_HEALTHBAR_ACCENT_COLOR_ATTR: "readonly",
    BOTTOM_BAR_WASH_COLOR_ATTR: "readonly",
    KEYBOARD_OVERLAY_WASH_COLOR_ATTR: "readonly",
    STAMINA_CHARGE_COLOR_ATTR: "readonly",
    AMMO_TEXT_COLOR_ATTR: "readonly",
    MINIMAP_ICON_COLOR_ATTR: "readonly",
    QOL_BRIDGE_CHANNELS: "readonly",
    QOL_BRIDGE_ATTR_TO_CHANNEL: "readonly",
    QOLBridgeRead: "readonly",
    QOLBridgeWrite: "readonly",
    QOLBridgeReadAttr: "readonly",
    QOLBridgeWriteAttr: "readonly",
    GetCachedPanel: "readonly",
    SetCachedPanel: "readonly",
    ClearPanelCache: "readonly",
    ResolveCachedPanel: "readonly",
    PanelCache: "readonly",
    QOL_GetCachedPanel: "readonly",
    QOL_SetCachedPanel: "readonly",
    QOL_ClearPanelCache: "readonly",
    QOL_ResolveCachedPanel: "readonly",
    QOL_SCHEMA: "readonly",
    QOL_DEFAULT_CONFIG: "readonly",
    QOL_CONFIG_PROFILES: "readonly",
    QOL_PERF_OVERLAY_ENABLED: "readonly",
    QOL_PERF_OVERLAY_INITIAL_VISIBLE: "readonly",
    QOL_LOCALE: "readonly",
    QOL_MINIMAP_CRATE_SPAWNS: "readonly",
    QOL_RECENT_PURCHASES_ITEMS: "readonly",
    QOL_HEALTHBAR_SHARED: "readonly",
    QOL_PerfStart: "readonly",
    QOL_PerfEnd: "readonly",
    QOL_ExecuteFeature: "readonly",
    WrapConfigForStorage: "readonly",
    CRATE_DATA: "readonly",
    MINIMAP_CRATE_DATA: "readonly",
    MOD_ICONS: "readonly",
    HERO_IMAGES: "readonly",
    __qolLogBuf: "writable",
    MOD_CONFIG: "writable",
    MOD_DISPLAY_VERSION: "readonly",
    GetCompactWireVersion: "readonly",
    QOL_COMPACT_SCHEMA_UTILS: "readonly",
    LocalizeSettingsText: "readonly",
    QOL_COMPACT_SCHEMA_REGISTRY: "readonly",
    QOL_CODEC: "readonly",
    QOL_PRESETS: "readonly",
    QOL_ACCOUNT_PRESET_BINDINGS: "readonly",
    QOL_COMPACT_SCHEMA_WIRE_TO_SEMVER: "readonly",
    QOL_LATEST_COMPACT_SEMVER: "readonly",
    QOL_COMPACT_DEFAULT_HERO_FIELD: "readonly",
    QOL_SCHEMA_SEMVER: "readonly",
    QOL_PERF_OVERLAY: "readonly",
    BuildDefaultConfig: "readonly",
    GetSharedSchemaUtils: "readonly",
    MergeConfig: "readonly",
    NormalizeAmmoScaleConfig: "readonly",
    MigrateSplitZoomKeys: "readonly",
    NormalizeNeutralCampTierConfig: "readonly",
    NormalizeNeutralCampFlags: "readonly",
    NormalizeVoiceTypeValue: "readonly",
    NormalizeVoiceVolumeValue: "readonly",
    NormalizeBridgeBuffFilterConfig: "readonly",
    NormalizeVoiceTypeConfig: "readonly",
    NormalizeHealthbarTypeValue: "readonly",
    NormalizeHealthbarTypeConfig: "readonly",
    NormalizeColorWarningConfig: "readonly",
    NormalizeEnemyColorWarningConfig: "readonly",
    NormalizeAllyColorWarningConfig: "readonly",
    NormalizeTopbarEnemyHpWarningConfig: "readonly",
    NormalizeTopbarAllyHpWarningConfig: "readonly",
    NormalizeShopItemNotificationsConfig: "readonly",
    NormalizeQuickbuyDependencyConfig: "readonly",
    NormalizeItemCooldownModeConfig: "readonly",
    CompareSchemaSemver: "readonly",
    NormalizeCompassSpeedSchemaMigration: "readonly",
    NormalizeLanguageSchemaMigration: "readonly",
    SafeParseConfig: "readonly",
    UnwrapConfigFromStorage: "readonly",
    QOL_DumpDiagnostics: "readonly",
    QOL_SCHEMA_UTILS: "readonly",
    LATEST_COMPACT_SEMVER: "readonly",
    BUILD_CATEGORY_LATEST_COMPACT_SEMVER: "readonly",
    window: "readonly",
    document: "readonly",
};

// Globals shared across files in the Settings Menu context (hud_escape_menu.xml).
const SETTINGS_GLOBALS = {
    DEFAULT_CONFIG: "readonly",
    DEFAULT_HERO_OPTIONS: "readonly",
    DEFAULT_HERO_DROPDOWN_OPTIONS: "readonly",
    COMPACT_DEFAULT_HERO_FIELD: "readonly",
    NormalizeComparableConfigValue: "readonly",
    SetRuntimePresetName: "readonly",
    FindRootPanel: "readonly",
    IsSettingsWindowVisible: "readonly",
    GetPanelRectRelativeToContext: "readonly",
    SetPanelOpacitySafe: "readonly",
    SetPanelNonInteractive: "readonly",
    SaveAndSync: "readonly",
    HERO_HINT_PUBLISH_INTERVAL_SEC: "readonly",
    PERF_IMPACT_TIER_NONE: "readonly",
    PERF_IMPACT_TIER_LOW: "readonly",
    PERF_IMPACT_TIER_MEDIUM: "readonly",
    PERF_IMPACT_TIER_HIGH: "readonly",
    PERF_IMPACT_TIER_ORDER: "readonly",
    SETTING_PERF_IMPACT_TIERS: "readonly",
    PERF_IMPACT_LABEL_BY_TIER: "readonly",
    SETTING_CREATED_BY_BY_CONFIG: "readonly",
    SETTING_CREATED_BY_BY_LABEL: "readonly",
    SECTION_CREATED_BY_BY_TITLE: "readonly",
    currentTab: "writable",
    gCurrentSettingsSectionTitle: "writable",
    SECTION_DESCRIPTION_OVERRIDE_BY_TAB_TITLE: "readonly",
    SETTING_DESCRIPTION_OVERRIDE_BY_CATEGORY_ROW: "readonly",
    SETTING_DESCRIPTION_OVERRIDE_BY_CONFIG: "readonly",
    BuildCustomAnnouncerVoiceDescription: "readonly",
    GetPanelXOffsetWithinAncestor: "readonly",
    GetPanelYOffsetWithinAncestor: "readonly",
    PrepareSettingsModalOpen: "readonly",
    RUNTIME_PRESET_ATTR: "readonly",
    RefreshActivePresetConfigMarkerBeforeSave: "readonly",
    QueueActivePresetHighlightRefresh: "readonly",
    RefreshEnumSections: "readonly",
    UpdateListContent: "readonly",
    RenderSearchResults: "readonly",
    UpdatePresetHighlightPollingState: "readonly",
    InvalidateSearchSectionIndexCache: "readonly",
    IsConfigKeyChangedFromDefault: "readonly",
    GetSettingsTabDisplayName: "readonly",
    GetSettingsTabOrder: "readonly",
    GetSettingsTabGroups: "readonly",
    GetSettingsTabIconSource: "readonly",
    CreateSectionTitle: "readonly",
    CreateRow: "readonly",
    CreateSliderRow: "readonly",
    CreateInlineSecondaryCheckboxToggleRow: "readonly",
    CreateSeparator: "readonly",
    CreateSectionInlineIconButton: "readonly",
    CreateSectionTitleCheckboxToggle: "readonly",
    CreateAnimatedInlineToggleSection: "readonly",
    CreateCollapsibleSubSection: "readonly",
    CreateAnimatedInlineEnumSection: "readonly",
    CreateSectionResetButton: "readonly",
    CreateRuntimeSectionTitle: "readonly",
    ApplyDefaultHeroSelection: "readonly",
    ApplyHealthbarTypeSelection: "readonly",
    SLIDER_SHAPES: "readonly",
    GetRowResetKeys: "readonly",
    ApplyResetForConfigKeys: "readonly",
    CollectResetKeysFromPanel: "readonly",
    CollectResetKeysFromSectionTitleRow: "readonly",
    HasAnyChangedConfigKeys: "readonly",
    GetRuntimeButtonGroupDefaultIndex: "readonly",
    ApplyRuntimeButtonGroupIndex: "readonly",
    ResetRuntimeButtonGroupToDefault: "readonly",
    ResetRuntimeRowsInSectionFromTitleRow: "readonly",
    ForceCenterSliderValueInput: "readonly",
    CollectRowConfigKeys: "readonly",
    BindRowChangedState: "readonly",
    BuildSearchSectionIndexCacheKey: "readonly",
    GetCachedSearchSectionIndex: "readonly",
    NormalizeBreadPresetName: "readonly",
    PRESETS: "readonly",
    CitadelLeaveMatchmaking: "readonly",
    CitadelEditMatchmakingRoster: "readonly",
    CitadelReconnect: "readonly",
    CitadelConfirmAbandonGame: "readonly",
    CitadelDisconnectFromGame: "readonly",
    CitadelConCommand: "readonly",
    CitadelUIShowTextTooltip: "readonly",
    CitadelUIHideTextTooltip: "readonly",
    CitadelShowPlayPage: "readonly",
    CitadelShowWatchPage: "readonly",
    CitadelShowTrainingPage: "readonly",
    CitadelEscapeMenuChangeHero: "readonly",
    CitadelShowPlayerFeedbackPopup: "readonly",
    CitadelSettings: "readonly",
    CitadelMuteButtonClicked: "readonly",
    CitadelQuitConfirm: "readonly",
    CitadelResumePlaying: "readonly",
    UIShowTextTooltip: "readonly",
    UIHideTextTooltip: "readonly",
    SETTINGS_LANGUAGE_ENGLISH: "readonly",
    SETTINGS_LANGUAGE_RUSSIAN: "readonly",
    SETTINGS_LANGUAGE_UKRAINIAN: "readonly",
    SETTINGS_LANGUAGE_POLISH: "readonly",
    SETTINGS_LANGUAGE_BULGARIAN: "readonly",
    SETTINGS_LANGUAGE_JAPANESE: "readonly",
    SETTINGS_LANGUAGE_CHINESE: "readonly",
    SETTINGS_LANGUAGE_FRENCH: "readonly",
    SETTINGS_LANGUAGE_PORTUGUESE: "readonly",
    SETTINGS_LANGUAGE_BRAZILIAN_PORTUGUESE: "readonly",
    SETTINGS_LANGUAGE_SPANISH: "readonly",
    SETTINGS_LANGUAGE_BELARUSIAN: "readonly",
    SETTINGS_LANGUAGE_KOREAN: "readonly",
    SETTINGS_LANGUAGE_ITALIAN: "readonly",
    SETTINGS_LANGUAGE_TURKISH: "readonly",
    SETTINGS_LANGUAGE_OPTIONS: "readonly",
    SETTINGS_THEME_DEFAULT: "readonly",
    SETTINGS_THEME_CREAM: "readonly",
    SETTINGS_THEME_KITTEN: "readonly",
    SETTINGS_THEME_EMO: "readonly",
    SETTINGS_THEME_OCEAN: "readonly",
    SETTINGS_THEME_PSYCHO: "readonly",
    SETTINGS_THEME_MUNFINS: "readonly",
    SETTINGS_THEME_CLASS_NAMES: "readonly",
    SETTINGS_THEME_ROOT_CLASS_NAMES: "readonly",
    SETTINGS_THEME_OPTIONS: "readonly",
    SETTINGS_HEADER_MOG_LOGO_DEFAULT_SRC: "readonly",
    SETTINGS_HEADER_MOG_LOGO_THEME_SRC: "readonly",
    SETTINGS_HEADER_MUNFINS_LOGO_SRC: "readonly",
    GetSettingsLanguage: "readonly",
    IsRussianSettingsLanguage: "readonly",
    IsUkrainianSettingsLanguage: "readonly",
    IsPolishSettingsLanguage: "readonly",
    IsBulgarianSettingsLanguage: "readonly",
    IsBelarusianSettingsLanguage: "readonly",
    IsJapaneseSettingsLanguage: "readonly",
    IsChineseSettingsLanguage: "readonly",
    IsFrenchSettingsLanguage: "readonly",
    IsPortugueseSettingsLanguage: "readonly",
    IsBrazilianPortugueseSettingsLanguage: "readonly",
    IsSpanishSettingsLanguage: "readonly",
    GetSettingsLanguageKey: "readonly",
    GetSettingsTheme: "readonly",
    GetSettingsThemeKey: "readonly",
    ApplySettingsHeaderLogoTheme: "readonly",
    ApplySettingsThemeClasses: "readonly",
    NormalizeLatinSettingsText: "readonly",
    ShouldLocalizeTabContent: "readonly",
    SetLocalizedConfigFeedbackMessage: "readonly",
    MarkConfigDirty: "readonly",
    SetConfigFeedbackMessage: "readonly",
    RequestSettingsListRefresh: "readonly",
    RequestSettingsListSoftRefresh: "readonly",
    RegisterSettingsListRowSync: "readonly",
    RunConsoleCommandBestEffort: "readonly",
    ResolveAnnouncerEventForVolume: "readonly",
    PlayAnnouncerPreviewSound: "readonly",
    PlayAnnouncerBridgeVariantPreviewSound: "readonly",
    PublishPaletteColorBridge: "readonly",
    WarnLog: "readonly",
    gSearchCollectMode: "readonly",
    gSearchCollectState: "readonly",
    gSearchResultRenderMode: "readonly",
    BuildSearchCollectedRow: "readonly",
    gRuntimeToggleState: "writable",
    gRuntimeSliderState: "writable",
    gRuntimeButtonGroupConfig: "writable",
    gRuntimeButtonGroupRefreshers: "writable",
    gRuntimeSliderResetters: "writable",
    gEnumSectionSyncCallbacks: "writable",
    gArcadeOnDeathSyncFns: "writable",
    SyncTabActiveStates: "readonly",
    ClearSettingsSearchQuery: "readonly",
    SetActiveTabAndRefresh: "readonly",
};

// Node globals for tests, simulators, and build scripts.
const NODE_GLOBALS = {
    global: "readonly",
    require: "readonly",
    module: "writable",
    exports: "writable",
    process: "readonly",
    console: "readonly",
    __dirname: "readonly",
    __filename: "readonly",
    Buffer: "readonly",
    describe: "readonly",
    it: "readonly",
    test: "readonly",
    before: "readonly",
    after: "readonly",
    beforeEach: "readonly",
    afterEach: "readonly",
};

// Standard ES built-ins
const SHARED_GLOBALS = {
    globalThis: "readonly",
    crypto: "readonly",
    Math: "readonly",
    JSON: "readonly",
    Date: "readonly",
    Array: "readonly",
    Object: "readonly",
    String: "readonly",
    Number: "readonly",
    Boolean: "readonly",
    RegExp: "readonly",
    Error: "readonly",
    Promise: "readonly",
    Map: "readonly",
    Set: "readonly",
    Function: "readonly",
    Uint8Array: "readonly",
    Uint32Array: "readonly",
    parseInt: "readonly",
    parseFloat: "readonly",
    isFinite: "readonly",
    isNaN: "readonly",
    encodeURIComponent: "readonly",
    decodeURIComponent: "readonly",
    setTimeout: "readonly",
    clearTimeout: "readonly",
    setInterval: "readonly",
    clearInterval: "readonly",
};

// Correctness rules only — no cosmetic formatting noise
const BUG_RULES = {
    "no-undef": "error",
    "no-unreachable": "error",
    "no-dupe-keys": "error",
    "no-dupe-args": "error",
    "no-duplicate-case": "error",
    "no-func-assign": "error",
    "no-cond-assign": ["error", "except-parens"],
    "no-constant-condition": ["error", { checkLoops: false }],
    "no-self-assign": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "no-sparse-arrays": "error",
    "no-fallthrough": "error",
    "no-empty": ["error", { allowEmptyCatch: true }],
    "no-shadow-restricted-names": "error",
    "no-unsafe-negation": "error",
    "no-compare-neg-zero": "error",
    "no-irregular-whitespace": "error",
    "no-template-curly-in-string": "error",
    "getter-return": "error",
    "no-obj-calls": "error",
    "no-unmodified-loop-condition": "error",
    "no-unsafe-finally": "error",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-unused-vars": ["warn", { args: "none", caughtErrors: "none", varsIgnorePattern: "^_" }],
};

module.exports = [
    {
        ignores: [
            "node_modules/**",
            "build_mod/**",
            "scripts/simulator/perf/runs/**",
            "tools/local_chat_translation/**",
            "_restore_*/**",
            "backup_*/**",
        ],
    },

    // Shipped Panorama scripts (core, manifests, features, infrastructure)
    {
        files: ["panorama/scripts/**/*.js"],
        ignores: ["panorama/scripts/tools/qollock_smoke_test.js"],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "script",
            globals: Object.assign({}, SHARED_GLOBALS, PANORAMA_GLOBALS, QOLLOCK_GLOBALS),
        },
        rules: BUG_RULES,
    },

    // Settings Menu context scripts (hud_escape_menu.xml scope)
    {
        files: [
            "panorama/scripts/ql_settings*.js",
            "panorama/scripts/ql_settings_loc/**/*.js",
            "panorama/scripts/ql_arcade_games.js",
            "panorama/scripts/ql_update_checker.js",
            "panorama/scripts/ui/**/*.js",
        ],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "script",
            globals: Object.assign({}, SHARED_GLOBALS, PANORAMA_GLOBALS, QOLLOCK_GLOBALS, SETTINGS_GLOBALS),
        },
        rules: BUG_RULES,
    },

    // Valve minifier ASI protection for shipped scripts
    {
        files: ["panorama/scripts/**/*.js"],
        ignores: ["panorama/scripts/tools/**"],
        rules: {
            "operator-linebreak": ["error", "after", { overrides: { "?": "ignore", ":": "ignore" } }],
        },
    },

    // Node test runner & tooling scripts
    {
        files: [
            "tests/**/*.js",
            "scripts/**/*.js",
            "panorama/scripts/tools/**/*.js",
            "eslint.config.js",
        ],
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: "script",
            globals: Object.assign({}, SHARED_GLOBALS, NODE_GLOBALS, PANORAMA_GLOBALS, QOLLOCK_GLOBALS),
        },
        rules: BUG_RULES,
    },
];
