// ==========================================================================
// ql_state.js — QOLLOCK shared state and panel cache accessors
// ==========================================================================
// Provides: State object (global singleton), GetCachedPanel, SetCachedPanel,
//           ClearPanelCache, SweepStalePanelCache, ResolveCachedPanel
// Publishes to: QOL.* namespace, window.State
// ==========================================================================
var State;
(function() {
    'use strict';

    // IsPanelValid inline stub — mirrors ql_utils.js definition.
    var IsPanelValid = (typeof QOL_UTILS !== "undefined" && QOL_UTILS.IsPanelValid)
        ? QOL_UTILS.IsPanelValid
        : function(p) { return p != null && typeof p.IsValid === "function" && p.IsValid(); };

    // ── Panel cache accessors ──
    var GetCachedPanel = function(k) {
        var p = State.cachedPanels[k];
        if (IsPanelValid(p)) return p;
        State.cachedPanels[k] = null;
        return null;
    };
    var SetCachedPanel = function(k, p) {
        if (p !== null && p !== undefined && !IsPanelValid(p) && !Array.isArray(p)) {
            $.Msg("[QOLLock][WARN] SetCachedPanel('" + String(k) + "') called with non-panel value (type=" + typeof p + "). Use direct State.cachedPanels assignment for non-panel data.");
        }
        State.cachedPanels[k] = (p === null || p === undefined || IsPanelValid(p) || Array.isArray(p)) ? p : null;
        // Dual-write to typed cache (Phase 3 — ql_panelcache.js)
        if (typeof PanelCache !== "undefined" && PanelCache) {
            if (p === null || p === undefined) {
                PanelCache._clearKey(k);
            } else if (Array.isArray(p)) {
                PanelCache.setList(k, p);
            } else if (IsPanelValid(p)) {
                PanelCache.setPanel(k, p);
            } else {
                // Non-panel, non-array value — store as data
                PanelCache.setData(k, p);
            }
        }
    };
    var ClearPanelCache = function() {
        State.cachedPanels = {};
        // Clear typed caches (Phase 3 — ql_panelcache.js)
        if (typeof PanelCache !== "undefined" && PanelCache) {
            PanelCache.clear();
        }
    };
    var SweepStalePanelCache = function() {
        var swept = 0;
        var cache = State.cachedPanels;
        for (var k in cache) {
            if (cache.hasOwnProperty(k) && cache[k] && typeof cache[k].IsValid === "function" && !IsPanelValid(cache[k])) {
                cache[k] = null;
                swept++;
            }
        }
        return swept;
    };
    var ResolveCachedPanel = function(parent, cacheKey, traverseId) {
        var panel = IsPanelValid(State.cachedPanels[cacheKey]) ? State.cachedPanels[cacheKey] : null;
        if (!panel && parent && parent.FindChildTraverse) {
            panel = parent.FindChildTraverse(traverseId);
            State.cachedPanels[cacheKey] = panel || null;
        }
        return panel;
    };

    // ── State object ──
    State = {
        lastTime: -1, 
        lastIntervalAlert: 0,
        lastMinimapAlert: 0,
        triggeredOneTimers: {},
        lastRawConfig: null, 
        lastZoomState: null, 
        cachedPanels: {},
        customMouseCursorPanel: null,
        customMouseCursorImage: null,
        customMouseCursorClassActive: false,
        customMouseCursorLastX: null,
        customMouseCursorLastY: null,
        customMouseCursorImageBound: false,
        onDeathArcadeWasDead: false,
        onDeathArcadeLastTriggerMs: 0,
        onDeathArcadeRespawnPanel: null,
        onDeathArcadeRequestSerial: 0,
        allBindingsBoxes: [],
        forceRefreshTicks: 0,
        lastItemCount: 0,
        lastIndicatorCount: 0,
        lastIndicatorConfigSig: "",
        lastIndicatorHideModesSig: "",
        indicatorPanelsCache: [],
        indicatorMetaCache: [],
        runtimeTaskNextMs: {},
        minimapDrawOverUiActive: false,
        minimapDrawOverUiOriginalParent: null,
        minimapDrawOverUiOriginalIndex: -1,
        minimapDrawOverUiNextReassertMs: 0,
        fgHeroImageOriginalParent: null,
        fgHeroImageOriginalIndex: -1,
        fgHeroImageMoved: false,
        fgHeroImageSourceProbeNextMs: 0,
        // Last hero signature ResolveFgHeroRefreshSignal returned, so a tick
        // throttled by fgHeroImageSourceProbeNextMs reuses it instead of seeing
        // an empty signature and tearing down the hero-image attachment.
        fgHeroImageLastResolvedSig: "",
        fgHeroImageCurrentSig: "",
        fgHeroImagePendingAttachMs: 0,
        fgHeroImageRefreshBounceNextMs: 0,
        fgHeroImageSwapCandidateSig: "",
        fgHeroImageSwapCandidateHits: 0,
        fgHeroImageSwapCandidatePanel: null,
        minimapLocalPlayerPanelNextScanMs: 0,
        minimapLocalMainImageNextScanMs: 0,
        // Current escalating backoff for the two minimap local-player scans. Both
        // fall back to a whole-HUD class traversal, so a miss must not retry at the
        // 90ms fast cooldown forever. See NextMinimapScanBackoffMs in ql_core.js.
        minimapLocalPlayerPanelScanBackoffMs: 0,
        minimapLocalMainImageScanBackoffMs: 0,
        minimapRotateLastDeg: null,
        minimapRotateSmoothedDeg: null,
        minimapRotateLastUpdateMs: 0,
        minimapRotateLastHeadingDeg: null,
        minimapRotateLastHeadingMs: 0,
        minimapRotateHeadingVelDegPerSec: 0,
        minimapRotateLastValidHeadingDeg: null,
        minimapRotateLastValidHeadingMs: 0,
        minimapHeadingSnapshotMs: 0,
        minimapHeadingSnapshotAggressive: false,
        minimapHeadingSnapshotHeading: null,
        minimapHeadingSnapshotPlayerPanel: null,
        minimapHeadingSnapshotMainImage: null,
        minimapFlipClassCache: { panel: null, values: {} },
        minimapMinimalistOpacityApplied: false,
        minimapRuntimeSig: "",
        minimapIconColorStyleSig: "",
        minimapCastRangeScaleApplied: false,
        minimapCrateOverlayBuildSig: "",
        showBuildIdStyleSig: "",
        showBuildIdLastLabel: null,
        compass: {
            enabled: false,
            showSpeed: true,
            lastDegreeText: "",
            layoutSig: "",
            nextSpeedSampleMs: 0,
            lastSpeedValueText: "--",
            scale: 100,
            stretchX: 100,
            stretchY: 100,
            offsetX: 0,
            offsetY: 120,
            lastPosX: null,
            lastPosY: null,
            lastPosTimeMs: 0,
            speedSmoothed: null,
            speedDisplay: null,
            speedSamples: null,
            tickClassSigs: [],
            tickXTexts: [],
            errorNextLogMs: 0
        },
        lastConfig: null,
        zipBoostLastState: null,
        zipBoostReadyFlashUntilMs: 0,
        zipBoostDisplayMode: "",
        zipBoostLastLayoutSig: "",
        zipBoostLastClassSig: "",
        zipBoostLastTitle: "",
        zipBoostLastStatus: "",
        zipBoostNextSourceSearchMs: 0,
        imagesInChatTopNextSearchMs: 0,
        imagesInChatBottomNextSearchMs: 0,
        imagesInChatTopIdleMisses: 0,
        imagesInChatBottomIdleMisses: 0,
        imagesInChatTopWatermark: "",
        imagesInChatBottomWatermark: "",
        imagesInChatTopFullScanNextMs: 0,
        imagesInChatBottomFullScanNextMs: 0,
        imagesInChatTopMessageCache: [],
        imagesInChatBottomMessageCache: [],
        unsecuredSouls: {
            displayMode: "",
            lastLayoutSig: "",
            lastClassSig: "",
            lastTitle: "",
            lastStatus: "",
            lastSouls: -1,
            lastSampleMs: 0,
            rateEma: 0,
            rateLastUpdateMs: 0,
            etaEndMs: 0,
            nextSourceSearchMs: 0,
            hudStyleSig: "",
            hudBaseX: null,
            hudBaseY: null,
            hudLabel: null,
            hudMirrorLabel: null,
            hudMirrorIcon: null,
            hudMirrorText: null,
            hudNextSearchMs: 0
        },
        signatureCooldownFlashSlots: null,
        signatureCooldownFlashNextScanMs: 0,
        signatureCooldownFlashUntilById: {},
        signatureCooldownFlashPressById: {},
        signatureCooldownFlashWasEnabled: false,
        statBonuses: {
            displayMode: "",
            lastLayoutSig: "",
            lastClassSig: "",
            lastTitleText: "",
            lastFireRateText: "",
            lastAbilityCooldownText: "",
            lastSpiritPowerText: "",
            lastClipSizeText: "",
            lastWeaponDamageText: "",
            lastMaxHealthText: "",
            nextSourceSearchMs: 0,
            nextSourceSearchByKey: {},
            // Escalating retry interval for stat source lookups, and the shop
            // state the last lookup ran under. See ResolveStatBonusesSource in
            // ql_core.js for why a flat retry was expensive.
            sourceSearchBackoffMs: 0,
            lastSourceSearchShopOpen: null,
            nextIdolCountSearchMs: 0,
            nextTooltipScanMs: 0,
            goldenValues: {},
            debugLastSig: "",
            debugNextMs: 0
        },
        combatStatus: {
            displayMode: "",
            lastLayoutSig: "",
            lastClassSig: "",
            lastStateText: "",
            lastTimerText: "",
            lastCombatMs: 0,
            combatStartMs: 0,
            signalActive: false,
            nextAlertProbeMs: 0
        },
        enemyColoredHealthPanelCache: [],
        enemyColoredHealthPanelCacheNextMs: 0,
        enemyColoredHealthNextUpdateMs: 0,
        enemyColoredHealthDebugLastSig: "",
        enemyColoredHealthDebugNextMs: 0,
        combatIndicatorDebugLastSig: "",
        combatIndicatorDebugNextMs: 0,
        enemyColoredHealthLastScanStats: null,
        enemyColoredHealthFriendlyTeamClass: "",
        enemyColoredHealthFriendlyTeamNextMs: 0,
        allyColoredHealthPanelCache: [],
        allyColoredHealthPanelCacheNextMs: 0,
        allyColoredHealthNextUpdateMs: 0,
        enemyUnitStatusOldPanelCacheRoot: null,
        enemyUnitStatusOldPanelCache: [],
        enemyUnitStatusOldPanelCacheNextMs: 0,
        enemyUnitStatusOldPanelScanStats: null,
        ultCdSlotCache: null,
        ultCdSlotNextRecheckMs: null,
        ultCdSlotFullRescanAtMs: 0,
        enemyUltOldPanelCache: [],
        enemyUltOldPanelCacheNextMs: 0,
        enemyUltOldNextUpdateMs: 0,
        enemyUltOldTopBarNameByIndex: null,
        enemyUltOldTopBarNameToIndex: null,
        enemyUltOldTopBarNameToIndices: null,
        enemyUltOldTopBarEnemyIndices: null,
        enemyUltOldTopBarNameNextMs: 0,
        enemyUltOldDebugLastSig: "",
        enemyUltOldDebugNextMs: 0,
        enemyV2EnhancedBridgeLastValue: "",
        enemyV2UltBridgeLastValue: "",
        enemyV2LevelBridgeLastValue: "",
        enemyV2BridgeEventEnhanced: null,
        enemyV2BridgeEventUlt: null,
        enemyV2BridgeEventLevel: null,
        enemyV2BridgeEventLastMs: 0,
        enemyV2AttrBridgeLastSig: "",
        itemMirror: {
            probeLastScanMs: 0,
            probeLastSignature: "",
            probeWasEnabled: false,
            displayMode: "",
            lastLayoutSig: "",
            lastRowOpacityPanel: null,
            lastRowOpacityText: "",
            fastModeUntilMs: 0,
            debugLastMs: 0,
            debugLastSig: "",
            wasOnCooldown: false,
            readyAnimUntilMs: 0,
            cdLastDeg: null,
            cdLastMs: 0,
            cdSlopeEma: null,
            cdDisplayLock: null,
            lastSrc: "",
            lastClip: "",
            classCache: {},
            visualOpacityText: "1.00",
            sources: [],
            nextSourceId: 1,
            nextAcquireOrder: 1,
            slotStates: {},
            runtimePanelIds: [],
            nextRuntimePanelId: 1,
            exceptionGroupAssignments: {},
            lastShopOpen: false
        },
        customHudSuppressed: false,
        keyboardBoxCaches: [],
        heroShopNextSearchMs: 0,
        laneWithPartyNextApplyMs: 0,
        laneWithPartyLastApplyMs: 0,
        laneWithPartyLastState: "",
        heroShopMainPanelStyleSig: "",
        recentPurchaseFiltersCreated: false,
        recentPurchaseLastFilterSig: null,
        recentPurchaseLastFirstChild: null,
        recentPurchaseLastVisibilitySig: null,
        recentPurchaseWasInHideout: null,
        recentPurchaseQuickSeenKeys: {},
        recentPurchaseQuickInitialized: false,
        recentPurchaseQuickActiveEntries: [],
        heroPopup: {
            panelsByHero: {},
            activeEntriesByHero: {},
            lastEntryTime: {},
            playerCardCache: {},
            overlapPending: false,
            mapState: 0,
            buildGen: 0,
            ultCooldownsEnabled: false
        },
        topBarRuntimeStyleSig: "",
        bottomBarRuntimeStyleSig: "",
        bottomBarCurrencyColorStyleSig: "",
        bottomBarCurrencyDebugLastSig: "",
        bottomBarCurrencyDebugNextMs: 0,
        itemsRuntimeStyleSig: "",
        staminaChargeAngleStyleSig: "",
        staminaChargeColorStyleSig: "",
        staminaChargeColorPanelCache: [],
        staminaChargeColorPanelCacheNextMs: 0,
        soulsRuntimeStyleSig: "",
        urnTrackerDisplayMode: "",
        urnTrackerLastClass: "",
        urnTrackerLastText: "",
        urnTrackerLastDebugSig: "",
        urnTrackerLastIdolMood: "",
        urnTrackerIdolNextScanMs: 0,
        urnTrackerNextSampleMs: 0,
        urnTrackerNextPanelSearchMs: 0,
        urnTrackerCachedState: null,
        urnTimerDisplayMode: "",
        urnTimerLastText: "",
        riftTimerDisplayMode: "",
        riftTimerLastText: "",
        riftTimerLastMode: "",
        riftTimerRiftAccumulator: 0,
        riftTimerWarningGameSec: 0,
        riftTimerWarningActive: false,
        riftTimerLastCapturePointCheckMs: 0,
        riftTimerCapturePointValid: false,
        riftTimerLastSpawnCycleMs: 0,
        spm: {
            nextSampleMs: 0,
            panelCacheNextMs: 0,
            playerHistory: null,
            playerPanels: null,
            playerDisplayLabels: null,
            playerTeamByIndex: null,
            playerHiddenGoldLabels: null,
            playerSoulsLabels: null,
            cachedFriendlyScore: null,
            cachedEnemyScore: null,
            cachedFriendlyLabel: null,
            cachedEnemyLabel: null,
            teamHistory: null,
            lastClockSec: null,
            warmupActive: true,
            wasDisabled: false,
            needsFullPlayerCache: true,
            playerRefreshCursor: 0,
            playerRefreshRemaining: 0
        },
        topbarPlayerPanelRoot: null,
        topbarPlayerPanels: null,
        topbarPlayerPanelLastScanMs: null,
        topbarNicknamesWasEnabled: false,
        topbarNicknamesNextRefreshMs: 0,
        topbarNicknamePlayers: null,
        topbarNicknameLabels: null,
        topbarNicknameSourceLabels: null,
        topbarNicknameFallbackLabels: null,
        topbarNicknameResolvedTexts: null,
        topbarNicknameResolveStates: null,
        topbarNicknameRetryNextMs: null,
        topbarNicknamesWasInHideout: false,
        topbarNicknamesLastClockSec: null,
        statlockerWasEnabled: false,
        statlockerNextScanMs: 0,
        statlockerScanMisses: 0,
        statlockerCorePanels: null,
        statlockerButtons: null,
        unspentNextSampleMs: 0,
        unspentPanelCacheNextMs: 0,
        unspentPlayerPanels: null,
        unspentModsContainers: null,
        unspentDisplayLabels: null,
        unspentSoulValueLabelsPrimary: null,
        unspentSoulValueLabelsFallback: null,
        unspentCachedSpentSouls: null,
        unspentModsChildCount: null,
        unspentNextTierScanMs: null,
        unspentLastDisplayText: null,
        unspentWasDisabled: false,
        topbarSoulSnapshot: null,
        topbarSoulSnapshotUntilMs: 0,
        rejuvState: null,
        rejuvWasDisabled: false,
        minimapObjectiveBuffClassCache: { panel: null, values: {} },
        minimapObjectiveBuffBridgeLeftClassCache: { panel: null, values: {} },
        minimapObjectiveBuffBridgeRightClassCache: { panel: null, values: {} },
        minimapObjectiveRejuvClassCache: { panel: null, values: {} },
        minimapObjectiveScaleSig: "",
        legacyCooldownsUiFlag: null,
        ammoPanelStyleSig: "",
        reloadCooldownStyleSig: "",
        reloadCdLastDeg: null,
        reloadCdLastMs: 0,
        reloadCdSlopeEma: null,
        reloadCdDisplayLock: null,
        reloadCdDirection: 0,
        accountProbeStartMs: 0,
        accountProbeWindowEndMs: 0,
        accountProbeNextMs: 0,
        accountProbeReportNextMs: 0,
        accountProbeFoundId: "",
        accountProbeDone: false,
        accountProbeMissLogged: false,
        accountProbeDeepScanNextMs: 0,
        accountProbeScans: 0,
        accountProbeLastPanelsScanned: 0,
        accountProbeApiHintLogged: false,
        accountProbeFoundSource: "",
        accountProbeCandidateId: "",
        accountProbeCandidateHits: 0,
        accountPresetTestActive: false,
        accountPresetBootstrapDone: false,
        accountPresetBootstrapAccountId: "",
        accountPresetRawOverride: "",
        accountPresetUiMarker: "",
        accountPresetSessionLockId: "",
        accountPresetLastAppliedRaw: "",
        accountPresetBootstrapAtMs: 0,
        accountPresetLastUserEditRev: 0,
        accountPresetManualUnlockActive: false,
        accountPresetManualUnlockAccountId: "",
        buildCategoryPayloadNextScanMs: 0,
        buildCategoryPayloadLastAppliedAccountId: "",
        buildCategoryPayloadLastAppliedText: "",
        buildCategoryPayloadLastParseErrorKey: "",
        selectHeroLastTarget: "",
        selectHeroLastMs: 0,
        openItemShopLastMs: 0,
        buildCategoryPayloadHeroProbeStage: "",
        buildCategoryPayloadHeroProbeNextMs: 0,
        buildCategoryPayloadHeroProbeDidSwitch: false,
        buildCategoryPayloadHeroProbeReturnHero: "",
        buildCategoryPayloadHeroProbeReturnHeroSource: "",
        buildCategoryPayloadHeroProbeAccountId: "",
        buildCategoryPayloadHeroProbeDoneAccountId: "",
        buildCategoryPayloadHeroProbeStartedMs: 0,
        buildCategoryPayloadHeroProbeBootstrapStartedMs: 0,
        buildCategoryPayloadHeroProbeSwitchStartMs: 0,
        buildCategoryPayloadHeroProbeSwitchRetries: 0,
        buildCategoryPayloadHeroProbeScanStartedMs: 0,
        buildCategoryPayloadHeroProbeShopProbeTried: false,
        buildCategoryPayloadStorageConfirmSig: "",
        buildCategoryPayloadStorageConfirmHits: 0,
        storageHeroSignatureConfirmSig: "",
        storageHeroSignatureConfirmHits: 0,
        storageHeroSignatureLastDetail: "",
        buildCategoryPayloadHeroProbeRetryAfterMs: 0,
        buildCategoryPayloadHeroProbeMisses: 0,
        buildCategoryPayloadMissingScanAdvances: 0,
        buildCategoryPayloadCorruptRepairActive: false,
        buildCategoryPayloadCorruptRepairStartedMs: 0,
        buildCategoryPayloadCorruptRepairCleared: false,
        buildCategoryPayloadCorruptRepairClearRetries: 0,
        buildCategoryPayloadCorruptRepairClearNextMs: 0,
        buildCategoryPayloadCorruptRepairClearEmptyHits: 0,
        buildCategoryPayloadCorruptRepairBrowseReady: false,
        buildCategoryPayloadCorruptRepairLastDeleteTitle: "",
        buildCategoryPayloadCorruptRepairSameTitleDeleteHits: 0,
        buildCategoryPayloadCorruptRepairPostClearUntilMs: 0,
        buildCategoryPayloadShopOpenActionNextMs: 0,
        buildCategoryPayloadFavoritesActionNextMs: 0,
        buildCategoryPayloadBrowseActionNextMs: 0,
        buildCategoryPayloadDoneRearmNextMs: 0,
        buildCategoryPayloadDoneRearmAttempts: 0,
        buildCategoryPayloadStartupConsumedAccountId: "",
        buildCategoryPayloadStartupConsumedResult: "",
        buildCategoryPayloadStartupSuppressedForSession: false,
        buildCategoryPayloadStartupSuppressedReason: "",
        buildCategoryPayloadStartupSuppressedAccountId: "",
        buildCategoryPayloadDormant: false,
        buildCategoryPayloadDormantReason: "",
        buildCategoryPayloadDormantWakeCheckNextMs: 0,
        buildCategoryPayloadLoaderSessionCreateAttempts: 0,
        buildCategoryPayloadSourceBootstrapStage: "",
        buildCategoryPayloadSourceBootstrapNextMs: 0,
        buildCategoryPayloadSourceBootstrapRetries: 0,
        buildCategoryPayloadSessionSwitchConsumed: false,
        buildCategoryPayloadHeroProbeInitAttempted: false,
        buildCategoryPayloadHeroProbeInitStage: "",
        buildCategoryPayloadHeroProbeInitNextMs: 0,
        buildCategoryPayloadHeroProbeInitRetries: 0,
        buildCategoryPayloadHeroProbeInitCreateAttempts: 0,
        buildCategoryPayloadHeroProbeInitCreateVerifyUntilMs: 0,
        buildCategoryPayloadPostSwitchShopPulseDone: false,
        buildCategoryPayloadPromptEscClosed: false,
        buildCategoryPayloadDefaultBootstrapPayloadText: "",
        buildCategoryPayloadDefaultBootstrapRetries: 0,
        buildCategoryPayloadDefaultBootstrapSaveToken: "",
        buildCategoryPayloadDefaultBootstrapSaveVerifyHits: 0,
        buildCategoryPayloadDefaultBootstrapPostSavePrompt: false,
        buildCategoryPayloadPostSavePromptFallbackUsed: false,
        buildCategoryPayloadSkyrunnerHeaderConfirmed: false,
        buildCategoryPayloadSkyrunnerHeaderConfirmedMs: 0,
        settingsLoaderSessionAccountId: "",
        settingsLoaderSessionActive: false,
        settingsLoaderSessionCompleted: false,
        settingsLoaderCurrentStep: "",
        settingsLoaderDetail: "",
        settingsLoaderResult: "",
        // Tri-state record of whether this session's config was read successfully.
        // Guards the save pipeline against writing defaults over a stored config
        // that exists but could not be read.
        //   "pending" — load has not conclusively finished (also the pre-load state)
        //   "loaded"  — our payload was read, OR storage is genuinely empty
        //   "failed"  — a storage build exists but no payload could be read from it,
        //               so real user data may be sitting there unread
        configLoadState: "pending",
        configLoadStateDetail: "",
        configLoadStateAtMs: 0,
        // Set when a save is refused for an unread config; a second press inside
        // this window is treated as consent to overwrite.
        buildSaveOverwriteArmedUntilMs: 0,
        settingsLoaderShowUntilMs: 0,
        settingsLoaderNextReassertMs: 0,
        settingsLoaderLastRenderSig: "",
        settingsLoaderDebugOverlayLine: "",
        settingsLoaderDebugLastSig: "",
        settingsLoaderDebugNextMs: 0,
        settingsLoaderTraceLastSig: "",
        settingsLoaderTraceNextMs: 0,
        settingsLoaderStepStates: {},
        settingsLoaderSkipRequested: false,
        saveSettingsLoaderSessionToken: "",
        saveSettingsLoaderSessionActive: false,
        saveSettingsLoaderSessionCompleted: false,
        saveSettingsLoaderCurrentStep: "",
        saveSettingsLoaderDetail: "",
        saveSettingsLoaderResult: "",
        saveSettingsLoaderShowUntilMs: 0,
        saveSettingsLoaderNextReassertMs: 0,
        saveSettingsLoaderLastRenderSig: "",
        saveSettingsLoaderStepStates: {},
        clearSettingsLoaderSessionToken: "",
        clearSettingsLoaderSessionActive: false,
        clearSettingsLoaderSessionCompleted: false,
        clearSettingsLoaderCurrentStep: "",
        clearSettingsLoaderDetail: "",
        clearSettingsLoaderResult: "",
        clearSettingsLoaderShowUntilMs: 0,
        clearSettingsLoaderNextReassertMs: 0,
        clearSettingsLoaderLastRenderSig: "",
        clearSettingsLoaderStepStates: {},
        buildSaveActiveToken: "",
        buildSaveStage: "",
        buildSaveStartedMs: 0,
        buildSaveNextActionMs: 0,
        buildSaveRetries: 0,
        buildSaveDidSwitchToStorageHero: false,
        buildSaveCaptureStartedMs: 0,
        buildSaveReturnHero: "",
        buildSaveStorageHeroConfirmed: false,
        buildSaveStorageHeroConfirmedSource: "",
        buildSaveStorageConfirmRetries: 0,
        buildSaveStorageSwitchRetries: 0,
        buildSaveStorageConfirmStartedMs: 0,
        buildSaveStorageLastSwitchMs: 0,
        buildSaveStorageShopReopenNextMs: 0,
        buildSaveStorageShopReopenAttempts: 0,
        buildSaveFavoritesActionNextMs: 0,
        buildSaveStorageProvisionalHits: 0,
        buildSaveMutationClosed: false,
        buildSaveTargetBuildPanel: null,
        buildSaveTargetBuildSig: "",
        buildSaveTargetBuildTitle: "",
        buildSaveTargetStableHits: 0,
        buildSaveTargetDriftRetries: 0,
        buildSaveTargetQuietUntilMs: 0,
        // (debug state fields removed — buildSaveDebugLastSig, buildSaveDebugNextMs)
        buildClearActiveToken: "",
        buildClearStage: "",
        buildClearStartedMs: 0,
        buildClearNextActionMs: 0,
        buildClearRetries: 0,
        buildClearDeletedCount: 0,
        buildClearEmptyConfirmHits: 0,
        buildClearDidSwitchToStorageHero: false,
        buildClearReturnHero: "",
        buildClearStorageHeroConfirmed: false,
        buildClearStorageHeroConfirmedSource: "",
        buildClearStorageConfirmRetries: 0,
        buildClearStorageSwitchRetries: 0,
        buildClearStorageConfirmStartedMs: 0,
        buildClearUserShopGateSatisfied: false,
        // Prune mode: a clear request that spares the build holding the payload,
        // used to tidy up junk builds after a verified save instead of wiping
        // everything. See AdvanceBuildClearRequestStage in ql_core.js.
        buildClearPreservePayload: false,
        buildClearSkippedCount: 0,
        buildClearLastEntryCount: -1,
        buildClearNoProgressHits: 0,
        // (debug state fields removed — buildClearDebugLastSig, buildClearDebugNextMs, buildClearDebugOverlayLine)
        heroReturnDebugLastSig: "",
        heroReturnDebugNextMs: 0,
        heroDetectDebugLastSig: "",
        heroDetectDebugNextMs: 0,
        heroDetectLastResolved: "",
        heroDetectLastSource: "",
        heroResolveLastSource: "",
        heroDetectLastKnownPlayableHero: "",
        heroDetectNextProbeMs: 0,
        heroDetectAbilityProgressNextScanMs: 0,
        heroDetectAbilityProgressLastHero: "",
        heroDetectCaptureAbilityNextScanMs: 0,
        heroDetectCaptureAbilityLastHero: "",
        heroDetectAbilityHintNextScanMs: 0,
        heroDetectAbilityHintLastHero: "",
        heroDetectLogoSpotlightNextScanMs: 0,
        heroDetectLogoSpotlightLastHero: "",
        heroDetectCaptureSnapshotNextScanMs: 0,
        heroDetectCaptureSnapshotLastHero: "",
        heroDetectDeepScanNextMs: 0,
        heroDetectDeepScanExtendedNextMs: 0,
        heroDetectNoMatchStreak: 0,
        heroDetectLastDeepScanHero: "",
        heroDetectLastDeepScanDetail: "",
        heroPersistLastWriteMs: 0,
        heroPersistLastWrittenHero: "",
        heroPersistNextCheckMs: 0,
        heroDetectApiHintsLogged: false,
        heroRestorePendingTarget: "",
        heroRestorePendingStartedMs: 0,
        heroRestorePendingNextMs: 0,
        heroRestorePendingRetries: 0,
        heroRestorePendingContext: "",
        heroRestoreShopPulseNextMs: 0,
        passiveCooldownModeApplied: "",
        oldItemCooldownStyleSig: "",
        oldItemCooldownStylePanel: null,
        oldItemCooldownRuntimeWasActive: false,
        coloredHealthbarBridgeValue: "",
        playerHealthbarAccentColorSig: "",
        playerHealthbarAccentColorPanels: [],
        playerHealthbarAccentColorToken: 0,
        minimalistHealthbarOffsetSig: "",
        minimalistHealthbarOffsetApplied: false,
        minimalistHealthbarOffsetPanel: null,
        playerHealthbarScaleOpacityRuntimeApplied: false,
        fgHeroImageRuntimeStyleSig: "",
        fgHeroRuntimeLevelPanel: null,
        fgHeroRuntimeHeroPanel: null,
        budhudWasEnabled: false,
        budhudNextUpdateMs: 0,
        budhudLastColor: "",
        budhudLastPercentText: "",
        budhudCurrentLabelBaseColor: "",
        budhudCurrentLabelBaseColorCaptured: false,
        damageReportOffsetSig: "",
        damageReportOffsetApplied: false,
        damageReportOffsetPanel: null,
        chatStyleSig: "",
        chatStyleApplied: false,
        chatStylePanel: null,
        coloredHealthbarLastColor: "",
        coloredHealthbarEnabledPrev: null,
        coloredHealthbarPulseDir: 1,
        coloredHealthbarPulseVal: 0,
        coloredHealthbarZeroHeightStreak: 0,
        enemyColoredHealthEnabledPrev: null,
        enemyColoredHealthPulseDir: 1,
        enemyColoredHealthPulseVal: 0,
        allyColoredHealthEnabledPrev: null,
        allyColoredHealthPulseDir: 1,
        allyColoredHealthPulseVal: 0,
        rootClassCache: { panel: null, values: {} },
        coreRootStaticSig: "",
        quickbuyClassCache: { panel: null, values: {} },
        passiveHudClassCache: { panel: null, values: {} },
        abilitiesClassCache: { panel: null, values: {} },
        heroShopClassCache: { panel: null, values: {} },
        recentPurchasesContainer: null,
        recentPurchasesPanel: null,
        quickPurchasesPanel: null,
        cachedRejuvTimer: null,
        targetShapesCache: [],
        hintContainerCache: [],
        targetShapeStyleSig: "",
        nextTargetShapeRefreshMs: 0,
        targetShapeHadNonDefaultRuntime: false,
        targetShapeDebugLastSig: "",
        targetShapeDebugNextMs: 0,
        unitTargetBootstrapTryCount: 0,
        unitTargetBootstrapDone: false,
        perfEnabled: false,
        perfDetailed: false,
        perfWindowStartMs: 0,
        perfNextFlushMs: 0,
        perfStats: {},
        perfLoopCount: 0,
        perfCompassLoopCount: 0,
        perfLastLoopStartMs: 0,
        perfLastCompassStartMs: 0,
        coreLoopTickSerial: 0,
        coreLoopPhaseLast: 0,
        runtimeGateSig: "",
        runtimeGates: null,
        runtimeGateConfigRef: null,
        runtimeGateRaw: null,
        runtimeGateHideoutConnected: null,
        runtimeGateHasConfigSource: null,
        coreRootGateSig: "",
        onDeathArcadeRuntimeWasActive: false,
        healthbarVisDebugLastSig: "",
        healthbarVisDebugNextMs: 0,
        loopErrorNextLogMs: 0,
        // ── Minecraft healthbar ────────────────────────────────────────────────
        mcWasEnabled: false,
        mcNextUpdateMs: 0,
        mcHeartsBlinkTimer: null,
        mcLowHealthJiggleTimer: null,
        mcHealingWaveTimer: null,
        mcLastBlinkHalfSegments: null,
        mcHeartsBlinking: false,
        mcHeartsBlinkPhase: 0,
        mcLowHealthJiggleActive: false,
        mcHealingWaveActive: false,
        mcHealingWaveCurrentIndex: 0,
        mcIsAfflicted: false,
        mcCheckModifierNextMs: 0,
        mcLastModifierResult: false,
        mcLoggedHealthContainerMiss: false,
        mcLoggedGoldApMiss: false,
        mcLoggedBulletBarrierMiss: false,
        mcHeartSlots: [],
        mcHeartContainerImages: [],
        mcHeartHealingImages: [],
        mcHeartDeferredImages: [],
        mcHeartFillImages: [],
        mcHeartsCapacity: 0,
        mcHeartsRowCount: 0,
        mcLastVisibleHeartsCount: 0,
        mcBarrierHeartsPanels: [],
        mcBarrierHeartContainerImages: [],
        mcBarrierHeartFillImages: [],
        mcBarrierHeartsCapacity: 0,
        mcCachedFoodIcons: [],
        mcLastIsBlinkOn: null,
        mcLastContainerHeartsNeeded: -1,
        mcLastContainerLastSlotIsHalf: null,
        mcLastFillFullHearts: -1,
        mcLastFillHasHalf: null,
        mcLastFillAfflicted: null,
        mcLastDeferredFullHearts: -1,
        mcLastDeferredHasHalf: null,
        mcLastDeferredStartSlots: -1,
        mcLastHealingFullHearts: -1,
        mcLastHealingHasHalf: null,
        mcLastHealingStartSlots: -1,
        mcLastBarrierFullHearts: -1,
        mcLastBarrierHasHalf: null,
        mcLastBarrierLastSlotIsHalf: null,
        dl4dLastTime: -1,
        dl4dTriggeredTimes: {},
        dl4dCaptionToken: 0,
        dl4dCaptionVisible: false
    };

    // ── Publish to QOL namespace ──
    if (typeof QOL !== "undefined") {
        QOL.getCachedPanel = GetCachedPanel;
        QOL.setCachedPanel = SetCachedPanel;
        QOL.clearPanelCache = ClearPanelCache;
        QOL.sweepStalePanelCache = SweepStalePanelCache;
        QOL.resolveCachedPanel = ResolveCachedPanel;
    }

    // ── Publish to global scope ──
    try { if (typeof window !== "undefined") window.State = State; } catch(e) { /* window may not be defined */ }
    try { if (typeof globalThis !== "undefined") globalThis.State = State; } catch(e) { /* globalThis may not be defined */ }

    // ── Self-test ──
    try {
        if (typeof GetCachedPanel !== "function") throw new Error("GetCachedPanel is not a function");
        if (typeof SetCachedPanel !== "function") throw new Error("SetCachedPanel is not a function");
        if (typeof State !== "object" || State === null) throw new Error("State is not an object");
        if (typeof State.cachedPanels !== "object" || State.cachedPanels === null) throw new Error("State.cachedPanels is not an object");
    } catch(e) {
        $.Msg("[QOLLock][ERROR][ql_state] self-test failed: " + (e && e.message ? e.message : String(e)));
    }
})();
