// ui/ql_settings_metadata.js
// =============================================================================
// QOLLOCK — Settings Metadata Tables (PURE DATA)
// =============================================================================
// OWNS:        PERF_IMPACT_TIERS, SETTING_CREATED_BY_BY_CONFIG,
//              SETTING_DESCRIPTION_OVERRIDE_BY_CONFIG, and related metadata tables
// DOES NOT OWN: Settings rendering, config persistence, search, presets
// DEPENDS ON:  core/ql_namespace.js
// USED BY:     ql_settings.js, ql_settings_tooltips.js, ui/renderer.js
// =============================================================================

(() => {
    "use strict";

    const Q = (typeof globalThis !== "undefined" && globalThis.QOL)
        ? globalThis.QOL
        : (typeof QOL !== "undefined" ? QOL : (globalThis.QOL = {}));
    Q.ui = Q.ui || {};

    const PERF_IMPACT_TIER_NONE = "none";
const PERF_IMPACT_TIER_LOW = "low";
const PERF_IMPACT_TIER_MEDIUM = "medium";
const PERF_IMPACT_TIER_HIGH = "high";
const PERF_IMPACT_TIER_ORDER = {
    none: 0,
    low: 1,
    medium: 2,
    high: 3
};
const PERF_IMPACT_LABEL_BY_TIER = {
    none: "None",
    low: "Low",
    medium: "Medium",
    high: "High"
};
const SETTING_CREATED_BY_BY_CONFIG = {
    ENABLE_PASSIVE_COOLDOWN: "Hanturaya",
    OPEN_OLD_ITEM_FILTERS_DOWNLOAD: "Hanturaya",
    ENABLE_CUMULATIVE_DMG: "wouwei",
    ENABLE_CLEAN_DAMAGE_INDICATORS: "Lustie",
    ENABLE_HIDE_TROOPER_DAMAGE: "ninjabladejr",
    ENABLE_DAMAGE_FOUNTAIN: "ArkanoidVFX",
    ENABLE_AMMO_STATUS: "mikoboy",
    ENABLE_RED_DIAMOND: "Hanturaya",
    ENABLE_OBJ_MAP: "bonclide",
    ENABLE_REJUV_HUD: "BreadRollius",
    ENABLE_BUFF_HUD: "BreadRollius",
    ENABLE_URN_DIFF: "BreadRollius, bytenode",
    ENABLE_URN_TIMER: "bytenode",
    ENABLE_MISSING_HERO: "bonclide",
    ENABLE_NICKNAMES: "Predi",
    ENABLE_LEGACY_COOLDOWNS: "Predi",
    ENABLE_UPDATE_CHECKER: "Predi",
    ENABLE_OBJ_DMG: "Waltee",
    ENABLE_SHOP_STATS: "Goblin Man Sam",
    ENABLE_QUICKBUY_CLICK_TO_NOTIFY: "Hanturaya",
    ENABLE_SHOP_ITEM_NOTIFICATIONS: "Hanturaya",
    ENABLE_SHOP_RECENT_PURCHASES: "Hanturaya, bytenode",
    RECENT_PURCHASES_QUICK_MAX: "bytenode",
    RECENT_PURCHASES_QUICK_DISPLAY_SEC: "bytenode",
    RECENT_PURCHASES_QUICK_OPACITY: "bytenode",
    RECENT_PURCHASES_PANEL_OPACITY: "bytenode",
    ENABLE_SHOW_BUILD_ID: "0xluc4s",
    ENABLE_SHOW_BUILD_ID_TITLE: "0xluc4s",
    ENABLE_MINIMALISTIC_PAUSE: "Predi",
    ENABLE_DL4D_REMINDERS: "oGeorge",
    DL4D_VOLUME: "oGeorge",
    ENABLE_DL4D_CAPTIONS: "oGeorge",
    ENABLE_DL4D_SMALL_CAMPS_BOXES: "oGeorge",
    ENABLE_DL4D_RUNE_MELEE_TROOPERS: "oGeorge",
    ENABLE_DL4D_MEDIUM_CAMPS: "oGeorge",
    ENABLE_DL4D_BIG_CAMPS_SINNERS: "oGeorge",
    ENABLE_DL4D_MIDBOSS_URN_GOLD_RUNE: "oGeorge",
    ENABLE_DL4D_LANE_GUARDIAN_WEAK: "oGeorge",
    ENABLE_DL4D_RUNE: "oGeorge",
    ENABLE_DL4D_WALKER_WEAK: "oGeorge",
    ENABLE_DL4D_RUNE_FAST_TROOPERS: "oGeorge",
    ENABLE_DL4D_RUNE_GOLD_BUFFS: "oGeorge",
    ENABLE_DL4D_RUNE_TROOPERS20_HP: "oGeorge",
    SUPPORT_16_10: "Karma",
    SUPPORT_4_3: "Gyzeh",
    ENABLE_COMBAT_INDICATOR: "Goblin Man Sam",
    ENABLE_COLORED_HEALTHBAR: "Hanturaya",
    ENABLE_TOPBAR_ENEMY_HP_WARNING: "Hanturaya",
    ENABLE_TOPBAR_ALLY_HP_WARNING: "Hanturaya",
    HEALTHBAR_TYPE: "bytenode, somarotsaway, EmilyVasquez, Klutzz",
    PLAYER_HEALTHBAR_SCALE: "Civo",
    PLAYER_HEALTHBAR_OPACITY: "Civo",
    PLAYER_HEALTHBAR_X_OFFSET: "Civo",
    PLAYER_HEALTHBAR_Y_OFFSET: "Civo",
    ENABLE_CLEAN_STACKS: "bytenode",
    ZIP_BOOST_SCALE: "BreadRollius",
    ZIP_BOOST_X_OFFSET: "BreadRollius",
    ZIP_BOOST_Y_OFFSET: "BreadRollius",
    UNSECURED_SOUL_TIMER_SCALE: "Hanturaya",
    UNSECURED_SOUL_TIMER_X_OFFSET: "Hanturaya",
    UNSECURED_SOUL_TIMER_Y_OFFSET: "Hanturaya",
    ENABLE_FULL_KEYBOARD_LAYOUT: "Fascilux",
    KEYBOARD_OVERLAY_SCALE: "Fascilux",
    KEYBOARD_OVERLAY_X_OFFSET: "Fascilux",
    KEYBOARD_OVERLAY_Y_OFFSET: "Fascilux",
    MINIMAL_MINIMAP: "Lightbringer",
    ENABLE_MINIMAP_BUFF_TIMER: "BreadRollius",
    ENABLE_MINIMAP_REJUV_TIMER: "BreadRollius",
    ENABLE_MINIMAP_CRATE_OVERLAY: "gfkm",
    ENABLE_MINIMAP_REM_TUNNELS: "oGeorge",
    ENABLE_ALT_ZOOM_REM_TUNNELS: "oGeorge",
    ENABLE_TAB_ZOOM_REM_TUNNELS: "oGeorge",
    ENABLE_MINIMAP_ELEVATION_MARKERS: "Lightbringer",
    ENABLE_ENHANCED_QUICKBUY: "Aminsx",
    ENHANCED_QUICKBUY_COUNT: "Aminsx",
    ENABLE_URN_COLORS: "Civo"
};
const SETTING_CREATED_BY_BY_LABEL = {
};
const SECTION_CREATED_BY_BY_TITLE = {
    "Active Stats": "Predi",
    "Player Stats": "Predi"
};
const SETTING_DESCRIPTION_OVERRIDE_BY_CONFIG = {
    "ALT_ZOOM_DRAW_OVER_UI": "Draws the minimap over all other UI elements for improved visibility.",
    "BRIDGE_BUFF_START": "Time before the announcement happens in seconds.",
    "DISABLE_PLAYER_NAME_BLUR": "The world blur behind player names in the top bar.",
    "DISABLE_QUICK_BUY": "The item buying auto queue system in the shop menu.",
    "ENABLE_ENHANCED_QUICKBUY": "Replaces quickbuy with the Enhanced Quickbuy standalone layout and queue summaries.",
    "ENHANCED_QUICKBUY_COUNT": "Controls how many enhanced quickbuy preview items are shown.",
    "ENABLE_QUICKBUY_CLICK_TO_NOTIFY": "Notify your teammates in chat about how close you are to a quickbuy purchase.",
    "ENABLE_SHOP_ITEM_NOTIFICATIONS": "Shows item buy notifications from recent purchases.",
    "ENABLE_HERO_PURCHASE_POPUPS": "Show purchase notifications under each hero's portrait instead of in the center.",
    "ENABLE_SHOP_RECENT_PURCHASES": "See the recent purchases made in the game.",
    "ENABLE_SHOW_BUILD_ID": "Shows your build information always for content creators",
    "ENABLE_SHOW_BUILD_ID_TITLE": "Append the selected build title after the build ID.",
    "ENABLE_MINIMALISTIC_PAUSE": "Use the compact minimalistic pause screen instead of the default large one.",
    "ENABLE_DL4D_REMINDERS": "Timed audio reminders from Deadlock For Dummies.",
    "DL4D_VOLUME": "Volume for Deadlock For Dummies reminder audio.",
    "ENABLE_DL4D_CAPTIONS": "Show a short caption when Deadlock For Dummies reminders play.",
    "ENABLE_DL4D_SMALL_CAMPS_BOXES": "Remind when small camps, boxes, and statues are spawning.",
    "ENABLE_DL4D_RUNE_MELEE_TROOPERS": "Remind when bridge buffs and melee troopers are spawning.",
    "ENABLE_DL4D_MEDIUM_CAMPS": "Remind when medium camps are spawning.",
    "ENABLE_DL4D_BIG_CAMPS_SINNERS": "Remind when big camps and Sinner's Sacrifice are spawning.",
    "ENABLE_DL4D_MIDBOSS_URN_GOLD_RUNE": "Remind when urn, bridge buffs, and gold statue upgrades are spawning.",
    "ENABLE_DL4D_LANE_GUARDIAN_WEAK": "Remind when lane guardian resistance is reduced.",
    "ENABLE_DL4D_RUNE": "Remind when bridge buffs are spawning.",
    "ENABLE_DL4D_WALKER_WEAK": "Remind when walker resistance is reduced.",
    "ENABLE_DL4D_RUNE_FAST_TROOPERS": "Remind when bridge buffs spawn and troopers speed up.",
    "ENABLE_DL4D_RUNE_GOLD_BUFFS": "Remind when bridge buffs spawn and gold statue buffs are maxed.",
    "ENABLE_DL4D_RUNE_TROOPERS20_HP": "Remind when bridge buffs spawn and troopers improve again.",
    "DISABLE_SHOP_BLUE": "The world background blur effect behind the shop menu.",
    "ENABLE_AMMO_STATUS": "Visual indicator of your current ammo.",
    "ENABLE_BUFF_HUD": "Shows a visual indicator in the top bar of when Bridge Buffs will spawn.",
    "ENABLE_CENTER_ESC": "Centers ESC menu elements to make them easier to access.",
    "ENABLE_CENTER_FRIENDS_LIST": "Centers friends list area in ESC menu.",
    "ENABLE_LEGACY_COOLDOWNS": "Restores the legacy removed duration bars for abilities.",
    "ENABLE_STATLOCKER": "Adds a STAT button on profile rows that opens Statlocker for that account.",
    "ENABLE_CLEAN_STACKS": "Improve Ability Stacks",
    "ENABLE_COMBAT_INDICATOR": "Highlight regeneration in red for when in combat.",
    "ENABLE_COLORED_HEALTHBAR": "Colored healthbar warnings when at significant thresholds.",
    "ENABLE_TOPBAR_ENEMY_HP_WARNING": "Colored enemy top-bar health warnings when at significant thresholds.",
    "ENABLE_TOPBAR_ALLY_HP_WARNING": "Colored ally top-bar health warnings when at significant thresholds.",
    "ENABLE_COMPASS_SPEED": "Speed number tracker.",
    "ENABLE_CUMULATIVE_DMG": "The large cumulative damage number.",
    "ENABLE_CLEAN_DAMAGE_INDICATORS": "Modify damage numbers for a cleaner style and animation to be more out of the way",
    "ENABLE_DAMAGE_FOUNTAIN": "Ragnarok Online damage visuals with improved fancy styling.",
    "ENABLE_DAMAGE_IMPACT": "The popups that appear when getting a kill or CCing an enemy or healing an ally",
    "ENABLE_FORCE_TESTING_TOOLS": "Forcibly shows testing tools at all times.",
    "ENABLE_FULL_KEYBOARD_LAYOUT": "Shows all of your keybinds.",
    "ENABLE_HERO_SCENE_PANEL": "Shows your character in the shop menu.",
    "ENABLE_HIDE_ABILITY_SUGGESTION": "Highlighted abilities showing you what you should upgrade depending on build.",
    "ENABLE_HIDE_AMMO_ALL": "Current ammo inside of your magazine.",
    "ENABLE_HIDE_BEHAVIOR_SUMMARY": "Menu when you receive a punishment for breaking game rules.",
    "ENABLE_HIDE_COSMETIC_ABILITY": "The cosmetic ability on your default 5 key, like posters and snowballs.",
    "ENABLE_HIDE_FAILED_HINT": "The popup signifying you are too low on stamina to cast another movement input.",
    "ENABLE_HIDE_MAGAZINE": "Total ammo amount.",
    "ENABLE_HIDE_RELOAD_CIRCLE": "The circle countdown for when you are reloading.",
    "ENABLE_HIDE_RELOAD_ICON": "The icon that replaces your crosshair when reloading.",
    "ENABLE_HIDE_SMALL_NUMBERS": "The small incremental damage numbers.",
    "ENABLE_HIDE_TESTING_TOOLS": "Forcibly hides testing tools at all times.",
    "ENABLE_HIDE_TROOPER_DAMAGE": "The damage dealt to Trooper minions.",
    "ENABLE_HUD_SHIFT": "Slight adjustments to the HUD for better streaming output.",
    "ENABLE_LANE_WITH_PARTY": "Automatically selects Lane Preference: With Party for matchmaking.",
    "ENABLE_MINIMAP_BUFF_TIMER": "Shows a visual indicator in the minimap of when Bridge Buffs will spawn.",
    "ENABLE_MINIMAP_BUFF_TIMER_ON_BRIDGE": "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.",
    "ENABLE_MINIMAP_REJUV_TIMER": "Shows a visual indicator in the minimap of when Mid Boss will spawn.",
    "ENABLE_MINIMAP_CRATE_OVERLAY": "Shows Midtown crate markers in the minimap.",
    "ENABLE_MINIMAP_REM_TUNNELS": "Show an overlay of the underground tunnels.",
    "MINIMAP_REM_TUNNELS_OPACITY": "Opacity of the underground tunnel overlay.",
    "ENABLE_ALT_ZOOM_REM_TUNNELS": "Show the underground tunnel overlay while Alt Zoom is active.",
    "ALT_ZOOM_REM_TUNNELS_OPACITY": "Opacity of the underground tunnel overlay while Alt Zoom is active.",
    "ENABLE_TAB_ZOOM_REM_TUNNELS": "Show the underground tunnel overlay while Tab Zoom is active.",
    "TAB_ZOOM_REM_TUNNELS_OPACITY": "Opacity of the underground tunnel overlay while Tab Zoom is active.",
    "ENABLE_MINIMAP_ELEVATION_MARKERS": "Shows relative elevation difference between you and players.",
    "MINIMAP_ICON_COLOR": "Choose a preset color wash for minimap icons.",
    "MINIMAP_FIXED_ICON_SIZE": "Resizes the minimap using width and height instead of scaling the whole HUD. Applies to Base, Alt and Tab views.",
    "ENABLE_MINIMAP_ALWAYS_ON_MID_BOSS": "Moves the Mid Boss timer onto the bridge area of the minimap.",
    "ENABLE_MISSING_HERO": "Greys out heros in the top bar when missing on the map.",
    "ENABLE_NICKNAMES": "Shows nicknames of all players in the game within the top bar.",
    "ENABLE_OBJ_DMG": "Shows the individual player's objective damage in the top bar.",
    "ENABLE_OBJ_MAP": "Show a visual indicator in the top bar of the current Guardians, Walkers, and Base.",
    "ENABLE_OLD_ITEM_COOLDOWNS": "This is a lightweight version with significant FPS improvements but requires a seperate file for filters.",
    "ENABLE_RED_DIAMOND": "Significantly improve visibility of target reticle and highlight for execute ranges (Shiv).",
    "ENABLE_REJUV_HUD": "Shows a visual indicator in the top bar of when Mid Boss will spawn.",
    "ENABLE_SHOP_STATS": "Shows all of your player stats within the shop menu.",
    "ENABLE_SIMPLIFY_SHOP_STATS": "Cleans up the visuals of the shop stats display without changing the rest of the shop.",
    "ENABLE_SIMPLIFY_ABILITY_ICONS": "Cleans up visuals of abilities significantly to reduce clutter.",
    "ENABLE_SIMPLIFY_COMPASS": "Simplifies the Compass overlay to its bare elements.",
    "ENABLE_SIMPLIFY_ITEMS": "Cleans up visuals of the item bar significantly to reduce clutter.",
    "ENABLE_SIMPLIFY_SHOP": "Cleans up visuals of the shop menu significantly to reduce clutter.",
    "ENABLE_URN_DIFF": "Shows a visual indicator in the top bar of the percentage difference of souls between teams.",
    "ENABLE_URN_TIMER": "Shows a countdown timer in the top bar for the next urn spawn or relocation.",
    "ENABLE_URN_COLORS": "Changes urn color to know which side is favored, green for your team, red for the enemy.",
    "ENABLE_ENEMY_V2_ENHANCED": "Enhanced V2 enemy healthbar visuals and readability.",
    "ENABLE_ENEMY_V2_ULT_INDICATOR": "Show the UnitInfo panel on V2 enemy healthbars.",
    "ENABLE_ENEMY_V2_LEVEL": "Show level text on V2 enemy healthbars.",
    "HEALTHBAR_TYPE": "Customized healthbars for better visibility or flair.",
    "ENABLE_MINECRAFT_HEALTH_NUMBERS": "Show current / max HP numbers over the Minecraft hearts.",
    "PLAYER_HEALTHBAR_SCALE": "Adjust size of the player healthbar.",
    "PLAYER_HEALTHBAR_OPACITY": "Adjust opacity of the player healthbar.",
    "PLAYER_HEALTHBAR_X_OFFSET": "Adjust horizontal position of the player healthbar.",
    "PLAYER_HEALTHBAR_Y_OFFSET": "Adjust vertical position of the player healthbar.",
    "PLAYER_HEALTHBAR_ACCENT_COLOR": "Choose a preset accent color for the player healthbar frame.",
    "BOTTOM_BAR_WASH_COLOR": "Choose a preset color wash for the bottom ability bar.",
    "KEYBOARD_OVERLAY_WASH_COLOR": "Choose a preset color wash for the keyboard overlay.",
    "STAMINA_CHARGE_COLOR": "Choose a preset border color for stamina charge indicators.",
    "STAMINA_CHARGE_ANGLE": "Rotate the stamina charge indicator.",
    "AMMO_CLIP_ANGLE": "Rotate the ammo magazine visualiser.",
    "AMMO_TEXT_COLOR": "Choose a preset text color for the ammo display.",
    "CHAT_SCALE": "Adjust size of the in-game chat.",
    "CHAT_X_OFFSET": "Adjust horizontal position of the in-game chat.",
    "CHAT_Y_OFFSET": "Adjust vertical position of the in-game chat.",
    "ENABLE_CHAT": "Show the in-game chat panel.",
    "ENABLE_IMAGES_IN_CHAT": "Render image URLs as images.",
    "HITMARKERS_RUNTIME": "Toggle the hitmarkers when attacking enemies.",
    "MINIMAL_MINIMAP": "Cleans up visuals of the minimap significantly to reduce clutter.",
    "MINIMAP_FLIP": "Rotates the static minimap 180 degrees.",
    "MINIMAP_REMINDER_INTERVAL": "The interval in which the sound plays in seconds.",
    "MINIMAP_ROTATE_WITH_PLAYER": "Makes the minimap rotate with player view, this is just for fun.",
    "OPEN_OLD_ITEM_FILTERS_DOWNLOAD": "Only download the filter file of the filter you want, nothing else.",
    "PREVIEWS_ENABLED": "Realtime Changes",
    "ENABLE_UPDATE_CHECKER": "Check for new QOLLOCK releases when opening settings.",
    "SETTINGS_THEME": "Changes the visual theme used by the settings menu, modals, loader, and save menus.",
    "RUNTIME_MINIMAP_CLICK_RADIUS": "The click hitbox of your pings or clicks, this can help make pings more accurate.",
    "RUNTIME_MINIMAP_HERO_ICON_SIZE": "The size of other players on the minimap.",
    "RUNTIME_MINIMAP_ICON_SHRINK": "How much icons will shrink when overlapping with others.",
    "RUNTIME_MINIMAP_PLAYER_ICON_SIZE": "The size of yourself on the minimap.",
    "RUNTIME_MINIMAP_REFRESH_RATE": "How fast the minimap refreshes.",
    "RUNTIME_MINIMAP_SHRINK_DISTANCE": "The distance threshold in which icons will start shrinking. Lower is more accurate positions, higher is easier visibility.",
    "RUNTIME_MINIMAP_ZIP_THICKNESS": "The thickness of the Zipline lines across the map.",
    "RUNTIME_STATS_SHOWFPS": "Shows raw FPS count.",
    "RUNTIME_STATS_SHOWFRAME": "Shows current frame count, mostly useless.",
    "RUNTIME_STATS_SHOWMEM": "RAM and GPU Memory real time usage statistics.",
    "RUNTIME_STATS_SHOWPOS": "Position and Velocity real time statistics.",
    "RUNTIME_STATS_SHOWTICK": "Shows real time tick information, mostly useless.",
    "SUPPORT_16_10": "Shifts the HUD for better visual support for 16:10 resolutions.",
    "SUPPORT_4_3": "Shifts the HUD for better visual support for 4:3 resolutions.",
    "TAB_ZOOM_DRAW_OVER_UI": "Draws the minimap over all other UI elements for improved visibility.",
};
const SETTING_DESCRIPTION_OVERRIDE_BY_CATEGORY_ROW = {
    "Audio / Announcer|Voice": "You can download custom announcer packs, just download the correct one for the slot you want to replace.",
    "Audio / Announcer|Type": "Which events cause a sound to play. Camps are one time, Buff is every 5 minutes.",
    "Audio / Announcer|Buff Filter": "Choose which bridge buff sound variants can play.",
    "Audio / Announcer|Buff Delay": "Time before the announcement happens in seconds.",
    "Audio / Minimap Reminder|Timer": "The interval in which the sound plays in seconds.",
    "Audio|Announcer": "You can download custom announcer packs, just download the correct one for the slot you want to replace.",
    "Audio|Minimap Reminder": "Play an audio reminder to remember to look at the minimap.",
    "Config / Meta Settings|Preview": "Preview realtime changes to settings when modifying them.",
    "Config / Meta Settings|Update Checker": "Check for new QOLLOCK releases when opening settings.",
    "Config / Meta Settings|Language": "The displayed language of the settings menu.",
    "Config / Meta Settings|Default Hero": "The hero you automatically switch to on launch or after saving..",
    "Config / Meta Settings|Theme": "Retheme the settings menu, modals, loader, and save menus with a shared aesthetic.",
    "Console / General|Hitmarkers": "Toggle the hitmarkers when attacking enemies.",
    "Console / Minimap|Click Radius": "The click hitbox of your pings or clicks, this can help make pings more accurate.",
    "Console / Minimap|Hero Icon Size": "The size of other players on the minimap.",
    "Console / Minimap|Icon Shrink": "How much icons will shrink when overlapping with others.",
    "Console / Minimap|Player Icon Size": "The size of yourself on the minimap.",
    "Console / Minimap|Refresh Rate": "How fast the minimap refreshes.",
    "Console / Minimap|Shrink Distance": "The distance threshold in which icons will start shrinking. Lower is more accurate positions, higher is easier visibility.",
    "Console / Minimap|Zip Thickness": "The thickness of the Zipline lines across the map.",
    "Console / Statistics|Show FPS": "Shows raw FPS count.",
    "Console / Statistics|Show Frame": "Shows current frame count, mostly useless.",
    "Console / Statistics|Show Memory": "RAM and GPU Memory real time usage statistics.",
    "Console / Statistics|Show Position": "Position and Velocity real time statistics.",
    "Console / Statistics|Show Tick": "Shows real time tick information, mostly useless.",
    "Crosshair / Ammo|Current": "Current ammo inside of your magazine.",
    "Crosshair / Ammo|Current Size": "Size of your current ammo.",
    "Crosshair / Ammo|Total": "Total ammo amount.",
    "Crosshair / Ammo|Total Size": "Size of your total ammo.",
    "Crosshair / Ammo|Visual": "Visual indicator of your current ammo.",
    "Crosshair / Damage Numbers|Big Numbers": "The large cumulative damage number.",
    "Crosshair / Damage Numbers|Damage Fountain": "Ragnarok Online damage visuals with improved fancy styling.",
    "Crosshair / Damage Numbers|Small Numbers": "The small incremental damage numbers.",
    "Crosshair / Damage Numbers|Trooper Damage": "The damage dealt to Trooper minions.",
    "Crosshair / Item Cooldowns|Optimize Filters": "Only download the filter file of the filter you want, nothing else.",
    "Crosshair / Item Cooldowns|Advanced Mode": "Switch to the advanced item cooldown mode with in-menu filters.",
    "Crosshair / Item Cooldowns|Advanced Filter": "Decide what style of item to display the cooldown of.",
    "Crosshair / Active Stats|Show Debuffs": "Show negative modifiers (slow, antiheal, fire rate reduction...) next to the crosshair.",
    "Crosshair / Active Stats|Show Buffs": "Show positive modifiers (resistances, fire rate, lifesteal...) next to the crosshair.",
    "UI / Player Stats|Side": "Pin the stats panel to the left (default, like vanilla) or right side of the screen.",
    "HUD|Player Stats": "Customize the position of the Player Stats panel, or hide it completely.",
    "Crosshair / Item Target Reticle|Highlight Mode": "Significantly improve visibility of target reticle and highlight for execute ranges (Shiv).",
    "Crosshair / Item Target Reticle|Improved Hint": "Cleans up the styling of reticle hints.",
    "Crosshair / Reloading|Circle": "The circle countdown for when you are reloading.",
    "Crosshair / Reloading|Icon": "The icon that replaces your crosshair when reloading.",
    "Crosshair|Active Stats": "Mirror active buffs/debuffs vertically next to the crosshair so they are visible mid-fight.",
    "Crosshair|Combat Status": "Show if you are in combat or not.",
    "Crosshair|Damage Numbers": "Customize the styling of damage numbers.",
    "Crosshair|Item Cooldowns": "Shows item cooldowns near crosshair for easier readability.",
    "Crosshair|Item Target Reticle": "Customize visibility of target reticle when abilities or items visually show on allies and enemies.",
    "Crosshair|Reload Cooldown": "View a cooldown timer for reloading time.",
    "HUD / Bottom Bar|Ability Suggestion": "Highlighted abilities showing you what you should upgrade depending on build.",
    "HUD / Bottom Bar|Cosmetic Ability": "The cosmetic ability on your default 5 key, like posters and snowballs.",
    "HUD / Bottom Bar|Failed Hint": "The popup signifying you are too low on stamina to cast another movement input.",
    "HUD / Bottom Bar|Minimalist Abilities": "Cleans up visuals of abilities significantly to reduce clutter.",
    "HUD / Bottom Bar|Clean Stacks": "Move ability stacks to bottom-center of ability icon.",
    "HUD / Bottom Bar|Minimalist Item Bar": "Cleans up visuals of the item bar significantly to reduce clutter.",
    "HUD / HUD Controls|16:10 Support": "Shifts the HUD for better visual support for 16:10 resolutions.",
    "HUD / HUD Controls|21:9 Stream Fix": "Slight adjustments to the HUD for better streaming output.",
    "HUD / HUD Controls|4:3 Support": "Shifts the HUD for better visual support for 4:3 resolutions.",
    "HUD / HUD Controls|Behavior Summary": "Menu when you receive a punishment for breaking game rules.",
    "HUD / HUD Controls|Centered ESC Menu": "Centers ESC menu elements to make them easier to access.",
    "HUD / HUD Controls|Statlocker": "Adds a STAT button on profile rows that opens Statlocker for that account.",
    "HUD / HUD Controls|Hide Testing Tools": "Forcibly hides testing tools at all times.",
    "HUD / HUD Controls|Lane with Party": "Automatically selects Lane Preference: With Party for matchmaking.",
    "HUD / HUD Controls|Show Testing Tools": "Forcibly shows testing tools at all times.",
    "UI / UI Controls|16:10 Support": "Shifts the HUD for better visual support for 16:10 resolutions.",
    "UI / UI Controls|21:9 Stream Fix": "Slight adjustments to the HUD for better streaming output.",
    "UI / UI Controls|4:3 Support": "Shifts the HUD for better visual support for 4:3 resolutions.",
    "UI / UI Controls|Behavior Summary": "Menu when you receive a punishment for breaking game rules.",
    "UI / UI Controls|Centered ESC Menu": "Centers ESC menu elements to make them easier to access.",
    "UI / UI Controls|Centered Friends List": "Centers the friends list area within the ESC menu.",
    "UI / UI Controls|Statlocker": "Adds a STAT button on profile rows that opens Statlocker for that account.",
    "UI / UI Controls|Hide Testing Tools": "Forcibly hides testing tools at all times.",
    "UI / UI Controls|Lane with Party": "Automatically selects Lane Preference: With Party for matchmaking.",
    "UI / UI Controls|Show Testing Tools": "Forcibly shows testing tools at all times.",
    "UI / UI Controls|Show Build ID": "Shows your build information always for content creators",
    "UI / UI Controls / Show Build ID|Show Title": "Append the selected build title after the build ID.",
    "UI / UI Controls|Minimalistic Pause": "Use the compact minimalistic pause screen instead of the default large one.",
    "HUD|Chat": "Adjust the in-game chat position and scale.",
    "UI|Chat": "Adjust the in-game chat position and scale.",
    "HUD / Shop|Blur": "The world background blur effect behind the shop menu.",
    "HUD / Shop|Hero": "Shows your character in the shop menu.",
    "HUD / Shop|Minimalist": "Cleans up visuals of the shop menu significantly to reduce clutter.",
    "HUD / Shop|Quick Buy": "The item buying auto queue system in the shop menu.",
    "HUD / Shop|Recent Purchases": "Tools for tracking recent item purchases.",
    "HUD / Shop|Item Buy Notifications": "Tools for showing and sharing item purchase notifications.",
    "HUD / Shop|Stats": "Shows all of your player stats within the shop menu.",
    "HUD / Top Bar|Bridge Buff Timer": "Shows a visual indicator in the top bar of when Bridge Buffs will spawn.",
    "HUD / Top Bar|Mid Boss Timer": "Shows a visual indicator in the top bar of when Mid Boss will spawn.",
    "HUD / Top Bar|Missing Hero Opaque": "Greys out heros in the top bar when missing on the map.",
    "HUD / Top Bar|Nicknames": "Shows nicknames of all players in the game within the top bar.",
    "HUD / Top Bar|Objective Damage": "Shows the individual player's objective damage in the top bar.",
    "HUD / Top Bar|Objective Map": "Show a visual indicator in the top bar of the current Guardians, Walkers, and Base.",
    "HUD / Top Bar|Top Bar Background": "The world blur and backing strip behind player names in the top bar.",
    "HUD / Top Bar|Enemy HP Warning": "Colored enemy top-bar health warnings when at significant thresholds.",
    "HUD / Top Bar|Ally HP Warning": "Colored ally top-bar health warnings when at significant thresholds.",
    "HUD / Top Bar|Urn Difference": "Shows a visual indicator in the top bar of the percentage difference of souls between teams.",
    "HUD|Damage Report": "Customize the visuals of the incoming damage panel.",
    "Healthbar / Player|Color Warning": "Colored healthbar warnings when at significant thresholds.",
    "Healthbar / Player|Type": "Customized healthbars for better visibility or flair.",
    "Healthbar / Player|Horizontal Offset": "Adjust horizontal position of the player healthbar.",
    "Healthbar / Player|Vertical Offset": "Adjust vertical position of the player healthbar.",
    "Healthbar / Enemy|Colored Health": "Colored enemy healthbar warnings when at significant thresholds.",
    "Healthbar / Enemy|Ult Indicator": "Show the ultimate indicator for V1 healthbars.",
    "Healthbar / Enemy V2|Enhanced": "Enhanced V2 enemy healthbar visuals and readability.",
    "Healthbar / Enemy V2|Ult Indicator": "Show the UnitInfo panel on V2 enemy healthbars.",
    "Healthbar / Enemy V2|Level": "Show level text on V2 enemy healthbars.",
    "Healthbar|Enemy": "Enemy healthbar enhancements.",
    "Healthbar|Enemy V2": "V2 enemy healthbar enhancements.",
    "Minimap / Alt Zoom|Draw Over UI": "Draws the minimap over all other UI elements for improved visibility.",
    "Minimap / Minimap|Bridge Buff Timer": "Shows a visual indicator in the minimap of when Bridge Buffs will spawn.",
    "Minimap / Minimap / Bridge Buff Timer|On Bridge": "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.",
    "Minimap / Minimap|Flip": "Rotates the static minimap 180 degrees.",
    "Minimap / Minimap|Mid Boss Timer": "Shows a visual indicator in the minimap of when Mid Boss will spawn.",
    "Minimap / Minimap / Mid Boss Timer|On Mid Boss": "Moves the Mid Boss timer onto the bridge area of the minimap.",
    "Minimap / Addons / Mid Boss Timer|On Mid Boss": "Moves the Mid Boss timer onto the bridge area of the minimap.",
    "Minimap / Addons / Bridge Buff Timer|On Bridge": "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.",
    "Minimap / Minimap|Minimalist": "Cleans up visuals of the minimap significantly to reduce clutter.",
    "Minimap / Minimap|Minimalist Opacity": "Opacity of the background of Minimalist Minimap.",
    "Minimap / Minimap|Spinny Mode": "Makes the minimap rotate with player view, this is just for fun.",
    "Minimap / Minimap|Urn Colors": "Changes urn color to know which side is favored, green for your team, red for the enemy.",
    "Minimap / Tab Zoom|Draw Over UI": "Draws the minimap over all other UI elements for improved visibility.",
    "Minimap|Alt Zoom": "View an enhanced minimap on opening ability menu.",
    "Minimap|Tab Zoom": "View an enhanced minimap on opening scoreboard menu.",
    "Overlay / Compass|Minimalist": "Simplifies the Compass overlay to its bare elements.",
    "Overlay / Compass|Speed": "Speed number tracker.",
    "Overlay / Compass|Horizontal Stretch": "Stretch the compass horizontally.",
    "Overlay / Compass|Vertical Stretch": "Stretch the compass vertically.",
    "Overlay / Keyboard|Full Keys": "Shows all of your keybinds.",
    "Overlay|Compass": "See your view angle and speed.",
    "Overlay|Keyboard": "Real time key input visual.",
    "Overlay|Ult Cooldowns": "View the cooldown time of player ultimates.",
    "Overlay|Unsecured Plus": "Customize unsecured souls visuals.",
    "Overlay / Unsecured Plus|Icon": "The small visual icon.",
    "Overlay / Unsecured Plus|Text": "The unsecured text.",
    "Overlay|Unsecured Timer": "Show the estimated time for unsecured souls to dissapear.",
    "Overlay|Zipline Boost": "An always visible zipline boost overlay.",
};
const SECTION_DESCRIPTION_OVERRIDE_BY_TAB_TITLE = {
    "Audio|Announcer": "You can download custom announcer packs, just download the correct one for the slot you want to replace.",
    "Audio|Minimap Reminder": "Play an audio reminder to remember to look at the minimap.",
    "Crosshair|Active Stats": "Mirror active buffs/debuffs vertically next to the crosshair so they are visible mid-fight.",
    "UI|Player Stats": "Customize the position of the Player Stats panel, or hide it completely.",
    "Crosshair|Combat Status": "Show if you are in combat or not.",
    "Crosshair|Damage Numbers": "Customize the styling of damage numbers.",
    "Crosshair|Item Cooldowns": "Shows item cooldowns near crosshair for easier readability.",
    "Crosshair|Item Target Reticle": "Customize visibility of target reticle when abilities or items visually show on allies and enemies.",
    "Crosshair|Reload Cooldown": "View a cooldown timer for reloading time.",
    "HUD|Damage Report": "Customize the visuals of the incoming damage panel.",
    "UI|Damage Report": "Customize the visuals of the incoming damage panel.",
    "Healthbar|Enemy": "Enemy healthbar enhancements.",
    "Healthbar|Enemy V2": "V2 enemy healthbar enhancements.",
    "Minimap|Alt Zoom": "View an enhanced minimap on opening ability menu.",
    "Minimap|Tab Zoom": "View an enhanced minimap on opening scoreboard menu.",
    "Overlay|Compass & Speed": "See your view angle and speed.",
    "Overlay|Keyboard": "Real time key input visual.",
    "Overlay|Ult Cooldowns": "View the cooldown time of player ultimates.",
    "Overlay|Unsecured Plus": "Customize unsecured souls visuals.",
    "Overlay|Unsecured Timer": "Show the estimated time for unsecured souls to dissapear.",
    "Overlay|Zipline Boost": "An always visible zipline boost overlay.",
};
const SETTING_PERF_IMPACT_TIERS = {
    ALT_ZOOM_DRAW_OVER_UI: "low",
    ALT_ZOOM_OPACITY: "none",
    AMMO_CURRENT_SCALE: "none",
    AMMO_PANEL_X_OFFSET: "none",
    AMMO_PANEL_Y_OFFSET: "none",
    AMMO_TOTAL_SCALE: "none",
    BRIDGE_BUFF_START: "none",
    COMBAT_STATUS_SCALE: "none",
    COMBAT_STATUS_X_OFFSET: "none",
    COMBAT_STATUS_Y_OFFSET: "none",
    COMPASS_SCALE: "none",
    COMPASS_STRETCH_X: "low",
    COMPASS_STRETCH_Y: "low",
    COMPASS_X_OFFSET: "none",
    COMPASS_Y_OFFSET: "none",
    DAMAGE_NUMBER_OPACITY: "none",
    DAMAGE_IMPACT_OPACITY: "none",
    DAMAGE_IMPACT_SCALE: "none",
    DAMAGE_IMPACT_X_OFFSET: "none",
    DAMAGE_IMPACT_Y_OFFSET: "none",
    DAMAGE_REPORT_X_OFFSET: "none",
    DAMAGE_REPORT_Y_OFFSET: "none",
    DEFAULT_HERO: "none",
    DISABLE_DAMAGE_REPORT: "low",
    ENABLE_DAMAGE_IMPACT: "low",
    DISABLE_PLAYER_NAME_BLUR: "none",
    DISABLE_QUICK_BUY: "none",
    DISABLE_SHOP_BLUE: "none",
    ENABLE_ALT_ZOOM: "low",
    ENABLE_AMMO_STATUS: "low",
    ENABLE_CROSSHAIR_STATS: "medium",
    CROSSHAIR_STATS_SHOW_DEBUFFS: "medium",
    CROSSHAIR_STATS_SHOW_BUFFS: "medium",
    CROSSHAIR_STATS_X_OFFSET: "none",
    CROSSHAIR_STATS_Y_OFFSET: "none",
    CROSSHAIR_STATS_SCALE: "none",
    CROSSHAIR_STATS_OPACITY: "none",
    CROSSHAIR_STATS_SHOW_FIRERATE: "none",
    CROSSHAIR_STATS_SHOW_MOVESPEED: "none",
    CROSSHAIR_STATS_SHOW_HEALAMP: "none",
    CROSSHAIR_STATS_SHOW_BULLETRESIST: "none",
    CROSSHAIR_STATS_SHOW_TECHRESIST: "none",
    CROSSHAIR_STATS_SHOW_BULLETLIFESTEAL: "none",
    CROSSHAIR_STATS_SHOW_TECHLIFESTEAL: "none",
    CROSSHAIR_STATS_SHOW_WEAPONPOWER: "none",
    CROSSHAIR_STATS_SHOW_SPIRIT: "none",
    CROSSHAIR_STATS_SHOW_RANGE: "none",
    CROSSHAIR_STATS_SHOW_DURATION: "none",
    CROSSHAIR_STATS_SHOW_DAMAGEAMP: "none",
    CROSSHAIR_STATS_SHOW_CLIPSIZE: "none",
    CROSSHAIR_STATS_SHOW_REGEN: "none",
    CROSSHAIR_STATS_SHOW_BULLETEVASION: "none",
    ENABLE_STATS_POSITION: "low",
    STATS_POSITION_SIDE: "none",
    STATS_POSITION_X_OFFSET: "none",
    STATS_POSITION_Y_OFFSET: "none",
    STATS_POSITION_HIDE_NORMAL: "none",
    STATS_POSITION_HIDE_SCOREBOARD: "none",
    ENABLE_BETTER_UNSECURED: "low",
    ENABLE_BETTER_UNSECURED_SHOW_ICON: "low",
    ENABLE_BETTER_UNSECURED_SHOW_TEXT: "low",
    ENABLE_BUFF_HUD: "low",
    ENABLE_CENTER_ESC: "none",
    ENABLE_CENTER_FRIENDS_LIST: "none",
    ENABLE_LEGACY_COOLDOWNS: "low",
    ENABLE_STATLOCKER: "low",
    ENABLE_CLEAN_STACKS: "none",
    ENABLE_COMBAT_INDICATOR: "low",
    ENABLE_COLORED_HEALTHBAR: "medium",
    ENABLE_COLOR_WARNING_25: "medium",
    ENABLE_COLOR_WARNING_65: "medium",
    ENABLE_COLOR_WARNING_75: "medium",
    ENABLE_COMBAT_STATUS: "low",
    ENABLE_COMPASS: "medium",
    ENABLE_COMPASS_SPEED: "medium",
    ENABLE_CUMULATIVE_DMG: "low",
    ENABLE_CLEAN_DAMAGE_INDICATORS: "low",
    ENABLE_DAMAGE_FOUNTAIN: "low",
    ENABLE_TOPBAR_ENEMY_HP_WARNING: "medium",
    ENABLE_TOPBAR_ENEMY_HP_WARNING_25: "medium",
    ENABLE_TOPBAR_ENEMY_HP_WARNING_65: "medium",
    ENABLE_TOPBAR_ENEMY_HP_WARNING_75: "medium",
    ENABLE_TOPBAR_ALLY_HP_WARNING: "medium",
    ENABLE_TOPBAR_ALLY_HP_WARNING_25: "medium",
    ENABLE_TOPBAR_ALLY_HP_WARNING_65: "medium",
    ENABLE_TOPBAR_ALLY_HP_WARNING_75: "medium",
    ENABLE_ENEMY_V2_ENHANCED: "low",
    ENABLE_ENEMY_V2_ULT_INDICATOR: "low",
    ENABLE_ENEMY_V2_LEVEL: "low",
    ENABLE_ENEMY_ULT_INDICATOR: "low",
    ENABLE_ENHANCED_QUICKBUY: "low",
    ENHANCED_QUICKBUY_COUNT: "none",
    ENABLE_FORCE_TESTING_TOOLS: "none",
    ENABLE_FULL_KEYBOARD_LAYOUT: "low",
    ENABLE_HERO_SCENE_PANEL: "low",
    ENABLE_HIDE_ABILITY_SUGGESTION: "none",
    ENABLE_HIDE_AMMO_ALL: "none",
    ENABLE_HIDE_BEHAVIOR_SUMMARY: "none",
    ENABLE_HIDE_COSMETIC_ABILITY: "none",
    ENABLE_HIDE_FAILED_HINT: "none",
    ENABLE_HIDE_MAGAZINE: "none",
    ENABLE_HIDE_RELOAD_CIRCLE: "none",
    ENABLE_HIDE_RELOAD_ICON: "none",
    ENABLE_HIDE_SMALL_NUMBERS: "none",
    ENABLE_HIDE_TESTING_TOOLS: "none",
    ENABLE_HIDE_TROOPER_DAMAGE: "none",
    ENABLE_GAME_AUDIO: "low",
    ENABLE_HUD_SHIFT: "low",
    ENABLE_IMPROVED_HINT: "low",
    ENABLE_INTERVAL: "none",
    ENABLE_KEYBOARD_OVERLAY: "low",
    ENABLE_LANE_WITH_PARTY: "low",
    ENABLE_MINIMAP_BUFF_TIMER: "low",
    ENABLE_MINIMAP_REJUV_TIMER: "low",
    ENABLE_MINIMAP_CRATE_OVERLAY: "low",
    ENABLE_MINIMAP_REM_TUNNELS: "low",
    MINIMAP_REM_TUNNELS_OPACITY: "none",
    ENABLE_ALT_ZOOM_REM_TUNNELS: "low",
    ALT_ZOOM_REM_TUNNELS_OPACITY: "none",
    ENABLE_TAB_ZOOM_REM_TUNNELS: "low",
    TAB_ZOOM_REM_TUNNELS_OPACITY: "none",
    ENABLE_MINIMAP_ELEVATION_MARKERS: "low",
    MINIMAP_ICON_COLOR: "none",
    MINIMAP_FIXED_ICON_SIZE: "none",
    ENABLE_MINIMAP_ALWAYS_ON_MID_BOSS: "low",
    ENABLE_MINIMAP_REMINDER: "low",
    ENABLE_MISSING_HERO: "low",
    ENABLE_NICKNAMES: "none",
    ENABLE_OBJ_DMG: "low",
    ENABLE_OBJ_MAP: "low",
    ENABLE_OLD_ITEM_COOLDOWNS: "low",
    ENABLE_ONE_TIME_TIER1: "low",
    ENABLE_ONE_TIME_TIER2: "low",
    ENABLE_ONE_TIME_TIER3: "low",
    ENABLE_PASSIVE_COOLDOWN: "low",
    ENABLE_RED_DIAMOND: "none",
    ENABLE_REJUV_HUD: "low",
    ENABLE_RELOAD_COOLDOWN: "low",
    ENABLE_SHOP_STATS: "low",
    ENABLE_QUICKBUY_CLICK_TO_NOTIFY: "low",
    ENABLE_SHOP_ITEM_NOTIFICATIONS: "low",
    ENABLE_HERO_PURCHASE_POPUPS: "low",
    ENABLE_SHOP_RECENT_PURCHASES: "low",
    RECENT_PURCHASES_QUICK_OPACITY: "none",
    RECENT_PURCHASES_PANEL_OPACITY: "none",
    ENABLE_SHOW_BUILD_ID: "low",
    ENABLE_SHOW_BUILD_ID_TITLE: "low",
    ENABLE_MINIMALISTIC_PAUSE: "low",
    ENABLE_DL4D_REMINDERS: "low",
    DL4D_VOLUME: "none",
    ENABLE_DL4D_CAPTIONS: "low",
    ENABLE_DL4D_SMALL_CAMPS_BOXES: "low",
    ENABLE_DL4D_RUNE_MELEE_TROOPERS: "low",
    ENABLE_DL4D_MEDIUM_CAMPS: "low",
    ENABLE_DL4D_BIG_CAMPS_SINNERS: "low",
    ENABLE_DL4D_MIDBOSS_URN_GOLD_RUNE: "low",
    ENABLE_DL4D_LANE_GUARDIAN_WEAK: "low",
    ENABLE_DL4D_RUNE: "low",
    ENABLE_DL4D_WALKER_WEAK: "low",
    ENABLE_DL4D_RUNE_FAST_TROOPERS: "low",
    ENABLE_DL4D_RUNE_GOLD_BUFFS: "low",
    ENABLE_DL4D_RUNE_TROOPERS20_HP: "low",
    ENABLE_SIMPLIFY_SHOP_STATS: "none",
    ENABLE_SIMPLIFY_ABILITY_ICONS: "none",
    ENABLE_SIMPLIFY_COMPASS: "none",
    ENABLE_SIMPLIFY_ITEMS: "none",
    ENABLE_SIMPLIFY_SHOP: "none",
    HUD_BOTTOM_BAR_ENABLED: "low",
    HUD_ITEMS_ENABLED: "low",
    HUD_SHOP_ENABLED: "low",
    HUD_SOULS_ENABLED: "low",
    HUD_TOP_BAR_ENABLED: "low",
    ENABLE_TAB_ZOOM: "low",
    ENABLE_ULT_COOLDOWNS: "low",
    ENABLE_UNSECURED_SOUL_TIMER: "low",
    ENABLE_URN_DIFF: "low",
    ENABLE_URN_TIMER: "low",
    ENABLE_URN_COLORS: "none",
    ENABLE_ZIP_BOOST: "low",
    HEALTHBAR_TYPE: "low",
    ENABLE_MINECRAFT_HEALTH_NUMBERS: "none",
    PLAYER_HEALTHBAR_SCALE: "none",
    PLAYER_HEALTHBAR_OPACITY: "none",
    PLAYER_HEALTHBAR_X_OFFSET: "none",
    PLAYER_HEALTHBAR_Y_OFFSET: "none",
    PLAYER_HEALTHBAR_ACCENT_COLOR: "none",
    BOTTOM_BAR_WASH_COLOR: "none",
    KEYBOARD_OVERLAY_WASH_COLOR: "none",
    STAMINA_CHARGE_COLOR: "none",
    STAMINA_CHARGE_ANGLE: "none",
    AMMO_CLIP_ANGLE: "none",
    AMMO_TEXT_COLOR: "none",
    CHAT_SCALE: "none",
    CHAT_X_OFFSET: "none",
    CHAT_Y_OFFSET: "none",
    ENABLE_CHAT: "none",
    ENABLE_IMAGES_IN_CHAT: "low",
    HITMARKERS_RUNTIME: "none",
    HUD_INDICATOR_SIZE: "none",
    ITEM_FILTER_DEF_ACTIVE: "low",
    ITEM_FILTER_DEF_PASSIVE: "low",
    ITEM_FILTER_OFF_ACTIVE: "low",
    ITEM_FILTER_OFF_PASSIVE: "low",
    KEYBOARD_OVERLAY_SCALE: "none",
    KEYBOARD_OVERLAY_X_OFFSET: "none",
    KEYBOARD_OVERLAY_Y_OFFSET: "none",
    LANGUAGE: "none",
    SETTINGS_THEME: "none",
    MINIMAL_MINIMAP: "low",
    MINIMAL_MINIMAP_OPACITY: "none",
    MINIMAP_BASE_OPACITY: "none",
    MINIMAP_FLIP: "none",
    MINIMAP_LARGE_SIZE_ALT: "none",
    MINIMAP_LARGE_SIZE_TAB: "none",
    MINIMAP_REMINDER_INTERVAL: "none",
    MINIMAP_ROTATE_WITH_PLAYER: "medium",
    MINIMAP_SMALL_SIZE: "none",
    MINIMAP_X_OFFSET: "none",
    MINIMAP_Y_OFFSET: "none",
    OPEN_AIM_TRAINER: "none",
    OPEN_BLACKJACK: "none",
    OPEN_FLAPPY_BIRD: "none",
    OPEN_MINESWEEPER: "none",
    OPEN_OLD_ITEM_FILTERS_DOWNLOAD: "none",
    OPEN_TRAIN_TRACKING: "none",
    OPEN_WHACK_A_REM: "none",
    GAME_DEFAULT_DIFFICULTY: "none",
    PASSIVE_COOLDOWN_OPACITY: "none",
    PASSIVE_COOLDOWN_SIZE: "none",
    PASSIVE_COOLDOWN_X: "low",
    PASSIVE_COOLDOWN_Y: "low",
    ITEMS_OPACITY: "none",
    ITEMS_X_OFFSET: "none",
    ITEMS_Y_OFFSET: "none",
    ITEMS_WASH_COLOR: "none",
    PREVIEWS_ENABLED: "none",
    ENABLE_UPDATE_CHECKER: "none",
    RELOAD_COOLDOWN_OPACITY: "none",
    RELOAD_COOLDOWN_SIZE: "none",
    RELOAD_COOLDOWN_X_OFFSET: "none",
    RELOAD_COOLDOWN_Y_OFFSET: "none",
    RUNTIME_MINIMAP_CLICK_RADIUS: "none",
    RUNTIME_MINIMAP_HERO_ICON_SIZE: "none",
    RUNTIME_MINIMAP_ICON_SHRINK: "low",
    RUNTIME_MINIMAP_PLAYER_ICON_SIZE: "none",
    RUNTIME_MINIMAP_REFRESH_RATE: "low",
    RUNTIME_MINIMAP_SHRINK_DISTANCE: "none",
    RUNTIME_MINIMAP_ZIP_THICKNESS: "none",
    RUNTIME_STATS_SHOWFPS: "low",
    RUNTIME_STATS_SHOWFRAME: "low",
    RUNTIME_STATS_SHOWMEM: "low",
    RUNTIME_STATS_SHOWPOS: "low",
    RUNTIME_STATS_SHOWTICK: "low",
    SHOP_OPACITY: "none",
    SHOP_OFFSET_X: "none",
    SHOP_OFFSET_Y: "none",
    SHOP_SCALE: "none",
    SOULS_OPACITY: "none",
    SOULS_X_OFFSET: "none",
    SOULS_Y_OFFSET: "none",
    SUPPORT_16_10: "none",
    SUPPORT_4_3: "none",
    TAB_ZOOM_DRAW_OVER_UI: "low",
    TAB_ZOOM_OPACITY: "none",
    TOP_BAR_OPACITY: "none",
    TOP_BAR_SCALE: "none",
    TOP_BAR_X_OFFSET: "none",
    TOP_BAR_Y_OFFSET: "none",
    BOTTOM_BAR_OPACITY: "none",
    BOTTOM_BAR_SCALE: "none",
    BOTTOM_BAR_X_OFFSET: "none",
    BOTTOM_BAR_Y_OFFSET: "none",
    UNIT_TARGET_OPACITY: "none",
    UNIT_TARGET_SIZE: "none",
    UNIT_TARGET_HINT_SIZE: "none",
    UNSECURED_SOULS_HUD_SCALE: "none",
    UNSECURED_SOULS_HUD_X_OFFSET: "none",
    UNSECURED_SOULS_HUD_Y_OFFSET: "none",
    UNSECURED_SOUL_TIMER_SCALE: "none",
    UNSECURED_SOUL_TIMER_X_OFFSET: "none",
    UNSECURED_SOUL_TIMER_Y_OFFSET: "none",
    VOICE_TYPE: "low",
    VOICE_VOLUME: "none",
    ZIP_BOOST_SCALE: "none",
    ZIP_BOOST_X_OFFSET: "none",
    ZIP_BOOST_Y_OFFSET: "none",
    ZOOM_X_OFFSET_ALT: "none",
    ZOOM_X_OFFSET_TAB: "none",
    ZOOM_Y_OFFSET_ALT: "none",
    ZOOM_Y_OFFSET_TAB: "none",
    ENABLE_BHOP: "low",
    ENABLE_ON_DEATH_GAMES: "low",
    ENABLE_PERF_DEBUG: "none",
    ENABLE_PERF_DEBUG_DETAIL: "none",
    ENABLE_PERF_OVERLAY: "low",
    PERF_ALERT_THRESHOLD_MS: "low",
    PERF_OVERLAY_OPACITY: "none",
    RECENT_PURCHASES_PANEL_SCALE: "none",
    RECENT_PURCHASES_PANEL_X_OFFSET: "none",
    RECENT_PURCHASES_PANEL_Y_OFFSET: "none",
    RECENT_PURCHASES_QUICK_DISPLAY_SEC: "none",
    RECENT_PURCHASES_QUICK_MAX: "none",
    RECENT_PURCHASES_QUICK_SCALE: "none",
    RECENT_PURCHASES_QUICK_X_OFFSET: "none",
    RECENT_PURCHASES_QUICK_Y_OFFSET: "none",
    SHOW_RANK: "low",
    SHOW_RANK_TOPBAR: "low",
};

const DEFAULT_HERO_OPTIONS = [
        "hero_inferno",
        "hero_gigawatt",
        "hero_hornet",
        "hero_ghost",
        "hero_atlas",
        "hero_wraith",
        "hero_forge",
        "hero_chrono",
        "hero_dynamo",
        "hero_kelvin",
        "hero_haze",
        "hero_astro",
        "hero_bebop",
        "hero_nano",
        "hero_orion",
        "hero_krill",
        "hero_shiv",
        "hero_tengu",
        "hero_warden",
        "hero_yamato",
        "hero_lash",
        "hero_viscous",
        "hero_synth",
        "hero_mirage",
        "hero_viper",
        "hero_magician",
        "hero_vampirebat",
        "hero_drifter",
        "hero_priest",
        "hero_frank",
        "hero_bookworm",
        "hero_doorman",
        "hero_punkgoat",
        "hero_necro",
        "hero_fencer",
        "hero_familiar",
        "hero_werewolf",
        "hero_unicorn"
    ];

    const DEFAULT_HERO_DISPLAY_NAMES = {
        hero_inferno: "Infernus",
        hero_gigawatt: "Seven",
        hero_hornet: "Vindicta",
        hero_ghost: "Lady Geist",
        hero_atlas: "Abrams",
        hero_wraith: "Wraith",
        hero_forge: "McGinnis",
        hero_chrono: "Paradox",
        hero_dynamo: "Dynamo",
        hero_kelvin: "Kelvin",
        hero_haze: "Haze",
        hero_astro: "Holliday",
        hero_bebop: "Bebop",
        hero_nano: "Calico",
        hero_orion: "Grey Talon",
        hero_krill: "Mo & Krill",
        hero_shiv: "Shiv",
        hero_tengu: "Ivy",
        hero_warden: "Warden",
        hero_yamato: "Yamato",
        hero_lash: "Lash",
        hero_viscous: "Viscous",
        hero_synth: "Pocket",
        hero_mirage: "Mirage",
        hero_viper: "Vyper",
        hero_magician: "Sinclair",
        hero_vampirebat: "Mina",
        hero_drifter: "Drifter",
        hero_priest: "Venator",
        hero_frank: "Victor",
        hero_bookworm: "Paige",
        hero_doorman: "Doorman",
        hero_punkgoat: "Billy",
        hero_necro: "Graves",
        hero_fencer: "Apollo",
        hero_familiar: "Rem",
        hero_werewolf: "Silver",
        hero_unicorn: "Celeste"
    };

    const DEFAULT_HERO_DROPDOWN_OPTIONS = DEFAULT_HERO_OPTIONS.map((heroId) => {
        return { label: DEFAULT_HERO_DISPLAY_NAMES[heroId] || heroId, value: heroId };
    }).sort((a, b) => {
        const labelA = String(a?.label || "").toLowerCase();
        const labelB = String(b?.label || "").toLowerCase();
        if (labelA < labelB) return -1;
        if (labelA > labelB) return 1;
        return 0;
    });

    const COMPACT_DEFAULT_HERO_FIELD = "DEFAULT_HERO_INDEX";
    const HERO_HINT_PUBLISH_INTERVAL_SEC = 1.0;

    const MetadataApi = {
        PERF_IMPACT_TIER_NONE,
        PERF_IMPACT_TIER_LOW,
        PERF_IMPACT_TIER_MEDIUM,
        PERF_IMPACT_TIER_HIGH,
        PERF_IMPACT_TIER_ORDER,
        PERF_IMPACT_LABEL_BY_TIER,
        SETTING_CREATED_BY_BY_CONFIG,
        SETTING_CREATED_BY_BY_LABEL,
        SECTION_CREATED_BY_BY_TITLE,
        SETTING_DESCRIPTION_OVERRIDE_BY_CONFIG,
        SETTING_DESCRIPTION_OVERRIDE_BY_CATEGORY_ROW,
        SECTION_DESCRIPTION_OVERRIDE_BY_TAB_TITLE,
        SETTING_PERF_IMPACT_TIERS,
        DEFAULT_HERO_OPTIONS,
        DEFAULT_HERO_DISPLAY_NAMES,
        DEFAULT_HERO_DROPDOWN_OPTIONS,
        COMPACT_DEFAULT_HERO_FIELD,
        HERO_HINT_PUBLISH_INTERVAL_SEC
    };

    Q.ui.metadata = MetadataApi;

    if (typeof globalThis !== "undefined") {
        Object.assign(globalThis, MetadataApi);
    }
})();
