// ql_settings_loc_pl.js — QOLLOCK settings locale (pl)
// Extracted from ql_settings.js, Phase 1
(function() {
    'use strict';
    var _root = (typeof globalThis !== "undefined") ? globalThis : (typeof window !== "undefined") ? window : {};
    if (!_root.SETTINGS_LOCALE_TEXT) _root.SETTINGS_LOCALE_TEXT = {};
    _root.SETTINGS_LOCALE_TEXT["pl"] = {
    "<font color=\"#66cc99\">Free</font> updates for new features, <font color=\"#66cc99\">$5</font> for arbitrary changes": "<font color=\"#66cc99\">Bezpłatne</font> aktualizacje nowych funkcji, <font color=\"#66cc99\">5 USD</font> za dowolne zmiany",
    "16:10 Support": "Wsparcie 16:10",
    "1st": "Pierwszy",
    "21:9 Stream Fix": "Poprawka Streamu 21:9",
    "2nd": "Drugi",
    "3rd": "Trzeci",
    "4:3 Support": "Wsparcie 4:3",
    "Ability Cooldown %: --": "% Czasu Odnowienia Umiejętności: --",
    "Ability Menu Open": "Menu Umiejętności Otwarte",
    "Ability Suggestion": "Sugestia Umiejętności",
    "Accent Color": "Kolor Akcentujący",
    "Accuracy:": "Precyzja:",
    "actionbutton": "przycisk akcji",
    "Addons": "Dodatki",
    "Adds a STAT button on profile rows that opens Statlocker for that account.": "Dodaje przycisk STAT w profilu, który otwiera profil Statlocker dla tego konta.",
    "Adjust horizontal position of the in-game chat.": "Dostosuj poziomą pozycję czatu w grze.",
    "Adjust horizontal position of the player healthbar.": "Dostosuj poziomą pozycję paska zdrowia gracza.",
    "Adjust opacity of the player healthbar.": "Dostosuj przezroczystość paska zdrowia gracza.",
    "Adjust size of the in-game chat.": "Dostosuj rozmiar czatu w grze.",
    "Adjust size of the player healthbar.": "Dostosuj rozmiar paska zdrowia gracza.",
    "Adjust the in-game chat position and scale.": "Dostosuj pozycję i skalę czatu w grze.",
    "Adjust vertical position of the in-game chat.": "Dostosuj pionową pozycję czatu w grze.",
    "Adjust vertical position of the player healthbar.": "Dostosuj pionową pozycję paska zdrowia gracza.",
    "Advanced": "Zaawansowany",
    "Advanced Filter": "Zaawansowany Filtr",
    "Advanced Mode": "Tryb Zaawansowany",
    "Skyrunner switch sent.": "Przełącznik Skyrunner wysłany.",
    "All commissioned additions are released publicly and available to everyone.": "Wszystkie zlecane dodatki są udostępniane publicznie i dostępne dla każdego.",
    "Allows you to drag move some menus.": "Umożliwia przeciąganie i przesuwanie niektórych menu.",
    "Ally HP Warning": "Ostrzeżenie o HP Sojusznika",
    "Already at default value.": "Jest już domyślne/a",
    "Alt Zoom": "Alternatywne Powiększenie",
    "Always Hidden": "Zawsze Ukryty",
    "Always Shown": "Zawsze Pokazane/a",
    "Always Visible Boost": "Wzmocnienie Zawsze Widoczne",
    "Always Visible Override": "Zastąpienie Zawsze Widoczne",
    "Ammo": "Amunicja",
    "An always visible zipline boost overlay.": "Zawsze widoczna nakładka wzmocnienia tyrolki",
    "Angle and Speed": "Kąt i Prędkość",
    "Announcer": "Spiker",
    "Append the selected build title after the build ID.": "Pokaż tytuł builda po jego ID",
    "APPLIED": "ZASTOSOWANO",
    "APPLY": "ZASTOSUJ",
    "Arcade": "Mini-gry",
    "Asmon": "Asmon",
    "Audio": "Dźwięk",
    "Author:": "Autor:",
    "Automatically selects Lane Preference: With Party for matchmaking.": "Automatycznie wybiera Preferencje Linii \"Z Drużyną\" podczas matchmakingu.",
    "Backup & Restore": "Kopia Zapasowa i Przywracanie",
    "Base": "Główne",
    "Be conscious of the features you are using and read carefully.": "Bądź świadomy funkcji, których używasz i czytaj uważnie.",
    "Bebop Sweeper": "SaBeboper",
    "Beep": "Beep",
    "Behavior Summary": "Podsumowanie Zachowania",
    "Best:": "Najlepszy Wynik:",
    "Better Item Cooldowns": "Lepsze Cooldowny Przedmiotów",
    "Better Unsecured": "Lepsze Niezabezpieczone",
    "Better Unsecured Souls": "Lepsze Niezabezpieczone Dusze",
    "BHOP UI": "Interfejs BHOP",
    "Big Number": "Duża Liczba",
    "Big Numbers": "Duże Liczby",
    "Big Red": "Duży Czerwony",
    "Blackjack": "Blackjack",
    "Blackjack - You win.": "Blackjack – Wygrywasz.",
    "Blur": "Rozmazanie",
    "Boom. Press New Game.": "Boom. Naciśnij Nowa Gra",
    "Bottom Bar": "Dolny Pasek",
    "BR Portuguese": "Portugalski (Brazylia)",
    "Bridge Buff": "Wzmocnienie Mostowe",
    "Bridge Buff Delay": "Opóźnienie Wzmocnienia Mostowego",
    "Bridge Buff Timer": "Timer na Wzmocnienia Mostowe",
    "Bridge Buffs": "Wzmocnienia Mostowe",
    "Budhud": "Budhud",
    "Buff": "Wzmocnienie",
    "Buff Delay": "Opóźnienie Wzmocnienia",
    "Buff Filter": "Filtr Wzmocnienia",
    "Buff Reminder": "Przypomnienie o Wzmocnieniu",
    "Buff Timer": "Timer na Wzmocnienie/a",
    "Bulgarian": "Bułgarski",
    "Bust - Dealer wins.": "Spalony – Krupier wygrywa.",
    "by": "przez",
    "By default everything is disabled and has nearly zero performance cost.": "Domyślnie wszystko jest wyłączone i ma prawie zerowy koszt wydajności.",
    "Cancel": "Anuluj",
    "Captions": "Napisy",
    "Centered ESC Menu": "Wyśrodkowane Menu pod Escape",
    "Centered Friends List": "Wyśrodkowana Lista Znajomych",
    "Centers ESC menu elements to make them easier to access.": "Wyśrodkowuje elementy menu Escape, aby ułatwić do nich dostęp.",
    "Centers friends list area in ESC menu.": "Wyśrodkowuje obszar listy znajomych w menu Escape.",
    "Centers the friends list area within the ESC menu.": "Wyśrodkowuje obszar listy znajomych w menu Escape.",
    "Change Log": "Lista Zmian",
    "CHANGE LOG": "LISTA ZMIAN",
    "Changes the element's transparency.": "Zmienia przezroczystość elementu.",
    "Changes the visual theme used by the settings menu, modals, loader, and save menus.": "Zmienia motyw wizualny używany przez menu ustawień, okienka, loader i menu zapisywania.",
    "Changes urn color to know which side is favored, green for your team, red for the enemy.": "Zmienia kolor urny, aby wiedzieć, dla której strony jest łatwiejsza, zielony dla twojej drużyny, czerwony dla wroga.",
    "Changes:": "Zmiany:",
    "Chat": "Chat",
    "Check out our site to join": "Sprawdź naszą stronę, aby dołączyć",
    "Chinese": "Chiński",
    "Choose a preset accent color for the player healthbar frame.": "Wybierz kolor akcentu dla ramki paska zdrowia gracza.",
    "Choose a preset border color for stamina charge indicators.": "Wybierz kolor wskaźnika staminy.",
    "Choose a preset color wash for minimap icons.": "Wybierz kolor ikon na minimapie.",
    "Choose a preset color wash for the bottom ability bar.": "Wybierz kolor dla dolnego paska umiejętności.",
    "Choose a preset color wash for the item bar.": "Wybierz kolor dla paska elementów.",
    "Choose a preset color wash for the keyboard overlay.": "Wybierz kolor dla nakładki klawiatury.",
    "Choose a preset text color for the ammo display.": "Wybierz kolor tekstu dla wskaźnika amunicji.",
    "Choose which bridge buff sound variants can play.": "Wybierz, które efekty dźwiękowe wzmocnienia mostowego będą odtwarzane.",
    "Circle": "Koło",
    "Clean Indicators": "Czyste Wskaźniki",
    "Clean Stacks": "Czyste Stacki",
    "Cleaner Items": "Czystsze Przedmioty",
    "Cleaner Skills": "Czystsze Skille",
    "Cleans up the styling of reticle hints.": "Oczyszcza styl wskaźników celownika.",
    "Cleans up the visuals of the shop stats display without changing the rest of the shop.": "Czyści wygląd statystyk w sklepie bez zmiany reszty sklepu.",
    "Cleans up visuals of abilities significantly to reduce clutter.": "Znacznie oczyszcza ikony umiejętności dla bardziej minimalistycznego wyglądu.",
    "Cleans up visuals of the item bar significantly to reduce clutter.": "Znacznie oczyszcza wygląd paska przedmiotów dla bardziej minimalistycznego wyglądu.",
    "Cleans up visuals of the minimap significantly to reduce clutter.": "Znacznie oczyszcza wygląd minimapy, dla bardziej minimalistycznego wyglądu.",
    "Cleans up visuals of the shop menu significantly to reduce clutter.": "Znacznie oczyszcza menu sklepu, dla bardziej minimalistycznego wyglądu.",
    "CLEAR": "WYCZYŚĆ",
    "Clear completed.": "Czyszczenie zakończone.",
    "Clear failed.": "Czyszczenie nie powiodło się.",
    "Clear in progress...": "Trwa czyszczenie...",
    "Clear timed out. Try again.": "Upłynął limit czasu dla czyszczenia. Spróbuj ponownie.",
    "CLEARED": "WYCZYSZCZONE",
    "Cleared in": "Odkryto w",
    "Clearing builds...": "Czyszczenie buildów...",
    "click here": "kliknij tutaj",
    "Click Radius": "Promień Kliknięcia",
    "Click to Notify": "Kliknij, aby Powiadomić",
    "Clip Size % Increase: --": "Procentowe Zwiększenie Rozmiaru Magazynka: --",
    "Clipboard copy failed.": "Kopiowanie do schowka nie powiodło się.",
    "Color": "Kolor",
    "Color Warning": "Kolorowe Ostrzeżenie",
    "Colored ally top-bar health warnings when at significant thresholds.": "Kolorowe ostrzeżenia o stanie zdrowia sojusznika na górnym pasku w przypadku osiągnięcia poszczególnych progów.",
    "Colored enemy healthbar warnings when at significant thresholds.": "Kolorowe ostrzeżenia na pasku zdrowia wroga przy poszczególnych progach.",
    "Colored enemy top-bar health warnings when at significant thresholds.": "Kolorowe ostrzeżenia o stanie zdrowia wroga na górnym pasku w przypadku osiągnięcia poszczególnych progów.",
    "Colored Health": "Kolorowe Zdrowie",
    "Colored Healthbar": "Kolorowy Pasek Zdrowia",
    "Colored healthbar warnings when at significant thresholds.": "Kolorowe ostrzeżenia na pasku zdrowia przy poszczególnych progach.",
    "Combat Indicator": "Wskaźnik Walki",
    "Combat Status": "Stan Walki",
    "Commission": "Zlecenie",
    "Community acknowledgements": "Podziękowania społeczności",
    "Compact Layout": "Kompaktowy Układ",
    "Compass": "Kompas",
    "Compass & Speed": "Kompas i Prędkość",
    "Config": "Konfiguracja",
    "Confirm": "Potwierdź",
    "Confirming Skyrunner for clear...": "Potwierdzanie Skyrunner w celu wyczyszczenia...",
    "Console": "Konsola",
    "Console Notes": "Informacje dot. Konsoli",
    "Contact": "Kontakt",
    "Contributors": "Współtwórcy",
    "COPIED": "SKOPIOWANO",
    "COPY": "KOPIUJ",
    "Cosmetic Ability": "Umiejętność Kosmetyczna",
    "Crashed. Click playfield to restart.": "Rozbiłeś się. Kliknij gdziekolwiek, aby zrestartować.",
    "Crate Overlay": "Nakładka Pudełek.",
    "Created By": "Stworzony Przez ",
    "Created By:": "Stworzony Przez:",
    "Credits": "Podziękowania",
    "Crosshair": "Celownik",
    "Current": "Aktualna",
    "Current ammo inside of your magazine.": "Aktualna amunicja w twoim magazynku.",
    "Current Size": "Rozmiar Aktualnej",
    "Custom": "Niestandardowy",
    "Custom Preset Commission: <font color=\"#66cc99\">$25</font>": "Zlecenie Niestandarowego Presetu: <font color=\"#66cc99\">25 USD</font>",
    "Customizable Unsecured Souls": "Personalizowane Niezabezpieczone Dusze",
    "Customize the styling of damage numbers.": "Dostosuj styl liczb obrażeń.",
    "Customize the visuals of the incoming damage panel.": "Dostosuj wygląd panelu nadchodzących obrażeń.",
    "Customize unsecured souls visuals.": "Dostosuj wygląd niezabezpieczonych dusz.",
    "Customize visibility of target reticle when abilities or items visually show on allies and enemies.": "Dostosuj widoczność celownika, gdy umiejętności lub przedmioty są widoczne na sojusznikach i wrogach.",
    "Customized healthbars for better visibility or flair.": "Personalizowane paski zdrowia dla lepszej widoczności i stylu.",
    "Damage Fountain": "Fontanna Obrażeń",
    "Damage Numbers": "Liczby Obrażeń",
    "Damage Report": "Raport Obrażeń",
    "DAMAGE REPORT": "RAPORT OBRAŻEŃ",
    "Dealer": "Krupier",
    "Dealer blackjack.": "Blackjack krupiera.",
    "Dealer busts - You win.": "Krupier spalił – Wygrywasz.",
    "Dealer wins.": "Krupier wygrywa.",
    "Decide what style of item to display the cooldown of.": "Zdecyduj jakiego typu przedmiotu będzie wyświetlany cooldown",
    "Deck:": "Deck:",
    "Default": "Domyślny",
    "Default 18": "Domyślnie 18",
    "Default 400": "Domyślnie 400",
    "Default difficulty when opening games.": "Domyślny poziom trudności podczas otwierania gier.",
    "Default Hero": "Domyślny Bohater",
    "Defensive Active": "Defensywny Aktywny",
    "Defensive Passive": "Defensywny Pasywny",
    "Depending on complexity and work involved": "W zależności od złożoności i wymaganego nakładu pracy",
    "Depending on complexity and work involved, contact me on": "W zależności od złożoności i wymaganego nakładu pracy, skontaktuj się ze mną",
    "Difficulty": "Poziom Trudności",
    "Ding to Check Minimap": "Przypomnienie o Sprawdzaniu Minimapy",
    "Disabled": "Wyłączone",
    "Discord": "Discord",
    "DISCORD": "DISCORD",
    "Discord: <font color=\"#66cc99\">civocivocivo</font>": "Discord: <font color=\"#66cc99\">civocivocivo</font>",
    "Display Hero": "Pokaż Bohatera",
    "Display Stats": "Pokaż Statystyki",
    "DO NOT PRESS ANY KEYS UNTIL COMPLETE UNLESS PROMPTED": "NIE WCISKAJ ŻADNYCH KLAWISZY DO ZAKOŃCZENIA, CHYBA ŻE ZOSTANIESZ O TO POPROSZONY",
    "Download": "Pobierz",
    "Drag": "Przeciągnij",
    "Draggable UI": "Przeciągalny Interfejs",
    "Draw Over UI": "Renderuj na Interfejsie",
    "Draws the minimap over all other UI elements for improved visibility.": "Renderuje minimapę na wszystkich innych elementach UI, aby poprawić widoczność.",
    "dropdown": "menu rozwijane",
    "Duration": "Czas Trwania",
    "Easier Access": "Łatwiejszy Dostęp",
    "Easy": "Łatwy",
    "Elevation Markers": "Znaczniki Wysokości",
    "en": "en",
    "Enable": "Włącz",
    "Enable sounds in arcade games.": "Włącz dźwięki w mini grach",
    "Enabled": "Włączone",
    "Enemy": "Wróg",
    "Enemy healthbar enhancements.": "Ulepszenia paska zdrowia wrogów.",
    "Enemy HP Warning": "Ostrzeżenie o HP Wroga",
    "English": "Angielski",
    "Enhanced V2 enemy healthbar visuals and readability.": "Ulepszona grafika i czytelność paska zdrowia wroga V2.",
    "error": "błąd",
    "ERROR: Invalid String": "BŁĄD: Nieprawidłowy Ciąg",
    "Estimated ult cooldowns under top-bar ult icons": "Szacowane czasy odnowienia superumiejętności pod ikonami superumiejętności na górnym pasku",
    "Export Settings": "Eksportuj Ustawienia",
    "Export String": "Ciąg Ustawień",
    "Export string copied.": "Ciąg Ustawień skopiowany",
    "F": "F",
    "FAILED": "NIEUDANE",
    "Failed Hint": "Podpowiedź Błędu",
    "Failed to queue save request.": "ZAPROPONUJ PRESET SPOŁECZNOŚCI",
    "Failed to switch hero.": "Nie udało się zmienić bohatera.",
    "Fighting Game": "Bijatyka",
    "Filters": "Filtry",
    "Find all safe tiles. Right-click to flag.": "Znajdź wszystkie bezpieczne pola. Prawy przycisk flaguje minę.",
    "Fire Rate: --": "Szybkostrzelność: --",
    "First Spawns": "Pierwsze Spawny",
    "Flags:": "Flagi:",
    "Flappy Bat": "Flappy Bat",
    "Flip": "Przerzuć",
    "For custom BHop gamemode UI changes.": "Zmiany interfejsu dla trybu BHop",
    "Force Testing Tools": "Wymuś Narzędzia Testowe",
    "Forcibly hides testing tools at all times.": "Wymusza ukrycie narzędzi testowych",
    "Forcibly shows testing tools at all times.": "Wymusza pokazanie narzędzi testowych",
    "Fountain-style damage number animation.": "Animacja liczby obrażeń w stylu fontanny.",
    "FPS Impact:": "Wpływ na FPS:",
    "French": "Francuski",
    "Full Keybinds": "Pełne Skróty Klawiszowe",
    "Full Keys": "Wszystkie Klawisze",
    "Game Audio": "Dźwięk z Gry",
    "Game Settings": "Ustawienia Gry",
    "Gamemodes": "Tryby Gry",
    "Games": "MiniGry",
    "General": "Ogólne",
    "Get Filter": "Pobierz Filtr",
    "Get Filter File Only": "Pobierz Tylko Plik Filtra",
    "Graves Trainer": "Trener Aima dla Krypty",
    "Greys out heros in the top bar when missing on the map.": "Wyszarza bohaterów na górnym pasku, gdy nie ma ich na mapie.",
    "Hard": "Trudny",
    "Health Numbers": "Liczba Zdrowia",
    "Healthbar": "Pasek Zdrowia",
    "Help and feedback": "Pomoc i feedback",
    "Help fund continued development": "Pomóż finansować dalszy rozwój",
    "Help, Contact & Support": "Pomoc, Kontakt i Wsparcie",
    "Help, feedback, and community": "Pomoc, feedback i społeczność",
    "Hero": "Bohater",
    "Hero Icon Size": "Rozmiar Ikony Bohatera",
    "Hero on Load or Save": "Bohater podczas Wczytywania lub Zapisywania",
    "Hide Ability Suggestion": "Ukryj Sugestię Umiejętności",
    "Hide All": "Ukryj Wszystko",
    "Hide Behavior Summary": "Ukryj Podsumowanie Zachowania",
    "Hide Big Number": "Ukryj Dużą Liczbę",
    "Hide Blur": "Ukryj Rozmycie",
    "Hide Circle": "Ukryj Okrąg",
    "Hide Cosmetic Ability": "Ukryj Umiejętność Kosmetyczną",
    "Hide Current": "Ukryj Bieżącą",
    "Hide Damage Report": "Ukryj Raport Obrażeń",
    "Hide Failed Hint": "Ukryj Podpowiedź Błędu",
    "Hide Icon": "Ukryj Ikonę",
    "Hide Quick Buy": "Ukryj Szybki Zakup",
    "Hide Small Numbers": "Ukryj Małe Liczby",
    "Hide Testing Tools": "Ukryj Narzędzia Testowe",
    "Hide Total": "Ukryj Sumę",
    "Hide Trooper Damage": "Ukryj Obrażenia Minionów (Szturmowców)",
    "High": "Wysoki",
    "HIGH FPS IMPACT WARNING!": "OSTRZEŻENIE O WYSOKIM WPŁYWIE NA FPSy!",
    "Highlight Mode": "Tryb Wyróżnienia",
    "Highlight regeneration in red for when in combat.": "Zaznacz regenerację na czerwono podczas walki.",
    "Highlighted abilities showing you what you should upgrade depending on build.": "Podświetla umiejętności pokazując, co powinieneś ulepszyć w zależności od builda.",
    "Hit": "Dobierz",
    "Hitmarkers": "Znaczniki Trafień",
    "Hits:": "Trafione:",
    "Horizontal Offset": "Przesunięcie Poziome",
    "Horizontal Stretch": "Rozciągnięcie Poziome",
    "How fast the minimap refreshes.": "Jak szybko odświeża się minimapa.",
    "How much icons will shrink when overlapping with others.": "Jak bardzo ikony zmniejszą się w przypadku nakładania się na inne.",
    "How to Save Settings": "Jak Zapisać Ustawienia",
    "HP Warning": "Ostrzeżenie o HP",
    "HUD": "HUD",
    "HUD Controls": "Sterowanie HUD",
    "Hud Shift": "Przesunięcie HUDa",
    "I am open to all feedback, suggestions, and ideas!": "Jestem otwarty na wszelkie uwagi, sugestie i pomysły!",
    "Icon": "Ikona",
    "Icon Shrink": "Zmniejszanie się Ikon",
    "Icons": "Ikony",
    "If saving stalls, open your shop.": "Jeżeli zapisywanie zawiesi się, otwórz sklep.",
    "If you encounter issues please join the Discord": "Jeśli napotkasz problemy, dołącz do Discorda",
    "If you encounter issues, need help, or have any feedback join the Discord.": "Jeśli napotkasz problemy, potrzebujesz pomocy lub masz jakiś feedback, dołącz do Discorda.",
    "Images in Chat": "Obrazki na Chacie",
    "Import failed.": "Importowanie nie powiodło się.",
    "Import Settings": "Importuj Ustawienia",
    "Import String": "Ciąg do Importu",
    "Import: applying settings...": "Importowanie: stosowanie ustawień...",
    "Import: parsing string...": "Importowanie: analizowanie ciągu...",
    "Import: refreshing UI...": "Importowanie: odświeżanie UI...",
    "Improve Ability Stacks": "Ulepsz Stacki Umiejętności",
    "Improved Hint": "Ulepszone Wskaźniki",
    "IN COMBAT": "W WALCE",
    "In Seconds": "W Sekundach",
    "info": "info",
    "Invalid import string.": "Nieprawidłowy ciąg do importu.",
    "Issues, Feedback and Ideas": "Problemy, Opinie i Pomysły",
    "Item Cooldowns": "Cooldowny Itemów",
    "Item Target Reticle": "Wskaźnik Celu Przedmiotu",
    "Japanese": "Japoński",
    "Keyboard": "Klawiatura",
    "Klutz's Bar": "Bar Klutza",
    "Lane with Party": "Linia z Drużyną",
    "Language": "Język",
    "Latest updates and version notes": "Najnowsze aktualizacje i lista zmian wersji",
    "Legacy Durations": "Czasy Trwania Legacy",
    "Light Item Cooldowns": "Lekkie Czasy Odnowienia Przedmiotów",
    "Local settings loaded.": "Załadowano ustawienia lokalne.",
    "Loud": "Głośny",
    "Low": "Niski",
    "Low Stamina Popup": "Wyskakujące Okienko Niskiej Staminy",
    "Makes the minimap rotate with player view, this is just for fun.": "Sprawia, że ​​minimapa obraca się wraz z widokiem gracza. Dla zabawy.",
    "Max Health: --": "Maksymalne Zdrowie: --",
    "Max Notifications": "Maksymalna Liczba Powiadomień",
    "Medium": "Średni",
    "Menu when you receive a punishment for breaking game rules.": "Menu, gdy otrzymasz karę za złamanie zasad.",
    "Meta Settings": "Ustawienia Mety",
    "Metro Button": "Przycisk Metro",
    "Mid Boss Timer": "Timer Mid Bossa",
    "Midtown-only crate markers on the minimap.": "Znaczniki pudełek tylko w Midtown na minimapie.",
    "Mines:": "Miny:",
    "Minimalist": "Minimalistyczna",
    "Minimalist Abilities": "Minimalistyczne Umiejętności",
    "Minimalist Healthbar": "Minimalistyczny Pasek Zdrowia",
    "Minimalist Item Bar": "Minimalistyczny Pasek Przedmiotów",
    "Minimalist Minimap": "Minimalistyczna Minimapa",
    "Minimalist Opacity": "Nieprzezroczystość Trybu Minimalistycznego",
    "Minimap": "Minimapa",
    "Minimap Reminder": "Przypomnienie o Minimapie",
    "Mirror unsecured gold number": "Lustrzanie odbij złoty numer niezabezpieczonych dusz",
    "Misses:": "Chybionych:",
    "Missing Hero Opaque": "Niewidoczny Bohater Zacieniony",
    "Modify damage numbers for a cleaner style and animation to be more out of the way": "Zmień liczby obrażeń, aby uzyskać czystszy i bardziej minimalistyczny styl i animację",
    "MOG is Deadlock's first custom gamemode community server network.": "MOG to pierwsza sieć customowych serwerów Deadlock.",
    "moglock.gg": "moglock.gg",
    "Move ability stacks to bottom-center of ability icon": "Przenieś stacki umiejętności na środkową dolną część ikony umiejętnosći",
    "Move ability stacks to bottom-center of ability icon.": "Przenieś stacki umiejętności na środkową dolną część ikony umiejętnosći.",
    "Move notifications around Rejuvenator and Scoreboard UI.": "Przenieś powiadomienia znad interfejsu Odnawiacza oraz Tablicy Wyników",
    "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.": "Przesuwa timer Wzmocnień Mostowych na most z dwoma mniejszymi zcentrowanymi kopiami.",
    "Moves the element horizontally.": "Przesuwa element w poziomie.",
    "Moves the element vertically.": "Przesuwa element w pionie.",
    "Moves the Mid Boss timer onto the bridge area of the minimap.": "Przesuwa timer Mid Bossa na obszar mostu na minimapie.",
    "multitoggle": "multitoggle",
    "N/A": "N/A",
    "Neutral Camps": "Potwory Neutralne",
    "New Feature Commission: <font color=\"#66cc99\">$10</font> to <font color=\"#66cc99\">$100</font>": "Opłata za nową funkcję: od <font color=\"#66cc99\">10 USD</font> do <font color=\"#66cc99\">100 USD</font>",
    "New Game": "Nowa Gra",
    "New Hand": "Następna gra",
    "New Run": "Nowy Run",
    "Nicknames": "Pseudonimy",
    "No color wash": "Bez zmiany koloru",
    "No filter settings but better FPS.": "Bez ustawień filtrów, ale lepsze FPSy.",
    "No results found": "Brak wyników",
    "No setting changes detected.": "Nie wykryto żadnych zmian ustawień.",
    "None": "None",
    "Normal": "Normalny/a",
    "Notify your teammates in chat about how close you are to a quickbuy purchase.": "Powiadom swoich członków drużyny na czacie o tym, ile brakuje Ci dusz do szybkiego zakupu.",
    "Objective Damage": "Obrażenia Celów",
    "Objective Map": "Mapa Celów",
    "Off": "Wył.",
    "Offensive Active": "Ofensywny Aktywny",
    "Offensive Passive": "Ofensywny Pasywny",
    "On": "Wł.",
    "On Ability Upgrade": "Przy Ulepszeniu Umiejętności",
    "On Death": "Przy Śmierci",
    "On Death Games": "Gry Przy Śmierci",
    "Only download the filter file of the filter you want, nothing else.": "Pobierz tylko plik filtra, który chcesz, nic więcej.",
    "Opacity": "Przezroczystość",
    "Opacity of the background of Minimalist Minimap.": "Nieprzezroczystość tła Minimalistycznej Minimapy.",
    "Opacity of the underground tunnel overlay while Alt Zoom is active.": "Nieprzezroczystość nakładki podziemnych tuneli, gdy przybliżenie pod Alt jest aktywne.",
    "Opacity of the underground tunnel overlay while Tab Zoom is active.": "Nieprzezroczystość nakładki podziemnych tuneli, gdy przybliżenie pod Tab jest aktywne.",
    "Opacity of the underground tunnel overlay.": "Nieprzezroczystość nakładki podziemnych tuneli.",
    "Open": "Otwórz",
    "Open Config": "Otwórz Konfig",
    "Open random game when dead": "Otwórz losową grę, gdy jesteś martwy",
    "Open Settings": "Otwórz Ustawienia",
    "Open shop to continue clear.": "Otwórz sklep, aby kontynuować czyszczenie.",
    "Open shop to continue save.": "Otwórz sklep, aby kontynuować zapisywanie.",
    "Optimize Filters": "Optymalizuj Filtry",
    "Optimize Mode": "Optymalizuj Tryb",
    "Overlay": "Nakładka",
    "palette": "paleta",
    "Paste and apply an exported settings string": "Wklej i zastosuj wyeksportowany ciąg ustawień",
    "Play": "Graj",
    "Play an audio reminder to remember to look at the minimap.": "Odtwórz efekt dźwiękowy, aby pamiętać o spojrzeniu na minimapę.",
    "Play current announcer voice and volume.": "Odtwórz bieżący głos i głośność spikera.",
    "Play current announcer voice.": "Odtwórz bieżący głos spikera.",
    "Play Sound": "Odtwórz Dźwięk",
    "Play When On Death Enabled": "Opcja \"Graj Po Śmierci\" Włączona",
    "Player": "Gracz",
    "Player Icon Size": "Rozmiar Ikony Gracza",
    "Polish": "Polski",
    "Portuguese": "Portugalski",
    "Position and Velocity real time statistics.": "Statystyki Pozycji i Prędkości w czasie rzeczywistym.",
    "Preset apply failed.": "Nie udało się zastosować presetu.",
    "Presets": "Presety",
    "Preview": "Podgląd",
    "Preview Announcer": "Podgląd Spikera",
    "Preview Changes": "Podgląd Zmian",
    "Preview realtime changes to settings when modifying them.": "Podgląd zmian ustawień w czasie rzeczywistym podczas ich modyfikowania.",
    "Preview setting changes in realtime.": "Podgląd zmian ustawień w czasie rzeczywistym.",
    "Push - Both have blackjack.": "Remis – Oboje mają blackjacka.",
    "Push.": "Naciskać.",
    "Q": "Q",
    "QOL": "QOL",
    "QOL Settings Clearer": "Moduł Czyszczenia Ustawień QOL",
    "QOL Settings Loader": "Moduł Ładowania Ustawień QOL",
    "QOL Settings Saver": "Moduł Zapisywania Ustawień QOL",
    "Quick Buy": "Szybki Zakup",
    "Quiet": "Cichy",
    "Ragnarok Online damage visuals with improved fancy styling.": "Obrażenia wizualne z Ragnarock Online z ulepszoną stylistyką.",
    "RAM and GPU Memory real time usage statistics.": "Statystyki wykorzystania pamięci RAM i GPU w czasie rzeczywistym.",
    "Randomly opens an enabled arcade game while dead.": "Losowo otwiera jedną z włączonych gier zręcznościowych, kiedy umrzesz.",
    "Ready": "Gotowy",
    "Ready.": "Gotowy.",
    "Real time key input visual.": "Wizualizacja wciskania klawiszy w czasie rzeczywistym.",
    "Realtime Changes": "Zmiany w Czasie Rzeczywistym",
    "Realtime Drain Countdown": "Timer Zabezpieczania Dusz w Czasie Rzeczywistym",
    "Realtime Key Inputs": "Klawisze w Czasie Rzeczywistym",
    "Realtime Settings Changes": "Zmiany Ustawień w Czasie Rzeczywistym",
    "Recommended for 4:3": "Zalecane dla 4:3",
    "Refresh Rate": "Częstotliwość Odświeżania",
    "Reload Cooldown": "Czas Przeładowania",
    "Reloading": "Przeładowanie",
    "Rem Tunnels": "Tunele Rema",
    "Rem Tunnels Opacity": "Nieprzezroczystość Tunelów Rema",
    "Remind when big camps and Sinner's Sacrifice are spawning.": "Przypomnij, kiedy pojawiają się duże potwory oraz kasyna.",
    "Remind when bridge buffs and melee troopers are spawning.": "Przypomnij, kiedy pojawiają się wzmocnienia mostowe i miniony walczące wręcz (szturmowce).",
    "Remind when bridge buffs are spawning.": "Przypomnij, kiedy pojawiają się wzmocnienia mostowe.",
    "Remind when bridge buffs spawn and gold statue buffs are maxed.": "Przypomnij, kiedy wzmocnienia mostowe i złote posągi osiągną najlepsze wartości.",
    "Remind when bridge buffs spawn and troopers improve again.": "Przypomnij, kiedy pojawią się wzmocnienia mostowe oraz miniony (szturmowce) się ulepszą.",
    "Remind when bridge buffs spawn and troopers speed up.": "Przypomnij, kiedy pojawiają się wzmocnienia mostowe oraz miniony (szturmowce) przyspieszają.",
    "Remind when lane guardian resistance is reduced.": "Przypomnij, kiedy ochrona strażników liniowych zmniejszy się.",
    "Remind when medium camps are spawning.": "Przypomnij, kiedy pojawiają się średnie potwory.",
    "Remind when midboss, urn, bridge buffs, and gold statue upgrades are spawning.": "Przypomnij, kiedy pojawi się midboss, urna i wzmocnienia mostowe oraz złote posągi ulepszą się.",
    "Remind when small camps, boxes, and statues are spawning.": "Przypomnij, kiedy pojawią się małe potwory, pudła oraz posągi.",
    "Remind when walker resistance is reduced.": "Przypomnij, kiedy ochrona stąpacza zostanie zmniejszona.",
    "Render image URLs as images.": "Renderuj adresy URL obrazów jako obrazy.",
    "Replaces quickbuy with the Enhanced Quickbuy standalone layout and queue summaries.": "Zastępuje opcję szybkiego zakupu osobnym stylem oraz podsumowaniami kolejek Enchanced Quickbuy.",
    "Reposition": "Zmień Położenie",
    "Request a community preset": "Zaproponuj preset społeczności",
    "Request a custom feature or preset": "Zaproponuj niestandardową funkcję lub preset",
    "Reset row to defaults": "Zresetuj wiersz do wartości domyślnych",
    "Reset section runtime options": "Zresetuj opcje sekcji w runtime",
    "Reset section to defaults": "Zresetuj sekcję do ustawień domyślnych",
    "Reset to default value": "Przywróć wartość domyślną",
    "Reset to default value.": "Przywróć wartość domyślną.",
    "Restores the legacy removed duration bars for abilities.": "Przywraca legacy paski czasu trwania dla umiejętności",
    "Retheme the settings menu, modals, loader, and save menus with a shared aesthetic.": "Zmień motyw menu ustawień, okienek, modułu ładującego i menu zapisywania na wspólną estetykę.",
    "Rotate": "Obróć",
    "Rotate the stamina charge indicator.": "Obróć wskaźnik naładowania staminy.",
    "Rotates the static minimap 180 degrees.": "Obraca statyczną minimapę o 180 stopni.",
    "Row already at defaults.": "Wiersz ma już wartości domyślne",
    "Row reset (": "Resetowanie wiersza (",
    "Run complete. Press New Run.": "Run ukończony. Naciśnij Nowy Run.",
    "Russian": "Rosyjski",
    "SAVE": "ZAPISZ",
    "Save": "Zapisz",
    "Save completed.": "Zapisywanie zakończone.",
    "Save failed.": "Zapisywanie nie powiodło się.",
    "Save in progress...": "Zapis w toku...",
    "Save queued.": "Zapis umieszczony w kolejce.",
    "Save timed out. Try again.": "Upłynął limit czasu zapisu. Spróbuj ponownie.",
    "Save works only in hideout.": "Zapis działa tylko w kryjówce.",
    "SAVED": "ZAPISANO",
    "Scale": "Skala",
    "Scales the element.": "Skaluje element.",
    "Score:": "Wynik:",
    "Scoreboard Open": "Tablica Wyników Otwarta",
    "Search Results": "Wyniki Wyszukiwania",
    "Seconds Before Spawn": "Sekundy Przed Odrodzeniem",
    "Seconds each notification stays visible.": "Ilość czasu w sekundach przez który powiadomienie jest widoczne",
    "Section already at defaults.": "Sekcja ma już ustawienia domyślne.",
    "Section reset (": "Reset sekcji (",
    "See the recent purchases made in the game.": "Zobacz ostatnie zakupy dokonane w grze.",
    "See your view angle and speed.": "Sprawdź swój kąt widzenia i prędkość.",
    "Settings Changes": "Zmiany Ustawień",
    "Settings now load from your saved build string": "Ustawienia są teraz ładowne z twojego zapisanego ciągu ustawień",
    "Settings UI Language": "Język interfejsu ustawień",
    "Share or save your settings configuration!": "Udostępnij lub zapisz swoją konfigurację ustawień!",
    "Share your settings string": "Udostępnij ciąg ustawień",
    "Shifts the HUD for better visual support for 16:10 resolutions.": "Przesuwa HUD zapewniajac lepsze wsparcie dla rozdzielczości 16:10.",
    "Shifts the HUD for better visual support for 4:3 resolutions.": "Przesuwa HUD zapewniając lepsze wsparcie dla rozdzielczości 4:3.",
    "Shop": "Sklep",
    "Show a short caption when Deadlock For Dummies reminders play.": "Wyświetlaj krótki napis podczas odtwarzania przypomnień Deadlock For Dummies.",
    "Show a visual indicator in the top bar of the current Guardians, Walkers, and Base.": "Pokaż wskaźnik wizualny aktualnych Strażników, Stąpaczy i Bazy na górnym pasku.",
    "Show an overlay of the underground tunnels.": "Pokaż nakładkę podziemnych tuneli.",
    "Show Compass": "Pokaż Kompas",
    "Show current / max HP numbers over the Minecraft hearts.": "Pokaż aktualne/maksymalne liczby HP nad sercami z Minecraft.",
    "Show Filters": "Pokaż Filtry",
    "Show FPS": "Pokaż FPSy",
    "Show Frame": "Pokaż Klatkę",
    "Show Icon": "Pokaż Ikonę",
    "Show if you are in combat or not.": "Pokaż, czy jesteś w stanie walki, czy nie.",
    "Show level text on V2 enemy healthbars.": "Pokaż tekst poziomu na paskach zdrowia wroga V2.",
    "Show Memory": "Pokaż Pamięć",
    "Show player ultimate indicators on V1 healthbars.": "Pokaż wskaźniki superumiejętności gracza na paskach zdrowia V1.",
    "Show Position": "Pokaż Pozycję",
    "Show Speed": "Pokaż Prędkość",
    "Show Support": "Pokaż Wsparcie",
    "Show Testing Tools": "Pokaż Narzędzia Testowe",
    "Show Text": "Pokaż Tekst",
    "Show the estimated time for unsecured souls to dissapear.": "Pokaż szacowany czas, po którym niezabezpieczone dusze zostaną zabezpieczone.",
    "Show the in-game chat panel.": "Pokaż panel czatu w grze.",
    "Show the ultimate indicator for V1 healthbars.": "Pokaż wkaźnik superumiejętności na paskach zdrowia V1.",
    "Show the underground tunnel overlay while Alt Zoom is active.": "Pokaż nakładkę podziemnych tunelów, gdy przybliżenie pod Alt jest aktywne.",
    "Show the underground tunnel overlay while Tab Zoom is active.": "Pokaż nakładkę podziemnych tunelów, gdy przybliżenie pod Tab jest aktywne.",
    "Show the UnitInfo panel on V2 enemy healthbars.": "Pokaż panel UnitInfo na paskach zdrowia wrogów V2.",
    "Show Tick": "Pokaż Tick",
    "Show Title": "Pokaż Tytuł",
    "Showing:": "Pokazane:",
    "Shown Items": "Pokazane Przedmioty",
    "Shows a visual indicator in the minimap of when Bridge Buffs will spawn.": "Pokazuje wizualny wskaźnik na minimapie, kiedy pojawią się Wzmocnienia Mostowe.",
    "Shows a visual indicator in the minimap of when Mid Boss will spawn.": "Pokazuje wizualny wskaźnik na minimapie, kiedy pojawi się Mid Boss.",
    "Shows a visual indicator in the top bar of the percentage difference of souls between teams.": "Pokazuje wizualny wskaźnik na górnym pasku procentowej różnicy dusz pomiędzy drużynami.",
    "Shows a visual indicator in the top bar of when Bridge Buffs will spawn.": "Pokazuje wizualny wskaźnik na górnym pasku, kiedy pojawią się Wzmocnienia Mostowe.",
    "Shows a visual indicator in the top bar of when Mid Boss will spawn.": "Pokazuje wizualny wskaźnik na górnym pasku, kiedy pojawi się Mid Boss.",
    "Shows all of your keybinds.": "Pokazuje wszystkie skróty klawiszowe.",
    "Shows all of your player stats within the shop menu.": "Pokazuje wszystkie statystyki gracza w menu sklepu.",
    "Shows current frame count, mostly useless.": "Pokazuje aktualną liczbę klatek, w większości bezużyteczne.",
    "Shows item buy notifications from recent purchases.": "Pokazuje powiadomienia o przedmiotach zakupionych niedawno.",
    "Shows item cooldowns near crosshair for easier readability.": "Pokazuje cooldowny itemów w pobliżu celownika, dla łatwiejszej czytelności.",
    "Shows Midtown crate markers in the minimap.": "Pokazuje znaczniki skrzyń w Midtown na minimapie.",
    "Shows nicknames of all players in the game within the top bar.": "Pokazuje pseudonimy wszystkich graczy w grze na górnym pasku.",
    "Shows raw FPS count.": "Pokazuje liczbę klatek na sekunde (FPS)",
    "Shows real time tick information, mostly useless.": "Pokazuje informacje o tickach w czasie rzeczywistym, w większości bezużyteczne.",
    "Shows relative elevation difference between you and players.": "Pokazuje względną różnicę wysokości między tobą a graczami.",
    "Shows the angle degrees and ticks.": "Pokazuje stopnie i podziałkę na kompasie.",
    "Shows the individual player souls per minute on scoreboard and the team in the top bar.": "Pokazuje liczbę dusz na minutę poszczególnych graczy oraz drużyny na tablicy wyników na górnym pasku.",
    "Shows the individual player's objective damage in the top bar.": "Pokazuje obrażenia zadane celom poszczególnych graczy.",
    "Shows the individual player's unspent souls in the top bar.": "Pokazuje niewydane dusze danego gracza na górnym pasku.",
    "Shows your build information always for content creators": "Zawsze pokazuje informacje o twoim buildzie, przydatne dla twórców",
    "Shows your character in the shop menu.": "Pokazuje twoją postać w menu sklepu.",
    "Shrink Distance": "Odległość Zmniejszania się Ikon",
    "Significantly improve visibility of target reticle and highlight for execute ranges (Shiv).": "Znacząco popraw widoczność wskaźnika celu dla odległości egzekucji (Shiv).",
    "Simplified Minimap": "Uproszczona Minimapa",
    "Simplifies the Compass overlay to its bare elements.": "Upraszcza nakładkę Kompasu do surowych elementów.",
    "Simplify": "Uprość",
    "Simplify Ability Icons": "Uprość Ikony Umiejętności",
    "Simplify Items": "Uprość Przedmioty",
    "Simplify Shop": "Uprość Sklep",
    "Size": "Rozmiar",
    "Size of your current ammo.": "Rozmiar liczby aktualnej amunicji.",
    "Size of your total ammo.": "Rozmiar liczby całkowitej amunicji.",
    "Slight adjustments to the HUD for better streaming output.": "Niewielkie poprawki HUD w celu lepszego przesyłania strumieniowego.",
    "Small Numbers": "Małe Liczby",
    "Snowball or Poster": "Śnieżka lub Plakat",
    "Souls Per Minute": "Dusze na Minutę",
    "Souls Timer": "Timer Dusz",
    "Spanish": "Hiszpański",
    "Special Thanks": "Specjalne Podziękowania",
    "Speed": "Prędkość",
    "Speed number tracker.": "Wartość Obecnej Prędkości",
    "Spinny Map": "Kręcąca się Mapa",
    "Spinny Mode": "Tryb Kręcenia",
    "Spirit Power: --": "Moc Spirytualna: --",
    "Stamina": "Stamina",
    "Stand": "Pas",
    "Stat Bonuses": "Bonusy do Statystyk",
    "Statistics": "Wydajność",
    "Statlocker": "Statlocker",
    "Stats": "Statystyki",
    "Streak:": "Seria:",
    "Stretch the compass horizontally.": "Rozciągnij kompas w poziomie.",
    "Stretch the compass vertically.": "Rozciągnij kompas w pionie.",
    "Strings may sometimes break between mod versions.": "Ciągi mogą czasami nie działać między wersjami moda.",
    "success": "sukces",
    "Support": "Wsparcie",
    "Support development": "Wspieraj rozwój",
    "Support development by commissioning features or presets.": "Wspieraj rozwój poprzez zlecanie funkcji lub presetów.",
    "SUPPORT THE MOD": "WSPIERAJ MOD",
    "Support the mod - donate via Ko-fi (kofi) to help fund continued development": "Wesprzyj moda - przekaż darowiznę za pośrednictwem Ko-fi (kofi), aby pomóc w finansowaniu dalszego rozwoju",
    "Supporting and Feature Requests": "Wspieranie oraz Prośby o Funkcje",
    "Swap": "Zmień",
    "Switch to the advanced item cooldown mode with in-menu filters.": "Zmień na zaawansowany tryb cooldownów itemów z filtrami",
    "Switching to Skyrunner...": "Przełączanie na Skyrunner...",
    "Tab Zoom": "Przybliżenie pod Tabem",
    "Test": "Test",
    "Test Announcer": "Spiker Testowy",
    "Text": "Tekst",
    "The circle countdown for when you are reloading.": "Okrąg pozostałego czasu przeładowania.",
    "The click hitbox of your pings or clicks, this can help make pings more accurate.": "Hitbox twoich pingów lub kliknięć. Może to pomóc w zwiększeniu dokładności pingów.",
    "The cosmetic ability on your default 5 key, like posters and snowballs.": "Umiejętność kosmetyczna, domyślnie pod klawiszem 5, taka jak plakaty czy śnieżki.",
    "The damage dealt to Trooper minions.": "Obrażenia zadawane Minionom (Szturmowcom)",
    "The displayed language of the settings menu.": "Język menu ustawień.",
    "The distance threshold in which icons will start shrinking. Lower is more accurate positions, higher is easier visibility.": "Próg odległości, przy którym ikony zaczną się zmniejszać. Niższa oznacza dokładniejsze pozycje, wyższa oznacza lepszą widoczność.",
    "The hero you automatically switch to on launch or after saving..": "Domyślny ustawiany bohater po uruchomieniu lub po zapisaniu.",
    "The icon that replaces your crosshair when reloading.": "Ikona, która zastępuje celownik podczas przeładowywania.",
    "The interval in which the sound plays in seconds.": "Częstotliwość odtwarzania dźwięku w sekundach.",
    "The item buying auto queue system in the shop menu.": "System automatycznego dodawania przedmiotów do kolejki zakupu w menu sklepu.",
    "The large cumulative damage number.": "Duża skumulowana liczba obrażeń.",
    "The majority of issues are caused by improper installation or conflicting mods.": "Większość problemów jest spowodowana niewłaściwą instalacją lub sprzecznymi modami.",
    "The mod is <font color=\"#66cc99\">fully functional</font> and <font color=\"#66cc99\">free</font> for all users.": "Mod jest <font color=\"#66cc99\">w pełni funkcjonalny</font> i <font color=\"#66cc99\">bezpłatny</font> dla wszystkich użytkowników.",
    "The popup signifying you are too low on stamina to cast another movement input.": "Wyskakujące okienko informujące, że masz zbyt mało staminy, aby wykonać kolejny ruch specjalny.",
    "The popups that appear when getting a kill or CCing an enemy or healing an ally": "Wyskakujące okienka pojawiające się podczas zabijania, stunowania wroga lub leczenia sojusznika",
    "The size of other players on the minimap.": "Rozmiar innych graczy na minimapie.",
    "The size of yourself on the minimap.": "Rozmiar twojej ikony na minimapie.",
    "The small incremental damage numbers.": "Małe przyrostowe liczby obrażeń.",
    "The small visual icon.": "Mała ikona dusz.",
    "The thickness of the Zipline lines across the map.": "Grubość tyrolki na mapie.",
    "The unsecured text.": "Tekst niezabezpieczonych dusz.",
    "The world background blur effect behind the shop menu.": "Efekt rozmycia tła za menu sklepu.",
    "The world blur and backing strip behind player names in the top bar.": "Rozmycie tła i pasek za nazwami graczy w górnym pasku.",
    "The world blur behind player names in the top bar.": "Rozmycie tła za nazwami graczy w górnym pasku.",
    "Theme": "Motyw",
    "These are easy access to common console commands and are not included in QOL settings.": "Szybki dostęp do przydatnych komend konsolowych. Nie są to opcje moda.",
    "This is a lightweight version with significant FPS improvements but requires a seperate file for filters.": "Jest to lekka wersja ze znaczną poprawą FPSów, ale wymaga osobnego pliku dla filtrów.",
    "This is a mod designed to give you complete freedom over your game.": "Jest to mod zaprojektowany tak, aby dać Ci pełną kontrole nad grą.",
    "This is a way for me to give something back to the supporters.": "To dla mnie sposób, aby dać coś od siebie wspierającym.",
    "This is to switch to the Skyrunner hero (looks like Paradox), your settings are saved in the shop builds. To troubleshoot you can delete these and do a fresh save to fix any settings saving issues.": "Ma to na celu przejście na bohatera Skyrunner (wygląda jak Paradox), twoje ustawienia zostaną zapisane w buildach w sklepie. Aby rozwiązać problem, możesz je usunąć i zrobić świeży zapis, aby rozwiązać problemy z zapisywaniem ustawień.",
    "Tier 1": "Tier 1",
    "Tier 2": "Tier 2",
    "Tier 3": "Tier 3",
    "Time before the announcement happens in seconds.": "Ile czasu przed wydarzeniem ma zostać odtworzone przypomnienie.",
    "Time:": "Czas:",
    "Timed audio reminders from Deadlock For Dummies.": "Przypomnienia dźwiękowe z Deadlock For Dummies.",
    "TIMEOUT": "LIMIT CZASU",
    "Timer": "Częstotliwość",
    "Toggle the hitmarkers when attacking enemies.": "Przełącz znaczniki trafień podczas atakowania wrogów.",
    "Tools for showing and sharing item purchase notifications.": "Narzędzia do wyświetlania i udostępniania powiadomień o zakupie przedmiotów.",
    "Tools for tracking recent item purchases.": "Narzędzia do śledzenia ostatnio zakupionych przedmiotów.",
    "Top Bar": "Górny Pasek",
    "Top Bar Background": "Tło Górnego Paska",
    "Top Bar Plus": "Górny Pasek Plus",
    "Total": "Całkowita",
    "Total ammo amount.": "Całkowita ilość amunicji.",
    "Total Size": "Całkowity Rozmiar",
    "Total:": "Suma:",
    "Total: --": "Całkowity: --",
    "Tracked cooldowns near crosshair": "Czasy odnowienia przy celowniku",
    "Translators": "Tłumacze",
    "Trooper Damage": "Obrażenia Minionów",
    "Troubleshoot": "Rozwiązywanie Problemów",
    "Type": "Typ",
    "UI": "UI",
    "UI Controls": "Sterowanie UI",
    "Ukrainian": "Ukraiński",
    "Ult Cooldowns": "Czasy Odnowienia Superumiejętności",
    "Ult Indicator": "Wskaźnik Superumiejętności",
    "Unsecured Plus": "Niezabezpieczone Plus",
    "Unsecured Souls": "Niezabezpieczone Dusze",
    "Unsecured Souls Timer": "Timer Niezabezpieczonych Dusz",
    "Unsecured Timer": "Timer Niezabezpieczonych",
    "Unspent Souls": "Niewydane Dusze",
    "Urn Colors": "Kolory Urny",
    "Urn Difference": "Różnica Urny",
    "Use autoexec or other methods to load these automatically.": "Użyj autoexec lub innych sposobów, aby załadować je automatycznie.",
    "V2 enemy healthbar enhancements.": "Ulepszenia paska zdrowia wrogów V2.",
    "Vertical Offset": "Przesunięcie Pionowe",
    "Vertical Stretch": "Rozciągnięcie Pionowe",
    "View a cooldown timer for reloading time.": "Wyświetl licznik czasu przeładowania.",
    "View an enhanced minimap on opening ability menu.": "Zobacz ulepszoną minimapę w menu umiejętności.",
    "View an enhanced minimap on opening scoreboard menu.": "Zobacz ulepszoną minimapę po otwarciu tablicy wyników.",
    "View the cooldown time of player ultimates.": "Zobacz czas odnowienia superumiejętności gracza.",
    "View updates": "Zobacz aktualizacje",
    "Visual": "Wizualna",
    "Visual indicator of your current ammo.": "Wizualny wskaźnik aktualnej amunicji.",
    "Voice": "Głos",
    "Voice Actor:": "Aktor Głosowy:",
    "Volume": "Głośność",
    "Volume for Deadlock For Dummies reminder audio.": "Głośność dźwięków przypomnień Deadlock For Dummies.",
    "warning": "ostrzeżenie",
    "Weapon Damage %: --": "% Obrażeń Broni: --",
    "Welcome to QOL Lock": "Witamy w QOL Lock",
    "Which events cause a sound to play. Camps are one time, Buff is every 5 minutes.": "Które zdarzenia powodują odtworzenie dźwięku. Dla potworów dźwięki są jednorazowe, dla wzmocnień mostowych grają co 5 minut.",
    "Without them QOL Lock would not be possible.": "Bez nich QOL Lock nie byłby możliwy.",
    "Wraithjack": "WraithJack",
    "Writing settings string to build...": "Zapisywanie ciągu ustawień do builda...",
    "XQC": "XQC",
    "yoshii pls hire me": "yoshii zatrudnij mnie, proszę",
    "You can download custom announcer packs, just download the correct one for the slot you want to replace.": "Możesz pobrać niestandardowe pakiety komentatorów, po prostu pobierz odpowiedni dla slotu, który chcesz zastąpić.",
    "You can support development by commissioning features or presets.": "Możesz wspierać rozwój, zlecając funkcje lub presety.",
    "You win.": "Wygrywasz.",
    "Zerggy Mania": "Zerggy Mania",
    "ZIP BOOST": "WZMOCNIENIE TYROLKI",
    "Zip Boost": "Wzmocnienie Tyrolki",
    "Zip Thickness": "Grubość Tyrolki",
    "Zipline Boost": "Wzmocnienie Tyrolki",
    "Ability Duration": "Czas trwania umiejętności",
    "Ability Range": "Zasięg umiejętności",
    "Bullet Evasion": "Unik przed pociskami",
    "Bullet Lifesteal": "Kradzież życia z pocisków",
    "Bullet Resist": "Odporność na pociski",
    "Clip Size": "Rozmiar magazynka",
    "Damage Amp": "Wzmocnienie obrażeń",
    "Fire Rate": "Szybkostrzelność",
    "Healing Amp": "Wzmocnienie leczenia",
    "Health Regen": "Regeneracja zdrowia",
    "Move Speed": "Prędkość ruchu",
    "Reset settings:": "Zresetuj ustawienia:",
    "Spirit Lifesteal": "Kradzież życia ze spirytu",
    "Spirit Power": "Moc spirytu",
    "Spirit Resist": "Odporność na spiryt",
    "The line has been reset (": "Wiersz został zresetowany (",
    "This line is already on by default.": "Ten wiersz jest już domyślnie włączony.",
    "This section is already on by default.": "Ta sekcja jest już domyślnie włączona.",
    "Visible Stats": "Widoczne statystyki",
    "Weapon Power": "Moc broni",
    "25%": "25%",
    "65%": "65%",
    "75%": "75%",
    "Active Stats": "Aktywne Statystyki",
    "Alert Threshold": "Próg Alertu",
    "Automatically selects 'With Party' in lane preference. Requires the party screen to be open.": "Automatycznie wybiera \"Z Drużyną\" w preferencjach linii. Wymaga otwartego ekranu drużyny.",
    "Console alert when any feature exceeds this ms threshold.": "Alert w konsoli, gdy dowolna funkcja przekroczy ten próg w ms.",
    "Controls how many enhanced quickbuy preview items are shown.": "Określa, ile przedmiotów podglądu ulepszonego szybkiego zakupu jest pokazywanych.",
    "Customize the position of the Player Stats panel, or hide it completely.": "Dostosuj pozycję panelu Statystyk Gracza lub ukryj go całkowicie.",
    "Damage Impact": "Wpływ Obrażeń",
    "Detailed Console": "Szczegółowa Konsola",
    "Dev": "Dev",
    "Diagnostics": "Diagnostyka",
    "Enable performance tracking (required for overlay).": "Włącz śledzenie wydajności (required for overlay).",
    "Enhanced": "Ulepszony",
    "Enhanced Count": "Liczba Ulepszonych",
    "Estimated Active Reload Timer": "Szacowany Timer Aktywnego Przeładowania",
    "Feature Test": "Test Funkcji",
    "Hide in normal view": "Ukryj w normalnym widoku",
    "Hide on scoreboard (TAB)": "Ukryj na tablicy wyników (TAB)",
    "Hide the bottom-left active stats block during normal play. It stays in the HUD (just made invisible), so the Crosshair Active Stats mirror keeps working.": "Ukrywa blok aktywnych statystyk w lewym dolnym rogu podczas normalnej rozgrywki. Pozostaje on w HUD (jedynie staje się niewidoczny), więc lustrzane odbicie Aktywnych Statystyk przy Celowniku nadal działa.",
    "Hide the detailed stats list that appears while the scoreboard / TAB is held.": "Ukrywa szczegółową listę statystyk, która pojawia się przy przytrzymaniu tablicy wyników / TAB.",
    "Hint Size": "Rozmiar Podpowiedzi",
    "Item Buy Notifications": "Powiadomienia o Zakupie Przedmiotów",
    "Items": "Przedmioty",
    "Left": "Lewa",
    "MOG": "MOG",
    "MOGLOCK": "MOGLOCK",
    "Minimalistic Pause": "Minimalistyczna Pauza",
    "Mirror active buffs/debuffs vertically next to the crosshair so they are visible mid-fight.": "Lustrzanie odbij aktywne wzmocnienia/osłabienia pionowo obok celownika, aby były widoczne w trakcie walki.",
    "On Bridge": "Na Moście",
    "On Mid Boss": "Przy Mid Bossie",
    "Only simplifies the shop stats display.": "Upraszcza tylko wyświetlanie statystyk w sklepie.",
    "Opacity of the performance overlay panel.": "Przezroczystość panelu nakładki wydajności.",
    "Overlay Opacity": "Przezroczystość Nakładki",
    "Per-Hero Popups": "Wyskakujące Okienka przy Bohaterach",
    "Perf Debug": "Debug Wydajności",
    "Performance": "Wydajność",
    "Pin the stats panel to the left (default, like vanilla) or right side of the screen.": "Przypnij panel statystyk do lewej (domyślnie, jak w wersji podstawowej) lub prawej strony ekranu.",
    "Player Stats": "Statystyki Gracza",
    "Preset Cycle": "Cykl Presetów",
    "Recent Purchases": "Ostatnie Zakupy",
    "Rejuvenator": "Odnawiacz",
    "Remind when urn, bridge buffs, and gold statue upgrades are spawning.": "Przypomnij, kiedy pojawiają się urna, wzmocnienia mostowe oraz ulepszenia złotych posągów.",
    "Right": "Prawa",
    "Rotate Magazine": "Obróć Magazynek",
    "Rotate the ammo magazine visualiser.": "Obróć wizualizację magazynka amunicji.",
    "Scoreboard": "Tablica Wyników",
    "See your view angle.": "Sprawdź swój kąt widzenia.",
    "Settings": "Ustawienia",
    "Show Buffs": "Pokaż Wzmocnienia",
    "Show Build ID": "Pokaż ID Builda",
    "Show Debuffs": "Pokaż Osłabienia",
    "Show Overlay": "Pokaż Nakładkę",
    "Show Player Ranks": "Pokaż Rangi Graczy",
    "Show active buffs/debuffs (firerate, slow, antiheal...) vertically next to the crosshair": "Pokaż aktywne wzmocnienia/osłabienia (szybkostrzelność, spowolnienie, antyleczenie...) pionowo obok celownika",
    "Show full feature breakdown in console every 5s.": "Pokaż pełny rozkład funkcji w konsoli co 5s.",
    "Show negative modifiers (slow, antiheal, fire rate reduction...) next to the crosshair.": "Pokaż negatywne modyfikatory (spowolnienie, antyleczenie, redukcja szybkostrzelności...) obok celownika.",
    "Show positive modifiers (resistances, fire rate, lifesteal...) next to the crosshair.": "Pokaż pozytywne modyfikatory (odporności, szybkostrzelność, kradzież życia...) obok celownika.",
    "Show purchase notifications under each hero's portrait instead of in the center.": "Pokaż powiadomienia o zakupach pod portretem każdego bohatera zamiast na środku.",
    "Show rank prediction badges on top bar and escape menu player list.": "Pokaż odznaki przewidywanej rangi na górnym pasku oraz na liście graczy w menu Escape.",
    "Show rank prediction badges on top bar player panels (requires Show Player Ranks).": "Pokaż odznaki przewidywanej rangi na panelach graczy na górnym pasku (wymaga Pokaż Rangi Graczy).",
    "Show standalone movement speed.": "Pokaż osobną prędkość ruchu.",
    "Show the performance overlay HUD in-game.": "Pokaż nakładkę HUD wydajności w grze.",
    "Shows a countdown timer in the top bar for the next urn spawn or relocation.": "Pokazuje na górnym pasku timer odliczający do następnego pojawienia się lub przeniesienia urny.",
    "Side": "Strona",
    "Souls": "Dusze",
    "Urn Timer": "Timer Urny",
    "Use the compact minimalistic pause screen instead of the default large one.": "Użyj kompaktowego, minimalistycznego ekranu pauzy zamiast domyślnego dużego.",
    "Whack a Rem": "Pacnij Rema",
    "Amber": "Bursztynowy",
    "Big Camps + Sinners": "Duże Potwory + Kasyna",
    "Black": "Czarny",
    "Blue": "Niebieski",
    "Brown": "Brązowy",
    "Charcoal": "Grafitowy",
    "Coral": "Koralowy",
    "Crimson": "Karmazynowy",
    "Cyan": "Cyjan",
    "Gold": "Złoty",
    "Green": "Zielony",
    "Ice": "Lodowy",
    "Indigo": "Indygo",
    "Lane Guardian Weak": "Słaby Strażnik Liniowy",
    "Lavender": "Lawendowy",
    "Lime": "Limonkowy",
    "Magenta": "Magenta",
    "Medium Camps": "Średnie Potwory",
    "Mint": "Miętowy",
    "Orange": "Pomarańczowy",
    "Pink": "Różowy",
    "Poison": "Trujący",
    "Purple": "Purpurowy",
    "Red": "Czerwony",
    "Rose": "Różany",
    "Rune + Fast Troopers": "Wzmocnienia Mostowe + Szybkie Miniony",
    "Rune + Gold Buffs": "Wzmocnienia Mostowe + Złote Posągi",
    "Rune + Melee Troopers": "Wzmocnienia Mostowe + Miniony Wręcz",
    "Rune + Troopers 20s HP": "Wzmocnienia Mostowe + Miniony 20s HP",
    "Silver": "Srebrny",
    "Sky": "Błękitny",
    "Small Camps + Boxes": "Małe Potwory + Pudła",
    "Teal": "Morski",
    "Urn + Gold Rune": "Urna + Złote Posągi",
    "Violet": "Fioletowy",
    "Void": "Otchłań",
    "Walker Weak": "Słaby Stąpacz",
    "White": "Biały",
    "Yellow": "Żółty"
};
})();
