// ql_settings_loc_ru.js — QOLLOCK settings locale (ru)
// Extracted from ql_settings.js, Phase 1
(function() {
    'use strict';
    var _root = (typeof globalThis !== "undefined") ? globalThis : (typeof window !== "undefined") ? window : {};
    if (!_root.SETTINGS_LOCALE_TEXT) _root.SETTINGS_LOCALE_TEXT = {};
    _root.SETTINGS_LOCALE_TEXT["ru"] = {
    "Benchmark (Current Config)": "Бенчмарк (текущие настройки)",
    "Measure Scheduler polls and FindChildTraverse calls for 10 seconds with current settings. Native panel visits and FPS are unavailable.": "За 10 секунд измеряет вызовы Scheduler и FindChildTraverse с текущими настройками. Число панелей, просмотренных движком, и FPS недоступны.",
    "Run Current (10s)": "Запустить (10 с)",
    "Fixed Icon Size": "Фиксированный размер иконок",
    "Resizes the minimap using width and height instead of scaling the whole HUD. Applies to Base, Alt and Tab views.": "Изменяет ширину и высоту миникарты вместо масштабирования всего HUD. Применяется в обычном режиме, с Alt и Tab.",
    "<font color=\"#66cc99\">Free</font> updates for new features, <font color=\"#66cc99\">$5</font> for arbitrary changes": "<font color=\"#66cc99\">Бесплатные</font> изменения для новых функций, <font color=\"#66cc99\">$5</font> за произвольные правки",
    "16:10 Support": "Поддержка 16:10",
    "1st": "1-й",
    "21:9 Stream Fix": "Фикс 21:9 для стримов",
    "2nd": "2-й",
    "3rd": "3-й",
    "4:3 Support": "Поддержка 4:3",
    "Ability Cooldown %: --": "Время восстановления способности, %: --",
    "Ability Menu Open": "Открыто меню скиллов",
    "Ability Points (AP)": "Очки способностей (AP)",
    "Select an element on the HUD or in the list.": "Выберите элемент на HUD или в списке.",
    "Drag to move. Pull the any corner to resize.": "Перетащите для перемещения. Потяните любой угол для изменения размера.",
    "Drag to move.": "Перетащите для перемещения.",
    "Pull the any corner to resize.": "Потяните любой угол для изменения размера.",
    "This element is edited with the controls below.": "Этот элемент настраивается с помощью полей ниже.",
    "Color is shared with Bottom Bar. Position follows the native parent.": "Цвет общий с нижней панелью. Положение задаётся родительской панелью HUD.",
    "Drag this corner to resize.": "Потяните этот угол для изменения размера.",
    "Color is shared with Bottom Bar. This element has no placement settings yet.": "Цвет общий с нижней панелью. Настроек положения у этого элемента пока нет.",
    "Ability Suggestion": "Рекомендация способности",
    "Accent Color": "Акцентный цвет",
    "Accuracy:": "Точность:",
    "actionbutton": "кнопка действия",
    "Addons": "Аддоны",
    "Adds a STAT button on profile rows that opens Statlocker for that account.": "Добавляет кнопку STAT в профиль и открывает Statlocker этого игрока.",
    "Adjust horizontal position of the in-game chat.": "Настраивает горизонтальное положение игрового чата.",
    "Adjust horizontal position of the player healthbar.": "Изменяет горизонтальное положение панели здоровья игрока.",
    "Adjust opacity of the player healthbar.": "Изменяет прозрачность панели здоровья игрока.",
    "Adjust size of the in-game chat.": "Настраивает размер игрового чата.",
    "Adjust size of the player healthbar.": "Изменяет размер панели здоровья игрока.",
    "Adjust the in-game chat position and scale.": "Настраивает позицию и масштаб игрового чата.",
    "Adjust vertical position of the in-game chat.": "Настраивает вертикальное положение игрового чата.",
    "Adjust vertical position of the player healthbar.": "Изменяет вертикальное положение панели здоровья игрока.",
    "Advanced": "Расширенный",
    "Advanced Filter": "Расширенный фильтр",
    "Advanced Mode": "Расширенный режим",
    "Skyrunner switch sent.": "Запрос на смену героя на Skyrunner",
    "All commissioned additions are released publicly and available to everyone.": "Все заказанные изменения добавляются в публичную версию и доступны всем.",
    "Allows you to drag move some menus.": "Позволяет перетаскивать некоторые меню.",
    "Ally HP Warning": "Предупреждение о ХП союзников",
    "Already at default value.": "Уже по умолчанию.",
    "Alt Zoom": "Зум миникарты на ALT",
    "Always Hidden": "Всегда скрыто",
    "Always Shown": "Всегда показано",
    "Always Visible Boost": "Всегда видно ускорение",
    "Always Visible Override": "Принудительно показывать",
    "Ammo": "Боезапас",
    "An always visible zipline boost overlay.": "Постоянно отображаемый оверлей буста зиплайна.",
    "Angle and Speed": "Угол и скорость",
    "Announcer": "Озвучка событий",
    "Append the selected build title after the build ID.": "Показать название сборки после ID",
    "APPLIED": "ПРИМЕНЕНО",
    "APPLY": "ПРИМЕНИТЬ",
    "Arcade": "Аркада",
    "Asmon": "Asmon",
    "Audio": "Аудио",
    "Author:": "Автор:",
    "Automatically selects Lane Preference: With Party for matchmaking.": "Автоматически выбирает предпочтение линии: с группой.",
    "Backup & Restore": "Резервное копирование и восстановление",
    "Base": "База",
    "Be conscious of the features you are using and read carefully.": "Изучайте функции которые вы используете и внимательно читайте их описание.",
    "Bebop Sweeper": "Bebop Sweeper",
    "Beep": "Beep",
    "Behavior Summary": "Плашка поведения",
    "Best:": "Лучший:",
    "Better Item Cooldowns": "Улучшенные перезарядки предметов",
    "Better Unsecured": "Улучшенные ненадежные души",
    "Better Unsecured Souls": "Улучшенные ненадежные души",
    "BHOP UI": "Интерфейс для BHOP'a",
    "Big Number": "Большие числа",
    "Big Numbers": "Большие числа",
    "Big Red": "Большой и красный",
    "Blackjack": "Blackjack",
    "Blackjack - You win.": "Blackjack – Вы выиграли.",
    "Blur": "Размытие",
    "Boom. Press New Game.": "Бум. Нажмите «Новая игра».",
    "Bottom Bar": "Нижняя панель",
    "BR Portuguese": "БР Португальский",
    "Bridge Buff": "Руна",
    "Bridge Buff Delay": "Время до напоминания о рунах",
    "Bridge Buff Timer": "Таймер рун",
    "Bridge Buffs": "Руны",
    "Budhud": "Budhud",
    "Buff": "Бафф",
    "Buff Delay": "Задержка баффа",
    "Buff Filter": "Фильтр баффов",
    "Buff Reminder": "Напоминание о рунах",
    "Buff Timer": "Таймер рун",
    "Bulgarian": "Болгарский",
    "Bust - Dealer wins.": "Перебор – победа дилера.",
    "By default everything is disabled and has nearly zero performance cost.": "По умолчанию - все ОТКЛЮЧЕНО и ПОЧТИ не влияет на производительность.",
    "Cancel": "Отменить",
    "Captions": "Подписи",
    "Check for new QOLLOCK releases when opening settings.": "Проверять наличие новых версий QOLLOCK при открытии настроек.",
    "Centered ESC Menu": "Отцентровать меню паузы",
    "Centered Friends List": "Отцентровать список друзей",
    "Centers ESC menu elements to make them easier to access.": "Центрирует элементы меню ESC для более удобного доступа.",
    "Centers friends list area in ESC menu.": "Перемещает список друзей в ESC ближе к центру.",
    "Centers the friends list area within the ESC menu.": "Отцентровывает список друзей в ESC",
    "Change Log": "Список изменений",
    "CHANGE LOG": "СПИСОК ИЗМЕНЕНИЙ",
    "Changes the element's transparency.": "Изменяет прозрачность элемента",
    "Changes the visual theme used by the settings menu, modals, loader, and save menus.": "Изменяет визуальную тему мода.",
    "Changes urn color to know which side is favored, green for your team, red for the enemy.": "Перекрашивает урну в зависимости от перевеса команд.",
    "Changes:": "Изменения:",
    "Chat": "Чат",
    "Check out our site to join": "Посетите наш сайт, чтобы присоединиться",
    "Chinese": "Китайский",
    "Choose a preset accent color for the player healthbar frame.": "Выберите пресет цвета для рамки панели здоровья игрока.",
    "Choose a preset border color for stamina charge indicators.": "Выберите пресет цвета рамки для панели выносливости.",
    "Choose a preset color wash for minimap icons.": "Выберите пресет цветов для значков мини-карты.",
    "Choose a preset color wash for the bottom ability bar.": "Выберите пресет цветов для нижней панели способностей.",
    "Choose a preset color wash for the item bar.": "Выберите пресет цветов для панели предметов.",
    "Choose a preset color wash for the keyboard overlay.": "Выберите пресет цветов для оверлея клавиатуры.",
    "Choose a preset text color for the ammo display.": "Выберите пресет цвета текста отображения боеприпасов.",
    "Choose which bridge buff sound variants can play.": "Выберите, какие варианты звука руны могут воспроизводиться.",
    "Circle": "Круг",
    "Clean Indicators": "Чистые индикаторы",
    "Clean Stacks": "Чистые стаки",
    "Cleaner Items": "Убрать фон у предметов",
    "Cleaner Skills": "Убрать фон способностей",
    "Cleans up the styling of reticle hints.": "Улучшает стиль подсказок прицела.",
    "Cleans up the visuals of the shop stats display without changing the rest of the shop.": "Очищает визуальное отображение статистики магазина, не изменяя остальную часть магазина.",
    "Cleans up visuals of abilities significantly to reduce clutter.": "Сильно упрощает визуал способностей, уменьшая перегрузку.",
    "Cleans up visuals of the item bar significantly to reduce clutter.": "Сильно упрощает визуал панели предметов, уменьшая перегрузку.",
    "Cleans up visuals of the minimap significantly to reduce clutter.": "Сильно упрощает визуал миникарты, уменьшая перегрузку.",
    "Cleans up visuals of the shop menu significantly to reduce clutter.": "Сильно упрощает визуал магазина, уменьшая перегрузку.",
    "CLEAR": "ОЧИСТИТЬ",
    "Clear completed.": "Очистка завершена.",
    "Clear failed.": "Очистка не удалась.",
    "Clear in progress...": "Идёт очистка...",
    "Clear timed out. Try again.": "Очистка не вернула ответ вовремя. Попробуйте ещё раз.",
    "CLEARED": "ОЧИЩЕНО",
    "Cleared in": "Очищено за",
    "Clearing builds...": "Очищаем билды...",
    "click here": "Нажмите сюда",
    "Click Radius": "Радиус клика",
    "Click to Notify": "Уведомить команду о недостатке душ",
    "Clip Size % Increase: --": "Увеличение размера магазина в %: --",
    "Clipboard copy failed.": "Копирование в буфер обмена не удалось.",
    "Color": "Цвет",
    "Color Warning": "Цветовое предупреждение",
    "Colored ally top-bar health warnings when at significant thresholds.": "Изменение цвета здоровья союзников на верхней панели при достижении выбранных порогов.",
    "Colored enemy healthbar warnings when at significant thresholds.": "Цветовые предупреждения по HP врага на важных порогах.",
    "Colored enemy top-bar health warnings when at significant thresholds.": "Изменение цвета здоровья противника на верхней панели при достижении выбранных порогов.",
    "Colored Health": "Цветное здоровье",
    "Colored Healthbar": "Цветная полоска HP",
    "Colored healthbar warnings when at significant thresholds.": "Цветовые предупреждения полосы здоровья на важных порогах.",
    "Combat Indicator": "Индикатор боя",
    "Combat Status": "Состояние боя",
    "Commission": "Заказать",
    "Community acknowledgements": "Благодарности сообществу",
    "Compact Layout": "Компактный вид",
    "Compass": "Компас",
    "Compass & Speed": "Компас и скорость",
    "Config": "Конфиг",
    "Confirm": "Подтвердить",
    "Confirming Skyrunner for clear...": "Проверка Skyrunner для чистки...",
    "Console": "Консоль",
    "Console Notes": "Примечания к консоли",
    "Contact": "Связаться",
    "Contributors": "Помощники",
    "COPIED": "СКОПИРОВАНО",
    "COPY": "СКОПИРОВАТЬ",
    "Cosmetic Ability": "Ивентовые способности",
    "Crashed. Click playfield to restart.": "Разбился. Нажмите на игровое поле, чтобы начать заново.",
    "Crate Overlay": "Отображение ящиков",
    "Created By": "Авторство:",
    "Created By:": "Авторство:",
    "Credits": "Особая благодарность",
    "Crosshair": "Прицел",
    "Current": "Текущее кол-во",
    "Current ammo inside of your magazine.": "Текущее количество патронов в магазине.",
    "Current Size": "Размер текущего",
    "Custom": "Кастомный",
    "Custom Preset Commission: <font color=\"#66cc99\">$25</font>": "Заказ персонального пресета: <font color=\"#66cc99\">$25</font>",
    "Customizable Unsecured Souls": "Настраиваемые ненадежные души",
    "Customize the styling of damage numbers.": "Настраивает стиль чисел урона.",
    "Customize the visuals of the incoming damage panel.": "Настраивает внешний вид панели входящего урона.",
    "Customize unsecured souls visuals.": "Настраивает внешний вид ненадёжных душ.",
    "Customize visibility of target reticle when abilities or items visually show on allies and enemies.": "Настраивает видимость ромба-цели, когда способности или предметы отображаются на союзниках и врагах.",
    "Customized healthbars for better visibility or flair.": "Кастомные полосы здоровья для лучшей читаемости и стиля.",
    "Damage Fountain": "Эффект фонтана на урон",
    "Damage Numbers": "Числа урона",
    "Damage Report": "Отчет урона",
    "DAMAGE REPORT": "ОТЧЕТ О ПОВРЕЖДЕНИЯХ",
    "Dealer": "Дилер",
    "Dealer blackjack.": "Дилерский блэкджек.",
    "Dealer busts - You win.": "Дилер перебрал – вы выиграли.",
    "Dealer wins.": "Дилер выигрывает.",
    "Decide what style of item to display the cooldown of.": "Выберите, какие типы предметов показывать в кулдаунах.",
    "Deck:": "Рука:",
    "Default": "По умолчанию",
    "Default 18": "По умолчанию 18",
    "Default 400": "По умолчанию 400",
    "Default difficulty when opening games.": "Сложность по умолчанию при открытии игр.",
    "Default Hero": "Герой по умолчанию",
    "Defensive Active": "Оборонительные активные",
    "Defensive Passive": "Оборонительные пассивные",
    "Depending on complexity and work involved": "Зависит от сложности и объема работ",
    "Depending on complexity and work involved, contact me on": "В зависимости от сложности и объема работ, свяжитесь со мной в",
    "Difficulty": "Сложность",
    "Ding to Check Minimap": "Звуковое напоминание о миникарте",
    "Disabled": "Отключено",
    "Discord": "Discord",
    "DISCORD": "DISCORD",
    "Discord: <font color=\"#66cc99\">civocivocivo</font>": "Discord: <font color=\"#66cc99\">civocivocivo</font>",
    "Display Hero": "Показать героя",
    "Display Stats": "Показать статистику героя",
    "DO NOT PRESS ANY KEYS UNTIL COMPLETE UNLESS PROMPTED": "НЕ НАЖИМАЙТЕ КЛАВИШИ ДО ЗАВЕРШЕНИЯ ЕСЛИ НЕ БЫЛО ЗАПРОСОВ НА ЭТО",
    "Download": "Скачать",
    "Drag": "Перетаскивать",
    "Draggable UI": "перетаскиваемый интерфейс",
    "Draw Over UI": "Рисовать поверх интерфейса",
    "Draws the minimap over all other UI elements for improved visibility.": "Рисует миникарту поверх всех элементов интерфейса для лучшей видимости.",
    "dropdown": "падать",
    "Duration": "Продолжительность",
    "Easier Access": "Облегченный доступ",
    "Easy": "Легкий",
    "Elevation Markers": "Маркеры высоты",
    "en": "en",
    "Enable": "Включить",
    "Enable sounds in arcade games.": "Включите звуки в аркадных играх.",
    "Enabled": "Включено",
    "Enemy": "Враг",
    "Enemy healthbar enhancements.": "Улучшения полосы здоровья врага.",
    "Enemy HP Warning": "Предупреждение о ХП врагов",
    "English": "Английский",
    "Enhanced V2 enemy healthbar visuals and readability.": "Улучшенный стиль полосок здоровья v2",
    "error": "ошибка",
    "ERROR: Invalid String": "ОШИБКА: Неверная строка",
    "Estimated ult cooldowns under top-bar ult icons": "Примерный КД ультов под иконками игроков",
    "Export Settings": "Экспорт настроек",
    "Export String": "Строка экспорта",
    "Export string copied.": "Строка экспорта скопирована.",
    "F": "F",
    "FAILED": "ОШИБКА",
    "Failed Hint": "Уведомления выносливости",
    "Failed to queue save request.": "Ошибка при добавлении сохранения в очередь.",
    "Failed to switch hero.": "Не удалось поменять героя.",
    "Fighting Game": "Fighting Game",
    "Filters": "Фильтры",
    "Find all safe tiles. Right-click to flag.": "Найдите все безопасные плитки. Щелкните правой кнопкой мыши, чтобы отметить.",
    "Fire Rate: --": "Скорострельность: --",
    "First Spawns": "Первые спавны",
    "Flags:": "Флаги:",
    "Flappy Bat": "Flappy Bat",
    "Flip": "Подбросить",
    "For custom BHop gamemode UI changes.": "Изменения интерфейса для кастомных BHop серверов.",
    "Force Testing Tools": "Всегда показывать Debug инструменты",
    "Forcibly hides testing tools at all times.": "Принудительно скрывает инструменты тестирования всегда.",
    "Forcibly shows testing tools at all times.": "Принудительно показывает инструменты тестирования всегда.",
    "Fountain-style damage number animation.": "Стиль урона, в котором числа вылетают как фонтан.",
    "FPS Impact:": "Влияние на FPS:",
    "French": "Французский",
    "Full Keybinds": "Полная раскладка",
    "Full Keys": "Полные клавиши",
    "Game Audio": "Звуки игр",
    "Game Settings": "Настройки игр",
    "Gamemodes": "Режимы игры",
    "Games": "Игры",
    "General": "Общее",
    "Get Filter": "Сгенерировать фильтр",
    "Get Filter File Only": "Качайте только файл фильтра",
    "Graves Trainer": "Graves Trainer",
    "Greys out heros in the top bar when missing on the map.": "Затемняет героев на верхней панели, когда они пропали с карты.",
    "Hard": "Тяжелый",
    "Health Numbers": "Цифры здоровья",
    "Healthbar": "Полоса здоровья",
    "Help and feedback": "Помощь и обратная связь",
    "Help fund continued development": "Помогите финансировать дальнейшее развитие",
    "Help, Contact & Support": "Помощь, контакты и поддержка",
    "Help, feedback, and community": "Помощь, обратная связь и сообщество",
    "Hero": "Герой",
    "Hero Icon Size": "Размер иконок героев",
    "Hero on Load or Save": "Герой при загрузке или сохранении",
    "Hide Ability Suggestion": "Скрыть рекомендации способностей",
    "Hide All": "Скрыть все",
    "Hide Behavior Summary": "Скрыть плашку поведения",
    "Hide Big Number": "Скрыть большие числа",
    "Hide Blur": "Убрать размытие",
    "Hide Circle": "Скрыть общее кол-во",
    "Hide Cosmetic Ability": "Скрыть ивентовую способность",
    "Hide Current": "Скрыть текущие",
    "Hide Damage Report": "Скрыть отчет урона",
    "Hide Failed Hint": "Скрыть уведомления выносливости",
    "Hide Icon": "Скрыть иконку",
    "Hide Quick Buy": "Скрыть быструю покупку",
    "Hide Small Numbers": "Скрыть малые числа",
    "Hide Testing Tools": "Скрыть инструменты",
    "Hide Total": "Скрыть общее",
    "Hide Trooper Damage": "Скрыть урон по труперам",
    "High": "Высокая",
    "HIGH FPS IMPACT WARNING!": "ВНИМАНИЕ: ВЫСОКАЯ НАГРУЗКА НА FPS!",
    "Highlight Mode": "Улучшенная видимость",
    "Highlight regeneration in red for when in combat.": "Выделите регенерацию красным цветом в бою.",
    "Highlighted abilities showing you what you should upgrade depending on build.": "Подсвечивает способности, которые стоит улучшать в зависимости от билда.",
    "Hit": "Hit",
    "Hitmarkers": "Хитмаркеры",
    "Hits:": "Хиты:",
    "Horizontal Offset": "Гориз. положение",
    "Horizontal Stretch": "Гориз. размер",
    "How fast the minimap refreshes.": "Частота обновления миникарты.",
    "How much icons will shrink when overlapping with others.": "Насколько иконки сжимаются при перекрытии.",
    "How to Save Settings": "Как сохранить настройки",
    "HP Warning": "Предупреждение о ХП",
    "HUD": "HUD",
    "HUD Controls": "Управление HUD",
    "Hud Shift": "Сдвиг HUD",
    "I am open to all feedback, suggestions, and ideas!": "Я открыт к любым отзывам, предложениям и идеям!",
    "Icon": "Иконка",
    "Icon Shrink": "Сжатие иконок",
    "Icons": "Иконки",
    "If saving stalls, open your shop.": "Если сохранение зависло, откройте магазин.",
    "If you encounter issues please join the Discord": "Если вы столкнулись с проблемами, присоединяйтесь к Discord",
    "If you encounter issues, need help, or have any feedback join the Discord.": "Если возникли проблемы, нужна помощь или есть идеи, присоединяйтесь к Discord.",
    "Images in Chat": "Отображение изображений в чате",
    "Import failed.": "Импорт не удался",
    "Import Settings": "Импорт настроек",
    "Import String": "Строка импорта",
    "Import: applying settings...": "Импорт: применяются настройки...",
    "Import: parsing string...": "Импорт: обработка строки...",
    "Import: refreshing UI...": "Импорт: перезагружается интерфейс...",
    "Improve Ability Stacks": "Улучшает отображение стаков способностей.",
    "Improved Hint": "Улучшенная подсказка",
    "IN COMBAT": "В БОЮ",
    "In Seconds": "В секундах",
    "info": "Информация",
    "Invalid import string.": "Неверный код настроек",
    "Issues, Feedback and Ideas": "Проблемы, отзывы и идеи",
    "Item Cooldowns": "Кулдаун предметов",
    "Item Target Reticle": "Прицел предметов",
    "Japanese": "Японский",
    "Keyboard": "Клавиатура",
    "Klutz's Bar": "Klutz's Bar",
    "Lane with Party": "Лайнинг с группой",
    "Language": "Язык",
    "Latest updates and version notes": "Последние обновления и примечания к версии",
    "Legacy Durations": "Старые длительности способностей",
    "Light Item Cooldowns": "Облегчённые перезарядки предметов",
    "Local settings loaded.": "Локальные настройки загружены.",
    "Loud": "Громко",
    "Low": "Низкая",
    "Low Stamina Popup": "Убирает выскакивающие уведомления о стамине",
    "Makes the minimap rotate with player view, this is just for fun.": "Поворачивает миникарту вместе с направлением игрока, опция забавы ради.",
    "Max Health: --": "Максимальное здоровье: --",
    "Max Notifications": "Максимальное количество уведомлений",
    "Medium": "Средняя",
    "Menu when you receive a punishment for breaking game rules.": "Меню, которое появляется при наказании за нарушение правил игры.",
    "Meta Settings": "Настройки мода",
    "Metro Button": "Функция для Jamside",
    "Mid Boss Timer": "Таймер мид-босса",
    "Midtown-only crate markers on the minimap.": "Показывает ящики стандартной карты на мини-карте.",
    "Mines:": "Мины:",
    "Minimalist": "Минималистичный",
    "Minimalist Abilities": "Минималистичные способности",
    "Minimalist Healthbar": "Маленькая полоска HP",
    "Minimalist Item Bar": "Минималистичная панель предметов",
    "Minimalist Minimap": "Минимал. миникарта",
    "Minimalist Opacity": "Прозрачность минималистичной карты",
    "Minimap": "Миникарта",
    "Minimap Reminder": "Напоминание о миникарте",
    "Mirror unsecured gold number": "Отзеркаливать ненадежные души",
    "Misses:": "Промахи:",
    "Missing Hero Opaque": "Скрыть пропавших героев",
    "Modify damage numbers for a cleaner style and animation to be more out of the way": "Измените цифры урона, чтобы стиль был чище, а анимация была более незаметной.",
    "MOG is Deadlock's first custom gamemode community server network.": "MOG — это первая сеть серверов сообщества Deadlock с пользовательским игровым режимом.",
    "moglock.gg": "moglock.gg",
    "Move ability stacks to bottom-center of ability icon": "Перемещает стаки способностей в старое положение (на способность, с более видимым текстом).",
    "Move ability stacks to bottom-center of ability icon.": "Перемещает стаки способностей в старое положение (на способность, с более видимым текстом).",
    "Move notifications around Rejuvenator and Scoreboard UI.": "Перемещает уведомления вокруг Реджува и TAB интерфейса.",
    "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.": "Перемещает таймер Bridge Buff на мост с двумя меньшими копиями по центру.",
    "Moves the element horizontally.": "Двигает элемент горизонтально",
    "Moves the element vertically.": "Двигает элемент вертикально",
    "Moves the Mid Boss timer onto the bridge area of the minimap.": "Перемещает таймер Мид Босса в область моста на мини-карте.",
    "multitoggle": "мультипереключатель",
    "N/A": "Н/Д",
    "Neutral Camps": "Нейтральные кемпы",
    "New Feature Commission: <font color=\"#66cc99\">$10</font> to <font color=\"#66cc99\">$100</font>": "Заказ новой фичи: <font color=\"#66cc99\">$10</font> до <font color=\"#66cc99\">$100</font>",
    "New Game": "Новая игра",
    "New Hand": "Новая рука",
    "New Run": "Новый забег",
    "Nicknames": "Никнеймы",
    "No color wash": "Без кастомного цвета",
    "No filter settings but better FPS.": "Без настроек фильтров, но с более хорошим FPS",
    "No results found": "Ничего не найдено",
    "No setting changes detected.": "Никаких изменений настроек не обнаружено.",
    "None": "Нет",
    "Normal": "Средне",
    "Notify your teammates in chat about how close you are to a quickbuy purchase.": "Сообщите своим товарищам по команде в чате о том, насколько вы близки к быстрой покупке.",
    "Objective Damage": "Урон по строениям",
    "Objective Map": "Карта строений",
    "Off": "Выкл",
    "Offensive Active": "Агрессивные активные",
    "Offensive Passive": "Агрессивные пассивные",
    "On": "Вкл",
    "On Ability Upgrade": "скрывает рекомендации сборок",
    "On Death": "Показывать во время смерти",
    "On Death Games": "Игры после смерти",
    "Only download the filter file of the filter you want, nothing else.": "Скачивайте только файл нужного фильтра, ничего лишнего.",
    "Opacity": "Прозрачность",
    "Opacity of the background of Minimalist Minimap.": "Прозрачность фона минималистичной миникарты.",
    "Opacity of the underground tunnel overlay while Alt Zoom is active.": "Непрозрачность наложения подземного туннеля при активном Alt Zoom.",
    "Opacity of the underground tunnel overlay while Tab Zoom is active.": "Непрозрачность наложения подземного туннеля при активном Tab Zoom.",
    "Opacity of the underground tunnel overlay.": "Непрозрачность наложения подземного туннеля.",
    "Open": "Открыть",
    "Open Config": "Открыть конфиг",
    "Open random game when dead": "Открывать случайную игру при смерти",
    "Open Settings": "Открыть настройки",
    "Open shop to continue clear.": "Откройте магазин что бы продолжить очистку.",
    "Open shop to continue save.": "Откройте магазин что бы продолжить сохранение.",
    "Optimize Filters": "Фильтры оптимизации",
    "Optimize Mode": "Режим оптимизации",
    "Overlay": "Оверлей",
    "palette": "Палитра",
    "Paste and apply an exported settings string": "Вставить и применить экспортированную строку",
    "Play": "Играть",
    "Play an audio reminder to remember to look at the minimap.": "Проигрывает звуковое напоминание, чтобы не забывать смотреть на миникарту.",
    "Play current announcer voice and volume.": "Проиграть текущий голос и громкость озвучки.",
    "Play current announcer voice.": "Проиграть текущий голос.",
    "Play Sound": "Воспроизвести звук",
    "Play When On Death Enabled": "Играть при смерти включено",
    "Player": "Игрок",
    "Player Icon Size": "Размер иконки игрока",
    "Polish": "Польский",
    "Portuguese": "Португальский",
    "Position and Velocity real time statistics.": "Статистика позиции и скорости в реальном времени.",
    "Preset apply failed.": "Попытка применения пресета не удалась",
    "Presets": "Пресеты",
    "Preview": "Показывать изменения",
    "Preview Announcer": "Прослушать озвучку",
    "Preview Changes": "Предварительный просмотр изменений",
    "Preview realtime changes to settings when modifying them.": "Отображать изменения в реальном времени там, где это возможно",
    "Preview setting changes in realtime.": "Предварительный просмотр изменений настроек в реальном времени.",
    "Push - Both have blackjack.": "Ничья – у обоих блэкджек.",
    "Push.": "Ничья.",
    "Q": "Q",
    "QOL": "QOL",
    "QOL Settings Clearer": "QOL Очистка настроек",
    "QOL Settings Loader": "QOL Загрузчик настроек",
    "QOL Settings Saver": "QOL Сохранение настроек",
    "Quick Buy": "Быстрая покупка",
    "Quiet": "Тихо",
    "Ragnarok Online damage visuals with improved fancy styling.": "Визуал чисел урона в стиле Ragnarok Online с улучшенным оформлением.",
    "RAM and GPU Memory real time usage statistics.": "Статистика использования RAM и видеопамяти в реальном времени.",
    "Randomly opens an enabled arcade game while dead.": "Открывает случайную аркаду из выбранных во время смерти",
    "Ready": "Готовый",
    "Ready.": "Готово.",
    "Real time key input visual.": "Визуализация нажатий клавиш в реальном времени.",
    "Realtime Changes": "Показывает изменения в реальном времени",
    "Realtime Drain Countdown": "Показать время до перехода в чистые души",
    "Realtime Key Inputs": "Нажатия в реальном времени",
    "Realtime Settings Changes": "Отображение изменений настроек в реальном времени",
    "Recommended for 4:3": "Рекомендовано для 4:3",
    "Refresh Rate": "Частота обновления",
    "Reload Cooldown": "Время перезарядки",
    "Reloading": "Перезарядка",
    "Rem Tunnels": "Туннели Рема",
    "Rem Tunnels Opacity": "Непрозрачность туннелей Рема",
    "Remind when big camps and Sinner's Sacrifice are spawning.": "Напомните, когда спавнятся большие лагеря и Sinner's Sacrifice.",
    "Remind when bridge buffs and melee troopers are spawning.": "Напоминайте, когда появляются усилители моста и солдаты ближнего боя.",
    "Remind when bridge buffs are spawning.": "Напоминайте, когда появляются усиления моста.",
    "Remind when bridge buffs spawn and gold statue buffs are maxed.": "Напомните, когда появляются усиления моста и достигаются максимумы усиления золотых статуй.",
    "Remind when bridge buffs spawn and troopers improve again.": "Напомните, когда появятся усиления моста и снова улучшатся солдаты.",
    "Remind when bridge buffs spawn and troopers speed up.": "Напоминайте, когда появляются усиления моста и ускоряются солдаты.",
    "Remind when lane guardian resistance is reduced.": "Напоминайте, когда сопротивление стража на линии снижается.",
    "Remind when medium camps are spawning.": "Напомните, когда спавнятся средние лагеря.",
    "Remind when midboss, urn, bridge buffs, and gold statue upgrades are spawning.": "Напоминайте, когда появляются мидбосс, урна, усиления моста и улучшения золотой статуи.",
    "Remind when small camps, boxes, and statues are spawning.": "Напоминайте, когда появляются небольшие лагеря, ящики и статуи.",
    "Remind when walker resistance is reduced.": "Напомните, когда сопротивление Шагохода снизится.",
    "Render image URLs as images.": "Отображение URL-адресов изображений как изображений.",
    "Replaces quickbuy with the Enhanced Quickbuy standalone layout and queue summaries.": "Заменяет быструю покупку автономным макетом Enhanced Quickbuy и сводками очереди.",
    "Reposition": "Переместить",
    "Request a community preset": "Запросить пресет сообщества",
    "Request a custom feature or preset": "Запросить пользовательскую функцию или предустановку",
    "Reset row to defaults": "Сбросить ряды до изначальных значений",
    "Reset section runtime options": "Сбросить runtime-настройки секции",
    "Reset section to defaults": "Сбросить секцию к значениям по умолчанию",
    "Reset settings:": "Сброшено настройки:",
    "Reset to default value": "Вернуть значение к изначальному",
    "Reset to default value.": "Сброс до значения по умолчанию.",
    "Restores the legacy removed duration bars for abilities.": "Восстанавливает старые полоски каста способностей",
    "Retheme the settings menu, modals, loader, and save menus with a shared aesthetic.": "Измените тему меню настроек, модальных окон, загрузчика и меню сохранения с общей эстетикой.",
    "Rotate": "Поворот",
    "Rotate the stamina charge indicator.": "Поверните индикатор заряда выносливости.",
    "Rotates the static minimap 180 degrees.": "Поворачивает статическую мини-карту на 180 градусов.",
    "Row already at defaults.": "Ряды уже приведены к изначальным значениям",
    "Row reset (": "Сброс строки (",
    "Run complete. Press New Run.": "Бегите полностью. Нажмите «Новый запуск».",
    "Russian": "Русский",
    "SAVE": "СОХРАНИТЬ",
    "Save": "Сохранить",
    "Save completed.": "Сохранение закончено.",
    "Save failed.": "Ошибка сохранения.",
    "Save in progress...": "Сохранение в процессе...",
    "Save queued.": "Сохранение поставлено в очередь.",
    "Save timed out. Try again.": "Сохранение не вернуло ответ вовремя. Попробуйте ещё раз.",
    "Save works only in hideout.": "Сохранение работает только в убежище.",
    "SAVED": "СОХРАНЕНО",
    "Scale": "Масштаб",
    "Scales the element.": "Изменяет размеры элемента.",
    "Score:": "Счет:",
    "Scoreboard Open": "Открыта таблица счёта",
    "Search Results": "Результаты поиска",
    "Seconds Before Spawn": "Секунд до появления",
    "Seconds each notification stays visible.": "Секунды, когда каждое уведомление остается видимым.",
    "Section already at defaults.": "Секция уже имеет изначальные значения.",
    "Section reset (": "Сброс раздела (",
    "See the recent purchases made in the game.": "Посмотрите недавние покупки, сделанные в игре.",
    "See your view angle and speed.": "Показывает угол обзора и скорость.",
    "Settings Changes": "Изменения настроек",
    "Settings now load from your saved build string": "Настройки теперь загружаются из вашей сохраненной строки билда",
    "Settings UI Language": "Язык интерфейса",
    "Share or save your settings configuration!": "Поделитесь или сохраните свои настройки!",
    "Share your settings string": "Поделиться строкой настроек",
    "Shifts the HUD for better visual support for 16:10 resolutions.": "Смещает HUD для лучшей поддержки разрешений 16:10.",
    "Shifts the HUD for better visual support for 4:3 resolutions.": "Смещает HUD для лучшей поддержки разрешений 4:3.",
    "Shop": "Магазин",
    "Show a short caption when Deadlock For Dummies reminders play.": "Показывать короткую подпись при воспроизведении напоминаний Deadlock For Dummies.",
    "Show a visual indicator in the top bar of the current Guardians, Walkers, and Base.": "Показывает индикатор текущих Гвардов, Шагоходов и Базы на верхней панели.",
    "Show an overlay of the underground tunnels.": "Покажите наложение подземных туннелей.",
    "Show Compass": "Показать компас",
    "Show current / max HP numbers over the Minecraft hearts.": "Покажите текущие/максимальные числа HP над сердечками Minecraft.",
    "Show Filters": "Показать фильтры",
    "Show FPS": "Показать FPS",
    "Show Frame": "Показать кадр",
    "Show Icon": "Показать иконку",
    "Show if you are in combat or not.": "Показывает, находитесь ли вы в бою.",
    "Show level text on V2 enemy healthbars.": "Показывать уровень около полосок здоровья v2",
    "Show Memory": "Показать память",
    "Show player ultimate indicators on V1 healthbars.": "Показывает индикаторы ульты игроков на полосах здоровья V1.",
    "Show Position": "Показать позицию",
    "Show Speed": "Показывать скорость",
    "Show Support": "Поддержать разработчика",
    "Show Testing Tools": "Показывать инструменты",
    "Show Text": "Показать текст",
    "Show the estimated time for unsecured souls to dissapear.": "Показывает примерное время до исчезновения ненадёжных душ.",
    "Show the in-game chat panel.": "Показывает игровой чат.",
    "Show the ultimate indicator for V1 healthbars.": "Показывает индикатор ульты для V1-полосок здоровья.",
    "Show the underground tunnel overlay while Alt Zoom is active.": "Покажите наложение подземного туннеля, пока активен Alt Zoom.",
    "Show the underground tunnel overlay while Tab Zoom is active.": "Покажите наложение подземного туннеля, пока активна Tab Zoom.",
    "Show the UnitInfo panel on V2 enemy healthbars.": "Показывать панель UnitInfo с полосками здоровья v2",
    "Show Tick": "Показать тики",
    "Show Title": "Показать заголовок",
    "Showing:": "Показаны:",
    "Shown Items": "Фильтр предметов",
    "Shows a visual indicator in the minimap of when Bridge Buffs will spawn.": "Показывает индикатор на миникарте, когда появятся руны.",
    "Shows a visual indicator in the minimap of when Mid Boss will spawn.": "Показывает индикатор на миникарте, когда появится мид-босс.",
    "Shows a visual indicator in the top bar of the percentage difference of souls between teams.": "Показывает на верхней панели процентную разницу душ между командами.",
    "Shows a visual indicator in the top bar of when Bridge Buffs will spawn.": "Показывает индикатор на верхней панели, когда появятся руны.",
    "Shows a visual indicator in the top bar of when Mid Boss will spawn.": "Показывает индикатор на верхней панели, когда появится мид-босс.",
    "Shows all of your keybinds.": "Показывает все ваши бинды.",
    "Shows all of your player stats within the shop menu.": "Показывает все ваши характеристики игрока в меню магазина.",
    "Shows current frame count, mostly useless.": "Показывает текущий номер кадра, в основном бесполезно.",
    "Shows item buy notifications from recent purchases.": "Показывает уведомления о недавних покупках.",
    "Shows item cooldowns near crosshair for easier readability.": "Показывает кулдауны предметов рядом с прицелом для удобства.",
    "Shows Midtown crate markers in the minimap.": "Показывает маркеры ящиков Мидтауна на мини-карте.",
    "Shows nicknames of all players in the game within the top bar.": "Показывает никнеймы всех игроков на верхней панели.",
    "Shows raw FPS count.": "Показывает текущий FPS.",
    "Shows real time tick information, mostly useless.": "Показывает информацию о тиках в реальном времени, в основном бесполезно.",
    "Shows relative elevation difference between you and players.": "Показывает относительную разницу высот между вами и игроками.",
    "Shows the angle degrees and ticks.": "Показывает градусы угла и тики.",
    "Shows the individual player souls per minute on scoreboard and the team in the top bar.": "Показывает души в минуту для игроков на табло и для команды на верхней панели.",
    "Shows the individual player's objective damage in the top bar.": "Показывает урон по объектам для каждого игрока на верхней панели.",
    "Shows the individual player's unspent souls in the top bar.": "Показывает непотраченные души каждого игрока на верхней панели.",
    "Shows your build information always for content creators": "Всегда показывает информацию о вашей сборке для создателей контента.",
    "Shows your character in the shop menu.": "Показывает вашего героя в меню магазина.",
    "Shrink Distance": "Дистанция сжатия",
    "Significantly improve visibility of target reticle and highlight for execute ranges (Shiv).": "Сильно повышает видимость ромба-цели и подсветки порога добивания (Shiv).",
    "Simplified Minimap": "Упрощенная миникарта",
    "Simplifies the Compass overlay to its bare elements.": "Упрощает оверлей компаса до базовых элементов.",
    "Simplify": "Упрощение",
    "Simplify Ability Icons": "Упростить иконки способностей",
    "Simplify Items": "Упростить интерфейс предметов",
    "Simplify Shop": "Упростить магазин",
    "Size": "Размер",
    "Size of your current ammo.": "Размер текущих патронов.",
    "Size of your total ammo.": "Размер общего количества патронов.",
    "Slight adjustments to the HUD for better streaming output.": "Небольшие сдвиги HUD для более удобного стрим-вывода.",
    "Small Numbers": "Малые числа",
    "Snowball or Poster": "Снежок или постер",
    "Souls Per Minute": "Души в минуту",
    "Souls Timer": "Таймер душ",
    "Spanish": "Испанский",
    "Special Thanks": "Особая благодарность",
    "Speed": "Скорость",
    "Speed number tracker.": "Трекер числового значения скорости.",
    "Spinny Map": "Вращающаяся карта",
    "Spinny Mode": "Режим вращения",
    "Spirit Power: --": "Спиритическая сила: --",
    "Stamina": "Выносливость",
    "Stand": "Stand",
    "Stat Bonuses": "Бонусы к статистике",
    "Statistics": "Статистика",
    "Statlocker": "Statlocker",
    "Stats": "Статы",
    "Streak:": "Полоса:",
    "Stretch the compass horizontally.": "Растягивает компас по горизонтали.",
    "Stretch the compass vertically.": "Растягивает компас по вертикали.",
    "Strings may sometimes break between mod versions.": "Строки настроек могут ломаться после обновлений.",
    "success": "Успех",
    "Support": "Поддержка",
    "Support development": "Поддержка разработки",
    "Support development by commissioning features or presets.": "Поддержите разработку, заказав функции или пресеты.",
    "SUPPORT THE MOD": "ПОДДЕРЖАТЬ МОД",
    "Support the mod - donate via Ko-fi (kofi) to help fund continued development": "Поддержите мод — сделайте пожертвование через Ko-fi (kofi), чтобы помочь финансировать дальнейшую разработку.",
    "Supporting and Feature Requests": "Поддержка и запросы фич",
    "Swap": "Сменить",
    "Switch to the advanced item cooldown mode with in-menu filters.": "Переключитесь в расширенный режим восстановления предметов с помощью фильтров в меню.",
    "Switching to Skyrunner...": "Меняем героя на Skyrunner...",
    "Tab Zoom": "Зум миникарты на TAB",
    "Test": "Тест",
    "Test Announcer": "Тест озвучки",
    "Text": "Текст",
    "The circle countdown for when you are reloading.": "Круговой таймер обратного отсчёта при перезарядке.",
    "The click hitbox of your pings or clicks, this can help make pings more accurate.": "Радиус области клика для пингов и отметок; помогает делать их точнее.",
    "The cosmetic ability on your default 5 key, like posters and snowballs.": "Косметическая способность на клавише 5 по умолчанию, например постеры и снежки.",
    "The damage dealt to Trooper minions.": "Урон, нанесённый крипам-труперам.",
    "The displayed language of the settings menu.": "Язык отображения меню настроек",
    "The distance threshold in which icons will start shrinking. Lower is more accurate positions, higher is easier visibility.": "Дистанция, при которой иконки начинают сжиматься. Меньше — точнее позиции, больше — лучше видимость.",
    "The hero you automatically switch to on launch or after saving..": "Герой, на которого автоматически переключает при запуске или после сохранения.",
    "The icon that replaces your crosshair when reloading.": "Иконка, которая заменяет прицел во время перезарядки.",
    "The interval in which the sound plays in seconds.": "Интервал воспроизведения звука в секундах.",
    "The item buying auto queue system in the shop menu.": "Система автоочереди покупки предметов в меню магазина.",
    "The large cumulative damage number.": "Большое суммарное число урона.",
    "The line has been reset (": "Сброшена строка (",
    "The majority of issues are caused by improper installation or conflicting mods.": "Большинство проблем вызвано неправильной установкой или конфликтующими модами.",
    "The mod is <font color=\"#66cc99\">fully functional</font> and <font color=\"#66cc99\">free</font> for all users.": "Мод <font color=\"#66cc99\">полностью функционален</font> и <font color=\"#66cc99\">бесплатен</font> для всех пользователей.",
    "The popup signifying you are too low on stamina to cast another movement input.": "Всплывающее предупреждение, что у вас слишком мало выносливости для следующего мувмента.",
    "The popups that appear when getting a kill or CCing an enemy or healing an ally": "Всплывающие окна, которые появляются при убийстве, наведении контроля над врагом или исцелении союзника.",
    "The size of other players on the minimap.": "Размер иконок других игроков на миникарте.",
    "The size of yourself on the minimap.": "Размер вашей иконки на миникарте.",
    "The small incremental damage numbers.": "Малые инкрементальные числа урона.",
    "The small visual icon.": "Маленькая визуальная иконка.",
    "The thickness of the Zipline lines across the map.": "Толщина линий зиплайна на миникарте.",
    "The unsecured text.": "Текст ненадёжных душ.",
    "The world background blur effect behind the shop menu.": "Эффект размытия мира на фоне меню магазина.",
    "The world blur and backing strip behind player names in the top bar.": "Размытие мира и фоновая полоса позади имен игроков на верхней панели.",
    "The world blur behind player names in the top bar.": "Мир размывается за именами игроков на верхней панели.",
    "Theme": "Тема",
    "These are easy access to common console commands and are not included in QOL settings.": "Это простой доступ к общим консольным командам, которые не включены в настройки QOL.",
    "This is a lightweight version with significant FPS improvements but requires a seperate file for filters.": "Это лёгкая версия с заметно лучшим FPS, но требуется отдельный файл фильтров.",
    "This is a mod designed to give you complete freedom over your game.": "Этот мод создан, чтобы дать вам полную свободу в игре.",
    "This is a way for me to give something back to the supporters.": "Это способ отблагодарить разработчика мода.",
    "This is to switch to the Skyrunner hero (looks like Paradox), your settings are saved in the shop builds. To troubleshoot you can delete these and do a fresh save to fix any settings saving issues.": "Кнопка для переключения на героя Skyrunner (похож на Lash), ваши настройки сохраняются в сборках магазина. Для устранения неполадок вы можете удалить их и выполнить новое сохранение, чтобы исправить любые проблемы с сохранением настроек.",
    "This line is already on by default.": "Строка уже по умолчанию.",
    "This section is already on by default.": "Секция уже по умолчанию.",
    "Tier 1": "Тир 1",
    "Tier 2": "Тир 2",
    "Tier 3": "Тир 3",
    "Time before the announcement happens in seconds.": "Время до срабатывания уведомления в секундах.",
    "Time:": "Время:",
    "Timed audio reminders from Deadlock For Dummies.": "Звуковые напоминания по времени от Deadlock For Dummies.",
    "TIMEOUT": "ТАЙМ-АУТ",
    "Timer": "Таймер",
    "Toggle the hitmarkers when attacking enemies.": "Включает/выключает хитмаркеры при атаке врагов.",
    "Tools for showing and sharing item purchase notifications.": "Инструменты для отображения и обмена уведомлениями о покупке предметов.",
    "Tools for tracking recent item purchases.": "Инструменты для отслеживания недавних покупок товаров.",
    "Top Bar": "Верхняя панель",
    "Top Bar Background": "Фон верхней панели",
    "Top Bar Plus": "Верхняя панель+",
    "Total": "Общее кол-во",
    "Total ammo amount.": "Общее количество патронов.",
    "Total Size": "Размер общего",
    "Total:": "Общий:",
    "Total: --": "Общий: --",
    "Tracked cooldowns near crosshair": "Отслеживаемые кулдауны у прицела",
    "Translators": "Переводчики",
    "Trooper Damage": "Урон по крипам",
    "Troubleshoot": "Решить неисправность",
    "Type": "Тип",
    "UI": "UI",
    "UI Controls": "Управление UI",
    "Ukrainian": "Украинский",
    "Ult Cooldowns": "Кулдауны ультов",
    "Ult Indicator": "Индикатор ульты",
    "Unsecured Plus": "Улучшенные ненадежные души",
    "Unsecured Souls": "Ненадежные души",
    "Unsecured Souls Timer": "Таймер ненадежных душ",
    "Unsecured Timer": "Таймер ненадежных душ",
    "Unspent Souls": "Непотраченные души игроков",
    "Update Checker": "Проверка обновлений",
    "Urn Colors": "Цвета урны",
    "Urn Difference": "Разница урны",
    "Use autoexec or other methods to load these automatically.": "Используйте autoexec или другие методы для их автоматической загрузки.",
    "V2 enemy healthbar enhancements.": "Улучшения полосок здоровья v2",
    "Vertical Offset": "Верт. положение",
    "Vertical Stretch": "Верт. Размер",
    "View a cooldown timer for reloading time.": "Показывает таймер кулдауна времени перезарядки.",
    "View an enhanced minimap on opening ability menu.": "Показывает расширенную миникарту при открытии меню способностей.",
    "View an enhanced minimap on opening scoreboard menu.": "Показывает расширенную миникарту при открытии табло.",
    "View the cooldown time of player ultimates.": "Показывает время кулдауна ультимейтов игроков.",
    "View updates": "Просмотр обновлений",
    "Visual": "Визуализация патронов",
    "Visual indicator of your current ammo.": "Визуальный индикатор текущих патронов.",
    "Voice": "Голос",
    "Voice Actor:": "Актёр озвучки:",
    "Volume": "Громкость",
    "Volume for Deadlock For Dummies reminder audio.": "Громкость звука напоминания Deadlock For Dummies.",
    "warning": "предупреждение",
    "Weapon Damage %: --": "Урон оружия %: --",
    "Welcome to QOL Lock": "Добро пожаловать в QOL Lock",
    "Which events cause a sound to play. Camps are one time, Buff is every 5 minutes.": "Какие события воспроизводят звук. Крипы — единожды, руны — каждые 5 минут.",
    "Without them QOL Lock would not be possible.": "Без них QOL Lock был бы невозможен.",
    "Wraithjack": "Wraithjack",
    "Writing settings string to build...": "Записываем строку настроек в билд...",
    "XQC": "XQC",
    "yoshii pls hire me": "йоши, пж, найми меня",
    "You can download custom announcer packs, just download the correct one for the slot you want to replace.": "Вы можете скачать кастомные наборы озвучки, просто скачайте правильный для того слота, который хотите заменить.",
    "You can support development by commissioning features or presets.": "Вы можете поддержать разработку, заказав фичи или пресеты.",
    "You win.": "Вы выиграли.",
    "Zerggy Mania": "Zerggy Mania",
    "ZIP BOOST": "Ускорение зиплайна",
    "Zip Boost": "Ускорение зиплайна",
    "Zip Thickness": "Толщина зиплайна",
    "Zipline Boost": "Ускорение на зиплайне",
    "Ability Duration": "Длительность способностей",
    "Ability Range": "Дальность способностей",
    "Bullet Evasion": "Уклонение от пуль",
    "Bullet Lifesteal": "Вампиризм от пуль",
    "Bullet Resist": "Сопротивление пулям",
    "Clip Size": "Размер магазина",
    "Damage Amp": "Усиление урона",
    "Fire Rate": "Скорострельность",
    "Healing Amp": "Усиление лечения",
    "Health Regen": "Восстановление здоровья",
    "Move Speed": "Скорость передвижения",
    "Spirit Lifesteal": "Вампиризм от духа",
    "Spirit Power": "Сила духа",
    "Spirit Resist": "Сопротивление духу",
    "Visible Stats": "Видимые характеристики",
    "Weapon Power": "Сила оружия",
    "by": "от",
    "25%": "25%",
    "65%": "65%",
    "75%": "75%",
    "Active Item Horizontal Offset": "Гориз. положение активных предметов",
    "Active Item Scale": "Масштаб активных предметов",
    "Active Item Vertical Offset": "Верт. положение активных предметов",
    "Active Stats": "Активные статы",
    "Alert Threshold": "Порог оповещения",
    "Automatically selects 'With Party' in lane preference. Requires the party screen to be open.": "Автоматически выбирает «С группой» в предпочтении линии. Требуется открытый экран группы.",
    "Console alert when any feature exceeds this ms threshold.": "Оповещение в консоли, когда любая функция превышает этот порог в мс.",
    "Controls how many enhanced quickbuy preview items are shown.": "Управляет тем, сколько предметов показывается в превью улучшенной быстрой покупки.",
    "Customize the position of the Player Stats panel, or hide it completely.": "Настройте положение панели характеристик игрока или скройте её полностью.",
    "Damage Impact": "Эффект урона",
    "Detailed Console": "Подробная консоль",
    "Dev": "Разработка",
    "Diagnostics": "Диагностика",
    "Enable performance tracking (required for overlay).": "Включает отслеживание производительности (необходимо для оверлея).",
    "Enhanced": "Улучшенная",
    "Enhanced Count": "Кол-во в улучшенной",
    "Estimated Active Reload Timer": "Примерный таймер Active Reload",
    "Feature Test": "Тест функций",
    "Hide in normal view": "Скрывать в обычном виде",
    "Hide on scoreboard (TAB)": "Скрывать на табло (TAB)",
    "Hide the bottom-left active stats block during normal play. It stays in the HUD (just made invisible), so the Crosshair Active Stats mirror keeps working.": "Скрывает блок активных статов в левом нижнем углу во время обычной игры. Он остаётся в HUD (просто становится невидимым), поэтому отзеркаливание активных статов у прицела продолжает работать.",
    "Hide the detailed stats list that appears while the scoreboard / TAB is held.": "Скрывает подробный список характеристик, который появляется при удержании табло / TAB.",
    "Hint Size": "Размер подсказки",
    "Item Buy Notifications": "Уведомления о покупке предметов",
    "Items": "Предметы",
    "Left": "Слева",
    "MOG": "MOG",
    "MOGLOCK": "MOGLOCK",
    "Minimalistic Pause": "Минималистичная пауза",
    "Mirror active buffs/debuffs vertically next to the crosshair so they are visible mid-fight.": "Отзеркаливает активные баффы/дебаффы вертикально рядом с прицелом, чтобы они были видны прямо в бою.",
    "On Bridge": "На мосту",
    "On Mid Boss": "На Мид Боссе",
    "Only simplifies the shop stats display.": "Упрощает только отображение характеристик в магазине.",
    "Opacity of the performance overlay panel.": "Прозрачность панели оверлея производительности.",
    "Overlay Opacity": "Прозрачность оверлея",
    "Per-Hero Popups": "Всплывашки у каждого героя",
    "Perf Debug": "Отладка производительности",
    "Performance": "Производительность",
    "Pin the stats panel to the left (default, like vanilla) or right side of the screen.": "Закрепляет панель характеристик слева (по умолчанию, как в ваниле) или справа экрана.",
    "Player Stats": "Характеристики игрока",
    "Preset Cycle": "Перебор пресетов",
    "Recent Purchases": "Недавние покупки",
    "Rejuvenator": "Реджув",
    "Remind when urn, bridge buffs, and gold statue upgrades are spawning.": "Напоминает о появлении урны, рун и улучшений золотой статуи.",
    "Right": "Справа",
    "Rotate Magazine": "Повернуть магазин",
    "Rotate the ammo magazine visualiser.": "Поворачивает визуализацию магазина боеприпасов.",
    "Scoreboard": "Табло",
    "See your view angle.": "Показывает ваш угол обзора.",
    "Settings": "Настройки",
    "Show Buffs": "Показать баффы",
    "Show Build ID": "Показать ID сборки",
    "Show Debuffs": "Показать дебаффы",
    "Show Overlay": "Показать оверлей",
    "Show Player Ranks": "Показать ранги игроков",
    "Show active buffs/debuffs (firerate, slow, antiheal...) vertically next to the crosshair": "Показывает активные баффы/дебаффы (скорострельность, замедление, антихил...) вертикально рядом с прицелом",
    "Show full feature breakdown in console every 5s.": "Показывать полную разбивку по функциям в консоли каждые 5 с.",
    "Show negative modifiers (slow, antiheal, fire rate reduction...) next to the crosshair.": "Показывает отрицательные модификаторы (замедление, антихил, снижение скорострельности...) рядом с прицелом.",
    "Show positive modifiers (resistances, fire rate, lifesteal...) next to the crosshair.": "Показывает положительные модификаторы (сопротивления, скорострельность, вампиризм...) рядом с прицелом.",
    "Show purchase notifications under each hero's portrait instead of in the center.": "Показывает уведомления о покупках под портретом каждого героя вместо центра.",
    "Show rank prediction badges on top bar and escape menu player list.": "Показывает значки прогноза ранга на верхней панели и в списке игроков меню ESC.",
    "Show rank prediction badges on top bar player panels (requires Show Player Ranks).": "Показывает значки прогноза ранга на панелях игроков верхней панели (требуется «Показать ранги игроков»).",
    "Show standalone movement speed.": "Показывает отдельную скорость передвижения.",
    "Show the performance overlay HUD in-game.": "Показывает оверлей производительности в игре.",
    "Shows a countdown timer in the top bar for the next urn spawn or relocation.": "Показывает на верхней панели таймер до следующего появления или перемещения урны.",
    "Side": "Сторона",
    "Souls": "Души",
    "Urn Timer": "Таймер урны",
    "Use the compact minimalistic pause screen instead of the default large one.": "Использует компактный минималистичный экран паузы вместо большого по умолчанию.",
    "Whack a Rem": "Whack a Rem",
    "Amber": "Янтарный",
    "Big Camps + Sinners": "Большие крипы + автоматы",
    "Black": "Чёрный",
    "Blue": "Синий",
    "Brown": "Коричневый",
    "Charcoal": "Угольный",
    "Coral": "Коралловый",
    "Crimson": "Малиновый",
    "Cyan": "Голубой",
    "Gold": "Золотой",
    "Green": "Зелёный",
    "Ice": "Ледяной",
    "Indigo": "Индиго",
    "Lane Guardian Weak": "Страж линии ослаблен",
    "Lavender": "Лавандовый",
    "Lime": "Лаймовый",
    "Magenta": "Маджента",
    "Medium Camps": "Средние лагеря",
    "Mint": "Мятный",
    "Orange": "Оранжевый",
    "Pink": "Розовый",
    "Poison": "Ядовитый",
    "Purple": "Пурпурный",
    "Red": "Красный",
    "Rose": "Розово-красный",
    "Rune + Fast Troopers": "Руна + быстрые труперы",
    "Rune + Gold Buffs": "Руна + золотые баффы",
    "Rune + Melee Troopers": "Руна + труперы ближнего боя",
    "Rune + Troopers 20s HP": "Руна + труперы +HP 20с",
    "Silver": "Серебряный",
    "Sky": "Небесный",
    "Small Camps + Boxes": "Малые лагеря + ящики",
    "Teal": "Бирюзовый",
    "Urn + Gold Rune": "Урна + золотая руна",
    "Violet": "Фиолетовый",
    "Void": "Тёмный",
    "Walker Weak": "Шагоход ослаблен",
    "White": "Белый",
    "Yellow": "Жёлтый",
    "HUD settings walkthrough": "Пошаговая проверка HUD",
    "Open in a match or sandbox. Step through 12 HUD changes. Stop restores settings without saving the test values.": "Запусти в матче или песочнице. 12 шагов изменения HUD. Остановка вернёт настройки, не сохраняя тестовые значения.",
    "Settings restored": "Настройки восстановлены",
    "Open settings with a live HUD": "Открой настройки в матче или песочнице",
    "Right and down, smaller": "Вправо и вниз, меньше",
    "Right and up, smaller": "Вправо и вверх, меньше",
    "Right and up, more transparent": "Вправо и вверх, прозрачнее",
    "Right and up, more transparent; equip items first": "Вправо и вверх, прозрачнее; сначала купи предметы",
    "Right and up, larger": "Вправо и вверх, больше",
    "Smaller, more transparent": "Меньше, прозрачнее",
    "Reference position and size": "Исходное положение и размер",
    "Observe the HUD; this is not an automatic pass.": "Оцени изменения на экране. Автоматической оценки нет.",
    "Compare A/B": "Сравнить A/B",
    "Back": "Назад",
    "Next": "Далее",
    "Stop": "Стоп",
    "Start": "Начать",
    "Running": "Выполняется",
    "Right and down, smaller and more transparent": "Вправо и вниз, меньше и прозрачнее",
    "Right and up, smaller and more transparent": "Вправо и вверх, меньше и прозрачнее",
    "Inspect the changed layout, size and offsets; test inputs in game.": "Проверьте раскладку, размер и сдвиги; нажимайте клавиши в игре.",
    "Inspect the changed size and offsets; use a zipline in game.": "Проверьте размер и сдвиги; используйте зиплайн в игре.",
    "Inspect the changed offsets; move in game.": "Проверьте сдвиги; двигайтесь в игре.",
    "Inspect the changed layout, size and offsets; turn in game.": "Проверьте вид, размер и сдвиги; поворачивайтесь в игре.",
    "Inspect size, opacity and offsets while buffs or debuffs are active.": "Проверьте размер, прозрачность и сдвиги при активных баффах или дебаффах.",
    "Open the shop in game; inspect size, opacity and offsets.": "Откройте магазин в игре; проверьте размер, прозрачность и сдвиги.",
    "Buy items in game; inspect purchase history size, opacity and offsets.": "Купите предметы в игре; проверьте размер, прозрачность и сдвиги истории покупок.",
    "Trigger a new purchase notification in game; inspect size, opacity and offsets.": "Вызовите новое уведомление о покупке в игре; проверьте размер, прозрачность и сдвиги.",
    "Trigger a new purchase notification in game; compare center and per-hero placement.": "Вызовите новое уведомление о покупке в игре; сравните размещение в центре и под героями.",
    "Test in game, then reopen QOLLOCK settings to continue this step.": "Проверьте в игре, затем снова откройте настройки QOLLOCK для продолжения этого шага.",
    "Test in game": "Проверить в игре",
    "Shop Display": "Вид магазина",
    "Inspect size, opacity and offsets during gameplay.": "Проверьте размер, прозрачность и сдвиги во время игры.",
    "Deal damage in game; inspect size, opacity and offsets.": "Нанесите урон в игре; проверьте размер, прозрачность и сдвиги.",
    "Collect unsecured souls in game; inspect size and offsets.": "Соберите необеспеченные души в игре; проверьте размер и сдвиги.",
    "Open chat in game; inspect size and offsets.": "Откройте чат в игре; проверьте размер и сдвиги.",
    "Reload in game; inspect size, opacity and offsets.": "Перезарядитесь в игре; проверьте размер, прозрачность и сдвиги.",
    "Open in a match or sandbox. Compare HUD changes and test gameplay. Stop restores settings without saving the test values.": "Откройте в матче или песочнице. Сравнивайте изменения HUD и проверяйте их в игре. Остановка восстановит настройки без сохранения тестовых значений.",
    "HUD state recording": "Запись состояний HUD",
    "Record HUD states and managed callback activity for 60 seconds. Reproduce the stutter or return to hideout. Settings are unchanged.": "Запись состояний HUD и работы управляемых колбэков в течение 60 секунд. Воспроизведите статтеры или вернитесь в убежище. Настройки не меняются.",
    "After recording, copy HUD transitions, callback timings, delivery delays and active task counts. This is not an FPS measurement.": "После записи скопируйте переходы HUD, время выполнения колбэков, задержки их запуска и число активных задач. Это не измерение FPS.",
    "Record for 60 seconds while playing: open and close the scoreboard, die and respawn. Settings are unchanged.": "Запись 60 секунд в игре: откройте и закройте таблицу счёта, умрите и возродитесь. Настройки не меняются.",
    "Record HUD states": "Записать состояния HUD",
    "HUD state report": "Отчёт о состояниях HUD",
    "After recording, copy the class transitions and scoreboard event observations.": "После записи скопируйте переходы классов и события таблицы счёта.",
    "Copy HUD state report": "Копировать отчёт HUD",
    "No completed HUD state recording yet.": "Завершённой записи состояний HUD пока нет.",
    "HUD state report copied.": "Отчёт о состояниях HUD скопирован.",
    "Copy failed; see the console log.": "Не удалось скопировать; отчёт есть в консоли.",
    "Customize": "Настроить HUD",
    "Current Ammo": "Текущие патроны",
    "Total Ammo": "Максимум патронов",
    "Rotation": "Поворот",
    "Active Items": "Активные предметы",
    "Hide (Normal)": "Скрыть (обычный HUD)",
    "Hide (Scoreboard)": "Скрыть (TAB)",
    "Lock dragging": "Заблокировать перетаскивание",
    "Unavailable now": "Сейчас недоступно",
    "Preview active": "Предпросмотр активен",
    "Waiting for HUD preview": "Ожидание предпросмотра HUD",
    "Select an element, drag its frame, or enter exact values.": "Выбери элемент, перетащи его рамку или введи точные значения.",
    "Undo": "Отменить действие",
    "Redo": "Повторить действие",
    "Apply": "Применить",
    "Reset": "Сбросить",
    "Open editor": "Открыть редактор",
    "Move HUD elements on screen and edit their colors. Save keeps changes; Cancel discards the draft.": "Перетаскивай элементы HUD и меняй цвета. «Сохранить» сохранит изменения, «Отмена» их сбросит.",
    "Edit settings here; live HUD frames appear in a match or sandbox.": "Настройки можно менять здесь; рамки HUD появятся в матче или песочнице.",
    "The editor could not open. Close other visual tools and try again.": "Редактор не открылся. Закрой другие визуальные инструменты и попробуй снова.",
    "Editor error:": "Ошибка редактора:",
    "Press Enter to preview a typed value.": "Нажми Enter, чтобы посмотреть введённое значение на HUD.",
    "Enter a valid number or #RRGGBB color.": "Введи корректное число или цвет #RRGGBB.",
    "Saving HUD changes...": "Сохранение изменений HUD...",
    "HUD changes saved.": "Изменения HUD сохранены.",
    "HUD changes applied, but saving failed. Retry save or close.": "HUD изменён, но сохранить настройки не удалось. Повтори сохранение или закрой редактор.",
    "Retry save": "Повторить сохранение",
    "Close": "Закрыть",
    "HUD Elements": "Элементы интерфейса",
    "Search elements": "Поиск элементов",
    "Hide Magazine": "Скрыть магазин патронов",
    "Hide Ammo": "Скрыть патроны",
    "Debuffs": "Ослабления",
    "Buffs": "Усиления",
    "Healing Amplification": "Усиление лечения",
    "Weapon Damage": "Урон оружия",
    "Range": "Дальность",
    "Damage Amplification": "Усиление урона",
    "Ammo Capacity": "Ёмкость магазина",
    "Width": "Ширина",
    "Height": "Высота",
    "Icon Text": "Текст на значке",
    "Keyboard Overlay": "Клавиатура на экране",
    "Full Keyboard": "Полная клавиатура",
    "Hide Reload Icon": "Скрыть значок перезарядки",
    "Hide Reload Circle": "Скрыть круг перезарядки",
    "Position uses percentages. Dragging is unavailable for this element; enter exact values.": "Положение задаётся в процентах. Этот элемент пока нельзя перетаскивать; вводи точные значения.",
    "Basic Mode": "Обычный режим",
    "Horizontal Offset (%)": "Смещение по горизонтали (%)",
    "Vertical Offset (%)": "Смещение по вертикали (%)",
    "Base Minimap": "Обычная миникарта",
    "Crates": "Ящики",
    "Tunnel Opacity": "Непрозрачность тоннелей",
    "Minimap: Alt": "Миникарта: Alt",
    "Minimap: Tab": "Миникарта: Tab",
    "Minimap Timers": "Таймеры миникарты",
    "Rejuvenator Timer": "Таймер омоложения",
    "Always Show Mid Boss": "Всегда показывать мид-босса",
    "Disable Shop Blue": "Убрать синий фон магазина",
    "Shop Stats": "Характеристики в магазине",
    "Simplify Shop Stats": "Упростить характеристики магазина",
    "Disable Quick Buy": "Отключить быструю покупку",
    "Item Notifications": "Уведомления о предметах",
    "Hero Purchase Popups": "Покупки над героями",
    "Maximum Items": "Максимум предметов",
    "Display Duration": "Время показа",
    "Minecraft": "Minecraft",
    "Health Warnings": "Предупреждения о здоровье",
    "Hide": "Скрыть",
    "Images In Chat": "Картинки в чате",
    "Objectives": "Объекты на карте",
    "Hide Top Bar Background": "Скрыть фон верхней панели",
    "Ranks": "Ранги",
    "Show Rank": "Показывать ранг",
    "Show Rank in Top Bar": "Ранг на верхней панели",
    "Ultimate Cooldowns": "Перезарядка ультимейтов",
    "Top Bar HP Warnings": "Здоровье на верхней панели",
    "Urn": "Урна",
    "Buffs and Rejuvenator": "Усиления и омоложение",
    "Buff HUD": "Усиления на экране",
    "Rejuvenator HUD": "Омоложение на экране",
    "Ability Icons": "Значки способностей",
    "Hide Cosmetic Abilities": "Скрыть косметические способности",
    "Hide Failed Cast Hint": "Скрыть подсказку неудачного применения",
    "Build ID": "Номер сборки",
    "Build Title": "Название сборки",
    "Target Shapes": "Метки целей",
    "These visuals follow world targets. Size and visibility remain configurable; screen dragging does not apply.": "Эти метки следуют за целями в мире. Можно менять размер и видимость, но перетаскивать их по экрану нельзя.",
    "Red Diamond": "Красный ромб",
    "Clean Damage Indicators": "Упрощённые индикаторы урона",
    "Cumulative Damage": "Суммарный урон",
    "HUD profile links use this toggle. Profile and profile-card additions have their own context and no editable geometry.": "Этот переключатель управляет ссылками на профили в игровом интерфейсе. Элементы страницы и карточки профиля не имеют настроек положения.",
    "Testing Tools": "Инструменты тестирования",
    "Other Screens": "Другие экраны",
    "Testing tools appear in hero testing. Their visibility is configurable; their native layout has no position settings.": "Инструменты доступны при тестировании героя. Можно менять видимость; настроек положения у них нет.",
    "Menu Layout": "Расположение меню",
    "Menu changes are visible when the editor closes. Their existing controls do not define independent screen offsets.": "Изменения меню видны после закрытия редактора. Существующие настройки не задают произвольные смещения.",
    "Display & Screen": "Экран и отображение",
    "These controls adjust several HUD owners together. Recheck frames after changing display support.": "Эти настройки меняют расположение нескольких элементов сразу. После изменения проверь их рамки.",
    "Performance Overlay": "Показатели производительности",
    "On-death Games": "Игры после смерти",
    "Arcade overlays use their own modal layout and appear after death. Screen dragging does not apply.": "Игры открываются в отдельных окнах после смерти. Перетаскивание по экрану для них недоступно.",
    "Minesweeper": "Сапёр",
    "Whack-a-Rem": "Ударь Рема",
    "Reminder Captions": "Субтитры напоминаний",
    "Captions require the corresponding reminders. The caption renderer owns its layout.": "Для субтитров нужны соответствующие напоминания. Отдельных настроек положения у них нет.",
    "Profile and Profile Card": "Профиль и карточка профиля",
    "Profile links, rank badges and profile controls run in separate native contexts. They currently have no persistent customization settings.": "Ссылки, ранги и кнопки профиля работают на отдельных экранах. Сейчас у них нет сохраняемых настроек внешнего вида.",
    "Quickbuy Total Summary": "Сумма быстрой покупки",
    "The quickbuy summary uses the active quickbuy script and its parent layout. It has no separate persistent customization settings.": "Сумма покупок следует расположению панели быстрой покупки. Отдельных сохраняемых настроек у неё нет.",
    "Fixed HUD Visuals": "Элементы с фиксированным видом",
    "Cursor, signature press flash, fixed icons and shared styles belong to their original owners. No independent position or color setting exists for these assets.": "Курсор, вспышки способностей, фиксированные значки и общие стили используют оформление своих панелей. Отдельных настроек положения и цвета у них нет.",
    "Main Menu Cards": "Карточки главного меню",
    "Dashboard cards and links have fixed layouts and no persistent customization settings.": "Карточки и ссылки главного меню имеют фиксированное расположение без сохраняемых настроек.",
    "Friend Search": "Поиск друзей",
    "Friend search belongs to the friends pane and has no independent appearance settings.": "Поиск находится на панели друзей и не имеет отдельных настроек внешнего вида.",
    "Settings Interface": "Окно настроек",
    "Settings, previews, tooltips and developer dialogs use the settings theme. Change the theme in Settings.": "Настройки, превью, подсказки и окна разработчика используют тему настроек. Её можно сменить во вкладке настроек.",
    "Inactive Visuals": "Неактивные элементы",
    "Legacy souls-per-minute, unspent-souls and fortitude widgets are inactive. The editor does not enable unfinished renderers.": "Старые элементы душ в минуту, непотраченных душ и стойкости неактивны. Редактор не включает незавершённые функции.",
    "Enemy 25%": "Враги: 25%",
    "Enemy 65%": "Враги: 65%",
    "Enemy 75%": "Враги: 75%",
    "Ally 25%": "Союзники: 25%",
    "Ally 65%": "Союзники: 65%",
    "Ally 75%": "Союзники: 75%",
    "Hide panels": "Скрыть панели",
    "Show panels": "Показать панели",
    "Show frames": "Показать рамки",
    "Hide frames": "Скрыть рамки",
    "Snap to center": "Прилипание к центру",
    "Only this element can be edited. Other HUD elements stay locked.": "Можно изменить только этот элемент. Остальные элементы HUD заблокированы.",
    "Unknown HUD element.": "Неизвестный элемент HUD.",
    "HEX (#RRGGBB)": "HEX (#RRGGBB)",
    "Drag an element to move it. Drag its corner to resize.": "Перетащи элемент для перемещения, уголок — для изменения масштаба.",
    "Undo the last change.": "Отменить последнее изменение.",
    "Restore the change canceled by Undo.": "Повторить изменение, отменённое кнопкой Undo.",
    "Reset the selected element to defaults.": "Сбросить выбранный элемент к значениям по умолчанию.",
    "Drag to move. Drag any corner to resize.": "Перетащите для перемещения. Тяните за любой угол для изменения размера.",
    "Drag any corner to resize.": "Тяните за любой угол для изменения размера.",
    "Visible": "Виден",
    "Hidden": "Скрыт",
    "Exact position": "Точное положение",
    "Horizontal": "По горизонтали",
    "Vertical": "По вертикали",
    "Lock position": "Закрепить положение",
    "More options": "Другие настройки",
    "Color presets": "Палитра цветов",
    "Use a number from {min} to {max}.": "Введите число от {min} до {max}.",
    "Enter a complete HEX color, such as #AABBCC.": "Введите HEX-код цвета целиком, например #AABBCC.",
    "About this element": "Об этом элементе",
    "All elements": "Все элементы",
    "No visible elements": "Нет видимых элементов",
    "Ability Points": "Очки способностей",
    "Custom position": "Своё положение",
    "Magazine indicator": "Индикатор магазина",
    "Hide current ammo": "Скрыть текущий боезапас",
    "Hide total ammo": "Скрыть общий боезапас",
    "−": "−",
    "+": "+",
    "px": "пкс",
    "%": "%",
    "°": "°",
    "ACTIVE STATS": "АКТИВНЫЕ ЭФФЕКТЫ",
    "Apply every preset and verify no features auto-disable. Click again to stop.": "Применить каждый пресет и проверить, не отключаются ли функции из-за ошибок. Нажмите ещё раз для остановки.",
    "Audit not started: {error}": "Проверка не началась: {error}",
    "Auditing...": "Проверка...",
    "Benchmark (Expanded Config)": "Замер с расширенными настройками",
    "Benchmark timeout": "Время ожидания замера истекло",
    "Benchmarking: {seconds}s left...": "Замер: осталось {seconds} с...",
    "Build Storage Dry Run": "Пробный запуск хранения сборок",
    "Cancelled": "Отменено",
    "Changes: {count}": "Изменений: {count}",
    "Collect HUD observations, named manifest checks and recorded errors once. Copies the report; does not prove all features work.": "Собрать наблюдения HUD, проверки манифестов и записанные ошибки. Отчёт копируется; это не доказывает исправность всех функций.",
    "Copied! {milliseconds}ms callbacks (Check ~)": "Скопировано! Вызовы: {milliseconds} мс (см. ~)",
    "Copy Logs": "Копировать журнал",
    "Copy Manifest Report": "Копировать отчёт манифестов",
    "Copy QOLLock diagnostic logs to clipboard.": "Копировать диагностический журнал QOLLOCK в буфер обмена.",
    "Cycle Presets": "Перебрать пресеты",
    "Display & Resolution": "Экран и разрешение",
    "Done: {milliseconds}ms callbacks (Check ~)": "Готово: вызовы заняли {milliseconds} мс (см. ~)",
    "Done: {passed} passed, {failed} failed": "Готово: успешно — {passed}, ошибок — {failed}",
    "Done: {passed} passed, {failed} failed, {skipped} skipped": "Готово: успешно — {passed}, ошибок — {failed}, пропущено — {skipped}",
    "Dry run started": "Пробный запуск начат",
    "Dump Tree": "Снять дерево",
    "Dump the live panel tree to the console log for the offline profiler. Requires HUD context; save your console log afterwards.": "Вывести текущее дерево панелей в консоль для офлайн-профилировщика. Требуется HUD; после выполнения сохраните журнал консоли.",
    "Dumped to console log": "Выведено в журнал консоли",
    "Enemy V2": "Враг V2",
    "FAIL: {features}": "ОШИБКА: {features}",
    "Finalizing report...": "Подготовка отчёта...",
    "Game & Interface": "Игра и интерфейс",
    "Hooks: {passed}/{total} OK, {failed} failed, {errors} errors, {unchecked} unchecked{incomplete}": "Проверки: {passed}/{total} успешно, {failed} провалено, ошибок — {errors}, без проверки — {unchecked}{incomplete}",
    " (incomplete)": " (неполный отчёт)",
    "Hud panel not found": "Панель HUD не найдена",
    "Idle": "Ожидание",
    "Import {schema} applied. clamped={clamped} unknown={unknown}": "Импорт {schema} применён. Ограничено значений: {clamped}; неизвестных ключей: {unknown}",
    "In-Game Benchmarks": "Замеры в игре",
    "In-Game Engine Audit": "Проверка движка в игре",
    "Level": "Уровень",
    "Manifest Report": "Отчёт манифестов",
    "Manifest Tests": "Проверки манифестов",
    "No presets found.": "Пресеты не найдены.",
    "No toggle keys found": "Настройки-переключатели не найдены",
    "Panel Tree Dump": "Снимок дерева панелей",
    "Perform a dry run of the build storage pipeline (switch hero, open shop, open popup) and dump tree to console. Requires HUD context.": "Пробный запуск хранения сборок: сменить героя, открыть магазин и окно сборки, вывести дерево в консоль. Требуется HUD.",
    "Read registered manifest checks in the current HUD. Reports skips and failures; does not verify rendering or gameplay.": "Выполнить зарегистрированные проверки манифестов в текущем HUD. Отчёт содержит пропуски и ошибки; отображение и игровой процесс остаются непроверенными.",
    "Request failed": "Запрос не выполнен",
    "Restart your game to re-enable these features.": "Перезапустите игру, чтобы снова включить эти функции.",
    "Rift Timer": "Таймер разлома",
    "Run Engine Audit": "Проверить движок",
    "Run Feature Test": "Проверить функции",
    "Run Manifest Tests": "Проверить манифесты",
    "Run Storage Test": "Проверить хранение",
    "Run Stress Test (10s)": "Запустить стресс-тест (10 с)",
    "Run manifest checks and copy their observations, skips and errors. Rendering and gameplay remain unverified.": "Выполнить проверки манифестов и скопировать наблюдения, пропуски и ошибки. Отображение и игровой процесс остаются непроверенными.",
    "Running...": "Выполнение...",
    "SAVING": "СОХРАНЕНИЕ",
    "SUCCESS": "УСПЕШНО",
    "Schema {schema} | clamped={clamped} | unknown={unknown}": "Схема {schema} | ограничено={clamped} | неизвестно={unknown}",
    "Some QOLLOCK features were auto-disabled due to errors:": "Некоторые функции QOLLOCK автоматически отключены из-за ошибок:",
    "Starting...": "Запуск...",
    "Stopped": "Остановлено",
    "Stopped ({done} of {total})": "Остановлено ({done} из {total})",
    "Temporarily enables additional toggles for 10s, measures Scheduler poll callbacks, then restores config. Does not exercise every feature or measure FPS.": "На 10 с включить дополнительные функции, замерить вызовы Scheduler и восстановить настройки. Тест не охватывает все функции и не измеряет FPS.",
    "Test each feature individually (enable → verify → disable).": "Проверить каждую функцию отдельно: включить → проверить → отключить.",
    "Testing & Diagnostics": "Тестирование и диагностика",
    "Timeout (8s)": "Время ожидания истекло (8 с)",
    "Timeout — no HUD report within 6s": "Время ожидания истекло: отчёт HUD не получен за 6 с",
    "Timeout — no result within 6s": "Время ожидания истекло: результат не получен за 6 с",
    "{label} — EXCEPTION": "{label} — ИСКЛЮЧЕНИЕ",
    "{label} — TIMEOUT": "{label} — ВРЕМЯ ИСТЕКЛО",
    "{status} ({copy})": "{status} ({copy})",
    "{tab} — content ready.": "{tab} — содержимое готово.",
    "copied": "скопировано",
    "copy failed": "не удалось скопировать",
    "copy failed; check ~": "не удалось скопировать; см. ~",
    "Available": "Свободно",
    "Belarusian": "Белорусский",
    "Italian": "Итальянский",
    "Korean": "Корейский",
    "Turkish": "Турецкий",
    "Cleared in {seconds}s.": "Пройдено за {seconds} с.",
    "Color is shared with Bottom Bar.": "Цвет общий с нижней панелью.",
    "Magnets": "Магниты",
    "Properties": "Свойства",
    "Align left": "По левому краю",
    "Center horizontally": "По центру X",
    "Align right": "По правому краю",
    "Align top": "По верхнему краю",
    "Center vertically": "По центру Y",
    "Align bottom": "По нижнему краю"
};
})();
