// ql_settings_loc_it.js — QOLLOCK settings locale (it)
// Extracted from ql_settings.js, Phase 1
(function() {
    'use strict';
    if (!window.SETTINGS_LOCALE_TEXT) window.SETTINGS_LOCALE_TEXT = {};
    window.SETTINGS_LOCALE_TEXT["it"] = {
    "Ammo": "munizione",
    "Announcer": "annunciatore",
    "Bebop Sweeper": "Ottone Minato",
    "Budhud": "hud amici",
    "Buff": "potenziamento",
    "Color": "colore",
    "Compass": "bussola",
    "Console": "console",
    "Crosshair": "crosshair",
    "Custom": "personalizzato",
    "DISCORD": "Discord",
    "Default": "default",
    "Discord": "Discord",
    "Enemy": "nemico",
    "Enhanced": "migliorato",
    "FAILED": "fallito",
    "Gold": "oro",
    "HUD": "HUD",
    "Healthbar": "barra salute",
    "Hero": "eroe",
    "Icon": "icona",
    "Klutz's Bar": "barra per imbranati",
    "MOG": "MOG",
    "MOGLOCK": "MOGLOCK",
    "Minimalist": "minimalista",
    "Minimap": "minimappa",
    "Opacity": "opacità",
    "Open": "apri",
    "Overlay": "overlay",
    "Play": "suonare",
    "Player": "giocatore",
    "QOL": "QOL",
    "Rejuvenator": "Rianimatore",
    "SAVE": "salva",
    "Save": "salva",
    "Scoreboard": "classifica",
    "Settings": "impostazioni",
    "Shop": "negozio",
    "Size": "dimensione",
    "Souls": "anime",
    "Speed": "velocità",
    "Statlocker": "Statlocker",
    "Stats": "statistiche",
    "Timer": "timer",
    "Total": "totale",
    "UI": "UI",
    "Visual": "grafico",
    "moglock.gg": "moglock.gg",
    "CLEAR": "CLEAR",
    "Chat": "chat",
    "Special Thanks": "Ringraziamenti speciali",
    "Support": "supporto"
};
})();
