// ql_settings_loc_by.js — QOLLOCK settings locale (by)
// Extracted from ql_settings.js, Phase 1
(function() {
    'use strict';
    var _root = (typeof globalThis !== "undefined") ? globalThis : (typeof window !== "undefined") ? window : {};
    if (!_root.SETTINGS_LOCALE_TEXT) _root.SETTINGS_LOCALE_TEXT = {};
    _root.SETTINGS_LOCALE_TEXT["by"] = {
    "<font color=\"#66cc99\">Free</font> updates for new features, <font color=\"#66cc99\">$5</font> for arbitrary changes": "<font color=\"#66cc99\">Бясплатныя</font> змены для новых функцый, <font color=\"#66cc99\">$5</font> для адвольных змяненняў",
    "16:10 Support": "Падтрымка 16:10",
    "1st": "1-шы",
    "21:9 Stream Fix": "Фікс 21:9 для стрымаў",
    "2nd": "2-гі",
    "3rd": "3-ці",
    "4:3 Support": "Падтрымка 4:3",
    "Ability Cooldown %: --": "Адкат уменняў %: --",
    "Ability Menu Open": "Меню уменняў адкрыта",
    "Ability Suggestion": "Прапанова уменняў",
    "Accent Color": "Акцэнтны колер",
    "Accuracy:": "Дакладнасць:",
    "actionbutton": "Кнопка дзеяння",
    "Addons": "Aддоны",
    "Adds a STAT button on profile rows that opens Statlocker for that account.": "Дадць кнопку STAT ў радках профілю, якая адкрывае Statlocker для гэтага акаўнта.",
    "Adjust horizontal position of the in-game chat.": "Наладзіць гарызантальнае становішча ўнутрыгульнявога чату.",
    "Adjust horizontal position of the player healthbar.": "Наладзіць гарызантальнае становішча паласы здароўя гульца.",
    "Adjust opacity of the player healthbar.": "Наладзіць празрыстасць паласы здароўя гульца.",
    "Adjust size of the in-game chat.": "Наладзіць памер унутрыгульнявога чату.",
    "Adjust size of the player healthbar.": "Наладзіць памер паласы здароўя гульца.",
    "Adjust the in-game chat position and scale.": "Наладзіць становішча і маштаб унутрыгульнявога чату.",
    "Adjust vertical position of the in-game chat.": "Наладзіць вертыкальнае становішча ўнутрыгульнявога чату.",
    "Adjust vertical position of the player healthbar.": "Наладзіць вертыкальнае становішча паласы здароўя гульца.",
    "Advanced": "Пашыраны",
    "Advanced Filter": "Пашыраны фільтр",
    "Advanced Mode": "Пашыраны рэжым",
    "Skyrunner switch sent.": "Запыт на змену героя на Skyrunner.",
    "All commissioned additions are released publicly and available to everyone.": "Усе замоўленыя змены дадаюцца ў публічную версію і даступныя ўсім.",
    "Allows you to drag move some menus.": "Дазваляе перацягваць некаторыя меню.",
    "Ally HP Warning": "папярэджанне пра АЗ саюзніка",
    "Already at default value.": "Ужо па змаўчанні.",
    "Alt Zoom": "Зум мінікарты на ALT",
    "Always Hidden": "Заўсёды схаваны",
    "Always Shown": "Заўсёды паказваць",
    "Always Visible Boost": "Заўсёды бачна паскарэнне",
    "Always Visible Override": "Прымусова заўсёды бачна",
    "Ammo": "Боезапас",
    "An always visible zipline boost overlay.": "Пастаянна бачны оверлэй буста зіплайна.",
    "Angle and Speed": "Вугал і хуткасць",
    "Announcer": "Дыктар",
    "Append the selected build title after the build ID.": "Дадайце назву абранага білду пасля ідэнтыфікатара білду.",
    "APPLIED": "ПРЫМЕНЕНА",
    "APPLY": "ПРЫМЯНІЦЬ",
    "Arcade": "Аркада",
    "Asmon": "Asmon",
    "Audio": "Аўдыя",
    "Author:": "Аўтар:",
    "Automatically selects Lane Preference: With Party for matchmaking.": "Аўтаматычна выбірае перавагу лініі: з групай.",
    "Backup & Restore": "Рэзервовае капіяванне і аднаўленне",
    "Base": "База",
    "Be conscious of the features you are using and read carefully.": "Будзьце ўважлівыя да функцый, якімі вы карыстаецеся, і ўважліва чытайце.",
    "Bebop Sweeper": "Bebop Sweeper",
    "Beep": "Beep",
    "Behavior Summary": "Плашка паводзін",
    "Best:": "Лепшы:",
    "Better Item Cooldowns": "Палепшаныя кулдаўны прадметаў",
    "Better Unsecured": "Палепшаныя страчвальныя душы",
    "Better Unsecured Souls": "Палепшаныя ненадзейныя душы",
    "BHOP UI": "Bhop UI",
    "Big Number": "Вялікі лік",
    "Big Numbers": "Вялікія лікі",
    "Big Red": "Вялікі і чырвоны",
    "Blackjack": "Блэкджек",
    "Blackjack - You win.": "Блэкджэк – Вы выйгралі.",
    "Blur": "Размыццё",
    "Boom. Press New Game.": "Бум. Націсніце «Новая гульня».",
    "Bottom Bar": "Ніжняя панэль",
    "BR Portuguese": "БР Партугальская",
    "Bridge Buff": "Руна",
    "Bridge Buff Delay": "Час да напаміну пра руны",
    "Bridge Buff Timer": "Таймер рун",
    "Bridge Buffs": "Руны",
    "Budhud": "Budhud",
    "Buff": "Баф",
    "Buff Delay": "Затрымка бафа",
    "Buff Filter": "Фільтр бафаў",
    "Buff Reminder": "Напамін пра руны",
    "Buff Timer": "Таймер бафаў",
    "Bulgarian": "Балгарская",
    "Bust - Dealer wins.": "Перабор – перамога дылера.",
    "by": "па",
    "By default everything is disabled and has nearly zero performance cost.": "Па змаўчанні ўсё адключана і мае амаль нулявы ўплыў на прадукцыйнасць.",
    "Cancel": "Адмена",
    "Captions": "Подпісы",
    "Centered ESC Menu": "Адцэнтраваць меню ESC",
    "Centered Friends List": "Адцэнтраваць спіс сяброў",
    "Centers ESC menu elements to make them easier to access.": "Цэнтруе элементы меню ESC для больш зручнага доступу.",
    "Centers friends list area in ESC menu.": "Цэнтруе блок спісу сяброў у меню ESC.",
    "Centers the friends list area within the ESC menu.": "Адцэнтроўвае спіс сяброў у ESC",
    "Change Log": "Спіс змен",
    "CHANGE LOG": "СПІС ЗМЕН",
    "Changes the element's transparency.": "Змяняе празрыстасць элемента.",
    "Changes the visual theme used by the settings menu, modals, loader, and save menus.": "Змяняе візуальную тэму, якая выкарыстоўваецца меню налад, мадальнымі вокнамі, меню загрузчыка і захавання.",
    "Changes urn color to know which side is favored, green for your team, red for the enemy.": "Перафарбоўвае урну ў залежнасці ад перавагі каманд: зялёны - для вашай каманды, чырвоны - для праціўніка.",
    "Changes:": "Змены:",
    "Chat": "Чат",
    "Check out our site to join": "Наведайце наш сайт, каб далучыцца",
    "Chinese": "Кітайская",
    "Choose a preset accent color for the player healthbar frame.": "Абярыце прадвызначаны акцэнтны колер для рамкі панэлі здароўя гульца.",
    "Choose a preset border color for stamina charge indicators.": "Абярыце прадвызначаны колер рамкі для індыкатараў зараду вынослівасці.",
    "Choose a preset color wash for minimap icons.": "Абярыце прадвызначаную каляровую заліву для значкоў мінікарты.",
    "Choose a preset color wash for the bottom ability bar.": "Абярыце прадвызначаную каляровую заліву для ніжняй панэлі уменняў.",
    "Choose a preset color wash for the item bar.": "Абярыце прадвызначаную каляровую заліву для панэлі прадметаў.",
    "Choose a preset color wash for the keyboard overlay.": "Абярыце прадвызначаную каляровую заліву для накладання клавіятуры.",
    "Choose a preset text color for the ammo display.": "Абярыце прадвызначаны колер тэксту для адлюстравання боезапасу.",
    "Choose which bridge buff sound variants can play.": "Абярыце, якія варыянты гуку руны могуць прайгравацца.",
    "Circle": "Круг",
    "Clean Indicators": "Лаканічныя індыкатары",
    "Clean Stacks": "Лаканічныя Стаки",
    "Cleaner Items": "Лаканічныя прадметы",
    "Cleaner Skills": "Лаканічныя уменні",
    "Cleans up the styling of reticle hints.": "Паляпшае стыль падказак прыцэла.",
    "Cleans up the visuals of the shop stats display without changing the rest of the shop.": "Ачышчае візуальнае адлюстраванне статыстыкі крамы, не змяняючы астатнюю частку крамы.",
    "Cleans up visuals of abilities significantly to reduce clutter.": "Моцна спрашчае візуал здольнасцей, памяншаючы перагружанасць.",
    "Cleans up visuals of the item bar significantly to reduce clutter.": "Моцна спрашчае візуал панэлі прадметаў, памяншаючы перагружанасць.",
    "Cleans up visuals of the minimap significantly to reduce clutter.": "Моцна спрашчае візуал міні-карты, памяншаючы перагружанасць.",
    "Cleans up visuals of the shop menu significantly to reduce clutter.": "Моцна спрашчае візуал крамы, памяншаючы перагружанасць.",
    "CLEAR": "АЧЫСЦІЦЬ",
    "Clear completed.": "Ачыстка завершана.",
    "Clear failed.": "Ачыстка не ўдалася.",
    "Clear in progress...": "Ідзе ачыстка...",
    "Clear timed out. Try again.": "Ачыстка не вярнула адказ своечасова. Паспрабуйце яшчэ раз.",
    "CLEARED": "АЧЫШЧАНА",
    "Cleared in": "Ачышчана ў",
    "Clearing builds...": "Ачышчаем білды...",
    "click here": "націсніце сюды",
    "Click Radius": "Радыус кліку",
    "Click to Notify": "Націсніце, каб паведаміць",
    "Clip Size % Increase: --": "Павелічэнне памеру кліпа ў %: --",
    "Clipboard copy failed.": "Капіяванне ў буфер абмену не ўдалося.",
    "Color": "Колер",
    "Color Warning": "Каляровае папярэджанне",
    "Colored ally top-bar health warnings when at significant thresholds.": "Каляровыя папярэджанні пра HP саюзнікаў на верхняй панэлі пры дасягненні значных парогаў.",
    "Colored enemy healthbar warnings when at significant thresholds.": "Каляровыя папярэджання на панэлі HP суперніка пры дасягненні значных парогавых значэнняў.",
    "Colored enemy top-bar health warnings when at significant thresholds.": "Каляровыя папярэджанні пра HP праціўніка на верхняй панэлі пры дасягненні значных парогаў.",
    "Colored Health": "Каляровае здароўе",
    "Colored Healthbar": "Каляровы HP-бар",
    "Colored healthbar warnings when at significant thresholds.": "Каляровыя папярэджанні HP-бара на важных парогах.",
    "Combat Indicator": "Індыкатар бою",
    "Combat Status": "Стан бою",
    "Commission": "Заказы",
    "Community acknowledgements": "Падзякі супольнасці",
    "Compact Layout": "Кампактны выгляд",
    "Compass": "Компас",
    "Compass & Speed": "Компас і хуткасць",
    "Config": "Канфіг",
    "Confirm": "Пацвердзіць",
    "Confirming Skyrunner for clear...": "Праверка Skyrunner для ачысткі...",
    "Console": "Кансоль",
    "Console Notes": "Нататкі да кансолі",
    "Contact": "Сувязь",
    "Contributors": "Сааўтары",
    "COPIED": "СКАПІЯВАНА",
    "COPY": "СКАПІЯВАЦЬ",
    "Cosmetic Ability": "Касметычныя ўменні",
    "Crashed. Click playfield to restart.": "Разбіўся. Націсніце для перазапуску.",
    "Crate Overlay": "Паказваць скрыні",
    "Created By": "Аўтар",
    "Created By:": "Аўтар:",
    "Credits": "Творчая група",
    "Crosshair": "Прыцэл",
    "Current": "Сучасны",
    "Current ammo inside of your magazine.": "Бягучы запас патронаў у вашым краме.",
    "Current Size": "Бягучы памер",
    "Custom": "Кастамны",
    "Custom Preset Commission: <font color=\"#66cc99\">$25</font>": "Заказ асабістага прэсета: <font color=\"#66cc99\">$25</font>",
    "Customizable Unsecured Souls": "Наладжвальныя ненадзейныя душы",
    "Customize the styling of damage numbers.": "Наладжвае стыль лікаў урону.",
    "Customize the visuals of the incoming damage panel.": "Наладжвае выгляд панэлі ўваходнага ўрону.",
    "Customize unsecured souls visuals.": "Наладжвае выгляд ненадзейных душ.",
    "Customize visibility of target reticle when abilities or items visually show on allies and enemies.": "Наладжвайце бачнасць прыцэльнай сеткі, калі уменне або прадметы візуальна адлюстроўваюцца на саюзніках і ворагах.",
    "Customized healthbars for better visibility or flair.": "Кастомныя HP-бары для лепшай чытальнасці і стылю.",
    "Damage Fountain": "Пашкоджанне ад фантана",
    "Damage Numbers": "Лікі ўрону",
    "Damage Report": "Сводка пашкоджанняў",
    "DAMAGE REPORT": "СВОДКА ПАШКОДЖАННЯЎ",
    "Dealer": "Дылер",
    "Dealer blackjack.": "У дылера блэкджек.",
    "Dealer busts - You win.": "У дылера перабор — вы выйгралі.",
    "Dealer wins.": "Дылер выйграе.",
    "Decide what style of item to display the cooldown of.": "Вырашыце, для якога тыпу прадметаў будзе адлюстроўвацца час аднаўлення.",
    "Deck:": "Калода:",
    "Default": "Па змаўчанні",
    "Default 18": "Па змаўчанні 18",
    "Default 400": "Па змаўчанні 400",
    "Default difficulty when opening games.": "Складанасць па змаўчанні пры адкрыцці гульняў.",
    "Default Hero": "Герой па змаўчанні",
    "Defensive Active": "Актыўныя абарончыя",
    "Defensive Passive": "Пасіўныя абарончыя",
    "Depending on complexity and work involved": "У залежнасці ад складанасці і аб'ёма працы",
    "Depending on complexity and work involved, contact me on": "У залежнасці ад складанасці і аб'ёма працы,звяжыцеся са мной у",
    "Difficulty": "Складанасць",
    "Ding to Check Minimap": "Гукавы напамін пра міні-карту",
    "Disabled": "Адключана",
    "Discord": "Discord",
    "DISCORD": "DISCORD",
    "Discord: <font color=\"#66cc99\">civocivocivo</font>": "Discord: <font color=\"#66cc99\">civocivocivo</font>",
    "Display Hero": "Паказаць героя",
    "Display Stats": "Паказаць статыстыку героя",
    "DO NOT PRESS ANY KEYS UNTIL COMPLETE UNLESS PROMPTED": "НЕ НАЦІСКАЙЦЕ КЛАВІШЫ ДА ЗАВЯРШЭННЯ, КАЛІ НЕ БЫЛО ЗАПЫТАЎ НА ГЭТА",
    "Download": "Спампаваць",
    "Drag": "Перацягнуць",
    "Draggable UI": "Перацягвальны інтэрфейс",
    "Draw Over UI": "Адлюстроўваць паверх інтэрфейсу",
    "Draws the minimap over all other UI elements for improved visibility.": "Адлюстроўваць міні-карту паверх усіх элементаў інтэрфейсу для лепшай бачнасці.",
    "dropdown": "Выпадальнае меню",
    "Duration": "Працягласць",
    "Easier Access": "Больш зручны доступ",
    "Easy": "Лёгкі",
    "Elevation Markers": "Маркеры вышыні",
    "en": "en",
    "Enable": "Уключыць",
    "Enable sounds in arcade games.": "Уключыце гукі ў аркадных гульнях.",
    "Enabled": "Уключана",
    "Enemy": "Вораг",
    "Enemy healthbar enhancements.": "Паляпшэнні HP-бары ворага.",
    "Enemy HP Warning": "Папярэджанне пра здароўе ворага",
    "English": "Ангельскі",
    "Enhanced V2 enemy healthbar visuals and readability.": "Палепшаны стыль HP-бараў v2.",
    "error": "памылка",
    "ERROR: Invalid String": "ПАМЫЛКА: няправільны радок",
    "Estimated ult cooldowns under top-bar ult icons": "Прыблiзны час аднаўлення ульт пад значкамі ультоў на верхняй панэлі",
    "Export Settings": "Экспарт налад",
    "Export String": "Радок экспарту",
    "Export string copied.": "Радок экспарту скапіяваны.",
    "F": "Ф",
    "FAILED": "НЯЎДАЧА",
    "Failed Hint": "Памылка падказкі",
    "Failed to queue save request.": "Не атрымалася паставіць запыт на захаванне ў чаргу.",
    "Failed to switch hero.": "Не ўдалося змяніць героя.",
    "Fighting Game": "Fighting Game",
    "Filters": "Фільт",
    "Find all safe tiles. Right-click to flag.": "Знайдзіце ўсе бяспечныя пліткі. Пстрыкніце правай кнопкай мышы, каб адзначыць сцяжок.",
    "Fire Rate: --": "Хуткасць Стральбы: --",
    "First Spawns": "Першыя спаўны",
    "Flags:": "Сцягі:",
    "Flappy Bat": "Flappy Bat",
    "Flip": "Падкінуць",
    "For custom BHop gamemode UI changes.": "Для карыстальніцкіх змен інтэрфейсу ў рэжыму BHop.",
    "Force Testing Tools": "Інструменты прымусовага тэставання",
    "Forcibly hides testing tools at all times.": "Примусова хавае інструменты тэставання ў любы час.",
    "Forcibly shows testing tools at all times.": "Примусова адлюстроўвае інструменты тэставання ў любы час.",
    "Fountain-style damage number animation.": "Анімацыя лічбаў урону ў стылі фантана.",
    "FPS Impact:": "Уплыў на FPS:",
    "French": "Французскі",
    "Full Keybinds": "Поўныя кейбайнды",
    "Full Keys": "Поўныя клавішы",
    "Game Audio": "Аўдыё гульні",
    "Game Settings": "Налады гульні",
    "Gamemodes": "Рэжымы гульні",
    "Games": "Гульні",
    "General": "Агульнае",
    "Get Filter": "Атрымаць фільтр",
    "Get Filter File Only": "Атрымаць толькі файл фільтра",
    "Graves Trainer": "Graves Trainer",
    "Greys out heros in the top bar when missing on the map.": "Шарэе герояў у верхняй панэлі, калі яны адсутнічаюць на карце.",
    "Hard": "Цяжка",
    "Health Numbers": "Лічбы здароўя",
    "Healthbar": "HP-бары",
    "Help and feedback": "Дапамога і зваротная сувязь",
    "Help fund continued development": "Дапамажы фінансаваць далейшую распрацоўку",
    "Help, Contact & Support": "Дапамога, кантакты і падтрымка",
    "Help, feedback, and community": "Дапамога, зваротная сувязь і супольнасць",
    "Hero": "Герой",
    "Hero Icon Size": "Памер значка героя",
    "Hero on Load or Save": "Герой пры загрузцы або захаванні",
    "Hide Ability Suggestion": "Схаваць падказку умення",
    "Hide All": "Схаваць усе",
    "Hide Behavior Summary": "Схаваць зводку паводзін",
    "Hide Big Number": "Схаваць вялікую лічбу",
    "Hide Blur": "Схаваць размыццё",
    "Hide Circle": "Схаваць круг",
    "Hide Cosmetic Ability": "Схаваць касметычнае уменне",
    "Hide Current": "Схаваць бягучае",
    "Hide Damage Report": "Схаваць справаздачу аб уроне",
    "Hide Failed Hint": "Схаваць падказку аб няўдачы",
    "Hide Icon": "Схаваць значок",
    "Hide Quick Buy": "Схаваць хуткую купліку",
    "Hide Small Numbers": "Схаваць малыя лічбы",
    "Hide Testing Tools": "Схаваць інструменты тэставання",
    "Hide Total": "Схаваць агульнае",
    "Hide Trooper Damage": "Схаваць урон трупера",
    "High": "Высокі",
    "HIGH FPS IMPACT WARNING!": "УВАГА! ВЫСОКІ ЎПЛЫЎ НА FPS!",
    "Highlight Mode": "Рэжым падсветкі",
    "Highlight regeneration in red for when in combat.": "Падсвечвае рэгенерацыю чырвоным падчас бою.",
    "Highlighted abilities showing you what you should upgrade depending on build.": "Падсвечвае уменні, паказваючы што варта ўзмацніць у залежнасці ад білда.",
    "Hit": "Трапленне",
    "Hitmarkers": "Хітмаркеры",
    "Hits:": "Трапленні:",
    "Horizontal Offset": "Гарызантальнае зрушэнне",
    "Horizontal Stretch": "Гарызантальнае расцяжэнне",
    "How fast the minimap refreshes.": "Як хутка абнаўляецца міні-карта.",
    "How much icons will shrink when overlapping with others.": "Наколькі іконкі будуць зменшвацца пры перакрыцці з іншымі.",
    "How to Save Settings": "Як захаваць налады",
    "HP Warning": "Папярэджанне аб HP",
    "HUD": "HUD",
    "HUD Controls": "Кіраванне HUD",
    "Hud Shift": "Зрух HUD",
    "I am open to all feedback, suggestions, and ideas!": "Я адкрыты да любой зваротнай сувязі, прапаноў і ідэй!",
    "Icon": "Іконка",
    "Icon Shrink": "Памяншэнне іконкі",
    "Icons": "Іконкі",
    "If saving stalls, open your shop.": "Калі захаванне завісла, адкрый свой магазін.",
    "If you encounter issues please join the Discord": "Калі ўзніклі праблемы, далучайся да Discord",
    "If you encounter issues, need help, or have any feedback join the Discord.": "Калі ўзніклі праблемы, патрэбна дапамога, або ёсць зваротная сувязь — далучайся да Discord.",
    "Images in Chat": "Выявы ў чаце",
    "Import failed.": "Не ўдалося выканаць імпарт.",
    "Import Settings": "Імпарт налад",
    "Import String": "Імпартаваць радок",
    "Import: applying settings...": "Імпарт: Ужыванне налад...",
    "Import: parsing string...": "Імпарт: апрацоўка радка...",
    "Import: refreshing UI...": "Імпарт: абнаўленне інтэрфейсу...",
    "Improve Ability Stacks": "Паляпшэнне стэкаў умення",
    "Improved Hint": "Палепшаная падказка",
    "IN COMBAT": "У БОІ",
    "In Seconds": "У секундах",
    "info": "інфармацыя",
    "Invalid import string.": "Няправільны радок імпарту.",
    "Issues, Feedback and Ideas": "Праблемы, зваротная сувязь і ідэі",
    "Item Cooldowns": "Кулдауны прадметаў",
    "Item Target Reticle": "Прыцэл прадмета",
    "Japanese": "Японскі",
    "Keyboard": "Клавіятура",
    "Klutz's Bar": "Бар Клатца",
    "Lane with Party": "Лэйніць з пачком",
    "Language": "Мова",
    "Latest updates and version notes": "Апошнія абнаўленні і нататкі версіі",
    "Legacy Durations": "Устарэлыя працягласці",
    "Light Item Cooldowns": "Лёгкія кулдауны прадметаў",
    "Local settings loaded.": "Лакальныя налады загружаны.",
    "Loud": "Гучны",
    "Low": "Нізкі",
    "Low Stamina Popup": "Папап нізкай вынослівасці",
    "Makes the minimap rotate with player view, this is just for fun.": "Павярочвае міні-карту разам з аглядам гульца — проста для забавы.",
    "Max Health: --": "Макс. здароўе: --",
    "Max Notifications": "Макс. апавяшчэнняў",
    "Medium": "Сярэдні",
    "Menu when you receive a punishment for breaking game rules.": "Меню, якое з'яўляецца пры атрыманні пакарання за парушэнне правіл гульні.",
    "Meta Settings": "Мета налады",
    "Metro Button": "Кнопка метро",
    "Mid Boss Timer": "Таймер мід боса",
    "Midtown-only crate markers on the minimap.": "Маркеры скрынь толькі для Мідтауна на міні-карце.",
    "Mines:": "Міны:",
    "Minimalist": "Мінімалісцкі",
    "Minimalist Abilities": "Мінімалістычныя уменні",
    "Minimalist Healthbar": "Мінімалістычы HP-бар",
    "Minimalist Item Bar": "Мінімалістычная паласа прадметаў",
    "Minimalist Minimap": "Мінімалістычная міні-карта",
    "Minimalist Opacity": "Мінімалістычная празрыстасць",
    "Minimap": "Мінімапа",
    "Minimap Reminder": "Напамін мінімапы",
    "Mirror unsecured gold number": "Адлюстраваць лічбу незабяспечанага золата",
    "Misses:": "Прамахі:",
    "Missing Hero Opaque": "Адсутны герой непразрысты",
    "Modify damage numbers for a cleaner style and animation to be more out of the way": "Змяняе лічбы ўрону для больш акуратнага стылю і анімацыі, каб яны менш замінялі",
    "MOG is Deadlock's first custom gamemode community server network.": "MOG — першая сеткавая супольнасць кастомных рэжымаў Deadlock.",
    "moglock.gg": "moglock.gg",
    "Move ability stacks to bottom-center of ability icon": "Перамясціць стэкі умення ў ніжні цэнтр іконкі умення",
    "Move ability stacks to bottom-center of ability icon.": "Перамясціць стэкі умення ў ніжні цэнтр іконкі умення",
    "Move notifications around Rejuvenator and Scoreboard UI.": "Перамясціць апавяшчэнні вакол інтэрфейсу Рэжувенатара і табліцы вынікаў.",
    "Moves the Bridge Buff timer onto the bridge with two smaller centered copies.": "Перамяшчае таймер Руны на мост з двума меншымі цэнтраванымі копіямі.",
    "Moves the element horizontally.": "Перамяшчае элемент гарызантальна.",
    "Moves the element vertically.": "Перамяшчае элемент вертыкальна.",
    "Moves the Mid Boss timer onto the bridge area of the minimap.": "Перамяшчае таймер мід боса на вобласць моста міні-карты.",
    "multitoggle": "множынны пераключальнік",
    "N/A": "Н/Д",
    "Neutral Camps": "Нейтральныя лагеры",
    "New Feature Commission: <font color=\"#66cc99\">$10</font> to <font color=\"#66cc99\">$100</font>": "Камісія за новую функцыю: <font color=\"#66cc99\">$10</font> да <font color=\"#66cc99\">$100</font>",
    "New Game": "Новая гульня",
    "New Hand": "Новая рука",
    "New Run": "Новы запуск",
    "Nicknames": "Нікнеймы",
    "No color wash": "Без змывання колеру",
    "No filter settings but better FPS.": "Без налад фільтра, але лепшы FPS.",
    "No results found": "Вынікаў не знойдзена",
    "No setting changes detected.": "Змен налад не выяўлена.",
    "None": "Няма",
    "Normal": "Звычайны",
    "Notify your teammates in chat about how close you are to a quickbuy purchase.": "Апавяшчае тымейтаў у чаце аб тым, наколькі блізка ты да хуткай купліі.",
    "Objective Damage": "Урон па аб'ектах",
    "Objective Map": "Карта аб'ектаў",
    "Off": "Выкл.",
    "Offensive Active": "Актыўныя атакавальныя",
    "Offensive Passive": "Пасіўныя атакавальныя",
    "On": "Укл.",
    "On Ability Upgrade": "Пры ўзмацненні умення",
    "On Death": "Пры смерці",
    "On Death Games": "Гульні пры смерці",
    "Only download the filter file of the filter you want, nothing else.": "Спампуй толькі файл патрэбнага фільтра, нічога іншага.",
    "Opacity": "Празрыстасць",
    "Opacity of the background of Minimalist Minimap.": "Празрыстасць фону мінімалістычнай міні-карты.",
    "Opacity of the underground tunnel overlay while Alt Zoom is active.": "Празрыстасць налажэння падземнага тунэля пры актыўным Alt Zoom.",
    "Opacity of the underground tunnel overlay while Tab Zoom is active.": "Празрыстасць налажэння падземнага тунэля пры актыўным Tab Zoom.",
    "Opacity of the underground tunnel overlay.": "Празрыстасць налажэння падземнага тунэля.",
    "Open": "Адкрыць",
    "Open Config": "Адкрыць канфігурацыю",
    "Open random game when dead": "Адкрыць выпадковую гульню пры смерці",
    "Open Settings": "Адкрыць налады",
    "Open shop to continue clear.": "Адкрый магазін, каб працягнуць ачыстку.",
    "Open shop to continue save.": "Адкрый магазін, каб працягнуць захаванне.",
    "Optimize Filters": "Аптымізаваць фільтры",
    "Optimize Mode": "Рэжым аптымізацыі",
    "Overlay": "Налажэнне",
    "palette": "палітра",
    "Paste and apply an exported settings string": "Устаўце і ўжыце экспартаваны радок налад",
    "Play": "Гуляць",
    "Play an audio reminder to remember to look at the minimap.": "Прайграе гукавы напамін, каб памятаць глядзець на міні-карту.",
    "Play current announcer voice and volume.": "Прайграць бягучы голас і гучнасць дыктара.",
    "Play current announcer voice.": "Прайграць бягучы голас дыктара.",
    "Play Sound": "Прайграць гук",
    "Play When On Death Enabled": "Прайграваць пры ўключаным рэжыме смерці",
    "Player": "Гулец",
    "Player Icon Size": "Памер іконкі гульца",
    "Polish": "Польскі",
    "Portuguese": "Партугальскі",
    "Position and Velocity real time statistics.": "Статыстыка пазіцыі і хуткасці ў рэальным часе.",
    "Preset apply failed.": "Не атрымалася ўжыць прэсет.",
    "Presets": "Прэсеты",
    "Preview": "Папярэдні прагляд",
    "Preview Announcer": "Папярэдні прагляд дыктара",
    "Preview Changes": "Папярэдні прагляд змен",
    "Preview realtime changes to settings when modifying them.": "Папярэдні прагляд змен налад у рэальным часе пры іх змене.",
    "Preview setting changes in realtime.": "Прагляд змен налад у рэальным часе.",
    "Push - Both have blackjack.": "Нічыя — у абодвух блэкджэк.",
    "Push.": "Нічыя.",
    "Q": "Q",
    "QOL": "QOL",
    "QOL Settings Clearer": "Ачышчальнік QOL налад",
    "QOL Settings Loader": "Загрузчык QOL налад",
    "QOL Settings Saver": "Захавальнік QOL налад",
    "Quick Buy": "Хуткая купля",
    "Quiet": "Ціха",
    "Ragnarok Online damage visuals with improved fancy styling.": "Візуалы ўрону з Ragnarok Online з палепшаным стыльным афармленнем.",
    "RAM and GPU Memory real time usage statistics.": "Статыстыка выкарыстання RAM і памяці GPU у рэальным часе.",
    "Randomly opens an enabled arcade game while dead.": "Выпадкова адкрывае ўключаную аркадную гульню падчас смерці.",
    "Ready": "Гатова",
    "Ready.": "Гатова.",
    "Real time key input visual.": "Візуал уводу клавіш у рэальным часе.",
    "Realtime Changes": "Змены ў рэальным часе",
    "Realtime Drain Countdown": "Зваротны адлік расходу ў рэальным часе",
    "Realtime Key Inputs": "Увод клавіш у рэальным часе",
    "Realtime Settings Changes": "Змены налад у рэальным часе",
    "Recommended for 4:3": "Рэкамендавана для 4:3",
    "Refresh Rate": "Частата абнаўлення",
    "Reload Cooldown": "Кулдаун перазарадкі",
    "Reloading": "Перазарадка",
    "Rem Tunnels": "Тунэлі Рэма",
    "Rem Tunnels Opacity": "Празрыстасць тунэляў Рэма",
    "Remind when big camps and Sinner's Sacrifice are spawning.": "Нагадвае, калі буйныя лагеры і казіно адраджаюцца.",
    "Remind when bridge buffs and melee troopers are spawning.": "Нагадвае, калі Руны і мілішныя труперы адраджаюцца.",
    "Remind when bridge buffs are spawning.": "Нагадвае, калі Руны адраджаюцца.",
    "Remind when bridge buffs spawn and gold statue buffs are maxed.": "Нагадвае, калі Руны адраджаюцца і бафы залатых статуі дасягаюць максімуму.",
    "Remind when bridge buffs spawn and troopers improve again.": "Нагадвае, калі Руны адраджаюцца і труперы зноў узмацняюцца.",
    "Remind when bridge buffs spawn and troopers speed up.": "Нагадвае, калі Руны адраджаюцца і труперы паскараюцца.",
    "Remind when lane guardian resistance is reduced.": "Нагадвае, калі супраціўленне гвардыяна лэйна зніжаецца.",
    "Remind when medium camps are spawning.": "Нагадвае, калі сярэднія лагеры адраджаюцца.",
    "Remind when midboss, urn, bridge buffs, and gold statue upgrades are spawning.": "Нагадвае, калі мід бос, урна, Руны і апгрэйды залатой статуі адраджаюцца.",
    "Remind when small camps, boxes, and statues are spawning.": "Нагадвае, калі малыя лагеры, скрыні і статуі адраджаюцца.",
    "Remind when walker resistance is reduced.": "Нагадвае, калі супраціўленне воукера зніжаецца.",
    "Render image URLs as images.": "Адлюстроўваць URL выяў як выявы.",
    "Replaces quickbuy with the Enhanced Quickbuy standalone layout and queue summaries.": "Замяняе хуткую куплю на аўтаномны макет Паляпшанай Хуткай Купліі і зводкі чэргаў.",
    "Reposition": "Перамяшчэнне",
    "Request a community preset": "Запытаць прэсет супольнасці",
    "Request a custom feature or preset": "Запытаць кастомную функцыю або прэсет",
    "Reset row to defaults": "Скінуць радок да стандартных значэнняў",
    "Reset section runtime options": "Скінуць параметры запуску секцыі",
    "Reset section to defaults": "Скінуць секцыю да стандартных значэнняў",
    "Reset settings:": "Скінуць налады:",
    "Reset to default value": "Скінуць да значэння па змаўчанні",
    "Reset to default value.": "Скінуць да значэння па змаўчанні.",
    "Restores the legacy removed duration bars for abilities.": "Аднаўляе ўстарэлыя выдаленыя паласы працягласці для уменняў.",
    "Retheme the settings menu, modals, loader, and save menus with a shared aesthetic.": "Змяняе тэму меню налад, мадальных вокнаў, загрузчыка і меню захавання ў адзіным стылі.",
    "Rotate": "Павярнуць",
    "Rotate the stamina charge indicator.": "Павярнуць індыкатар зарада вынослівасці.",
    "Rotates the static minimap 180 degrees.": "Павярочвае статычную міні-карту на 180 градусаў.",
    "Row already at defaults.": "Радок ужо на стандартных значэннях.",
    "Row reset (": "Скід радка (",
    "Run complete. Press New Run.": "Запуск завершаны. Націсніце Новы запуск.",
    "Russian": "Руская",
    "SAVE": "ЗАХАВАЦЬ",
    "Save": "Захаваць",
    "Save completed.": "Захаванне завершана.",
    "Save failed.": "Не атрымалася захаваць.",
    "Save in progress...": "Захаванне ў працэсе...",
    "Save queued.": "Захаванне ў чарзе.",
    "Save timed out. Try again.": "Захаванне перавысіла час чакання. Паспрабуй яшчэ раз.",
    "Save works only in hideout.": "Захаванне працуе толькі ў хайдауце.",
    "SAVED": "ЗАХАВАНА",
    "Scale": "Маштаб",
    "Scales the element.": "Маштабуе элемент.",
    "Score:": "Лік:",
    "Scoreboard Open": "Табліца вынікаў адкрыта",
    "Search Results": "Вынікі пошуку",
    "Seconds Before Spawn": "Секунды да адраджэння",
    "Seconds each notification stays visible.": "Колькасць секунд, якое кожнае апавяшчэнне застаецца бачным.",
    "Section already at defaults.": "Секцыя ужо на стандартных значэннях.",
    "Section reset (": "Скід секцыі (",
    "See the recent purchases made in the game.": "Паказвае апошнія пакупкі, зробленыя ў гульні.",
    "See your view angle and speed.": "Паказвае вугал агляду і хуткасць.",
    "Settings Changes": "Змены налад",
    "Settings now load from your saved build string": "Налады зараз загружаюцца з захаванага радка білда",
    "Settings UI Language": "Мова інтэрфейсу налад",
    "Share or save your settings configuration!": "Падзяліся або захавай канфігурацыю сваіх налад!",
    "Share your settings string": "Падзяліся радком сваіх налад",
    "Shifts the HUD for better visual support for 16:10 resolutions.": "Зрушвае HUD для лепшай візуальнай падтрымкі дазволу 16:10.",
    "Shifts the HUD for better visual support for 4:3 resolutions.": "Зрушвае HUD для лепшай візуальнай падтрымкі дазволу 4:3.",
    "Shop": "Магазін",
    "Show a short caption when Deadlock For Dummies reminders play.": "Паказвае кароткі подпіс, калі прайграваюцца напаміны Deadlock For Dummies.",
    "Show a visual indicator in the top bar of the current Guardians, Walkers, and Base.": "Паказвае візуальны індыкатар у верхняй панэлі бягучых Гвардыянаў, Воукераў і Базы.",
    "Show an overlay of the underground tunnels.": "Паказвае налажэнне падземных тунэляў.",
    "Show Compass": "Паказаць компас",
    "Show current / max HP numbers over the Minecraft hearts.": "Паказвае бягучыя / максімальныя лічбы HP над сэрцамі Minecraft.",
    "Show Filters": "Паказаць фільтры",
    "Show FPS": "Паказаць FPS",
    "Show Frame": "Паказаць рамку",
    "Show Icon": "Паказаць іконку",
    "Show if you are in combat or not.": "Паказвае, знаходзішся ты ў баі ці не.",
    "Show level text on V2 enemy healthbars.": "Паказвае тэкст узроўню на HP-барах ворагаў V2.",
    "Show Memory": "Паказаць памяць",
    "Show player ultimate indicators on V1 healthbars.": "Паказвае індыкатары ультымейту гульца на V1 HP-барах.",
    "Show Position": "Паказаць пазіцыю",
    "Show Speed": "Паказаць хуткасць",
    "Show Support": "Паказаць падтрымку",
    "Show Testing Tools": "Паказаць інструменты тэставання",
    "Show Text": "Паказаць тэкст",
    "Show the estimated time for unsecured souls to dissapear.": "Паказвае прыблізны час да знікнення незабяспечаных душ.",
    "Show the in-game chat panel.": "Паказвае панэль чата ў гульні.",
    "Show the ultimate indicator for V1 healthbars.": "Паказвае індыкатар ультымейту на V1 HP-барах.",
    "Show the underground tunnel overlay while Alt Zoom is active.": "Паказвае налажэнне падземных тунэляў пры актыўным Alt Zoom.",
    "Show the underground tunnel overlay while Tab Zoom is active.": "Паказвае налажэнне падземных тунэляў пры актыўным Tab Zoom.",
    "Show the UnitInfo panel on V2 enemy healthbars.": "Паказвае панэль UnitInfo на V2 HP-барах ворагаў.",
    "Show Tick": "Паказаць тык",
    "Show Title": "Паказаць загаловак",
    "Showing:": "Паказваецца:",
    "Shown Items": "Адлюстраваныя прадметы",
    "Shows a visual indicator in the minimap of when Bridge Buffs will spawn.": "Паказвае візуальны індыкатар на міні-карце, калі адродзяцца Руны.",
    "Shows a visual indicator in the minimap of when Mid Boss will spawn.": "Паказвае візуальны індыкатар на міні-карце, калі адродзіцца мід бос.",
    "Shows a visual indicator in the top bar of the percentage difference of souls between teams.": "Паказвае візуальны індыкатар у верхняй панэлі працэнтнай розніцы душ паміж камандамі.",
    "Shows a visual indicator in the top bar of when Bridge Buffs will spawn.": "Паказвае візуальны індыкатар у верхняй панэлі, калі адродзяцца Руны.",
    "Shows a visual indicator in the top bar of when Mid Boss will spawn.": "Паказвае візуальны індыкатар у верхняй панэлі, калі адродзіцца мід бос.",
    "Shows all of your keybinds.": "Паказвае ўсе твае кейбайнды.",
    "Shows all of your player stats within the shop menu.": "Паказвае ўсе паказчыкі гульца ў меню магазіна.",
    "Shows current frame count, mostly useless.": "Паказвае бягучы лічыльнік фрэймаў, у асноўным бескарысна.",
    "Shows item buy notifications from recent purchases.": "Паказвае апавяшчэнні аб пакупках для апошніх прадметаў.",
    "Shows item cooldowns near crosshair for easier readability.": "Паказвае кулдауны прадметаў каля крыжыка для зручнасці чытання.",
    "Shows Midtown crate markers in the minimap.": "Паказвае маркеры скрынь Мідтауна на міні-карце.",
    "Shows nicknames of all players in the game within the top bar.": "Паказвае нікнеймы ўсіх гульцоў у гульні ў верхняй панэлі.",
    "Shows raw FPS count.": "Паказвае дакладны лічыльнік FPS.",
    "Shows real time tick information, mostly useless.": "Паказвае інфармацыю аб тыках у рэальным часе, у асноўным бескарысна.",
    "Shows relative elevation difference between you and players.": "Паказвае адносную розніцу вышыні паміж табой і гульцамі.",
    "Shows the angle degrees and ticks.": "Паказвае градусы вугла і тыкі.",
    "Shows the individual player souls per minute on scoreboard and the team in the top bar.": "Паказвае індывідуальныя душы гульца за хвіліну на табліцы вынікаў і каманду ў верхняй панэлі.",
    "Shows the individual player's objective damage in the top bar.": "Паказвае індывідуальны ўрон па аб'ектах гульца ў верхняй панэлі.",
    "Shows the individual player's unspent souls in the top bar.": "Паказвае індывідуальныя нявыдаткаваныя душы гульца ў верхняй панэлі.",
    "Shows your build information always for content creators": "Заўсёды паказвае інфармацыю аб білдзе для кантэнт-крэйтараў",
    "Shows your character in the shop menu.": "Паказвае твайго персанажа ў меню магазіна.",
    "Shrink Distance": "Адлегласць памяншэння",
    "Significantly improve visibility of target reticle and highlight for execute ranges (Shiv).": "Значна паляпшае бачнасць прыцэла і падсветкі для дыяпазонаў выкананання (Shiv).",
    "Simplified Minimap": "Спрошчаная міні-карта",
    "Simplifies the Compass overlay to its bare elements.": "Спрашчае налажэнне компаса да яго базавых элементаў.",
    "Simplify": "Спрасціць",
    "Simplify Ability Icons": "Спрасціць іконкі уменняў",
    "Simplify Items": "Спрасціць прадметы",
    "Simplify Shop": "Спрасціць магазін",
    "Size": "Памер",
    "Size of your current ammo.": "Памер бягучага боезапасу.",
    "Size of your total ammo.": "Памер агульнага боезапасу.",
    "Slight adjustments to the HUD for better streaming output.": "Невялікія карэктывы HUD для лепшага выхаду трансляцыі.",
    "Small Numbers": "Малыя лічбы",
    "Snowball or Poster": "Сняжок або постэр",
    "Souls Per Minute": "Душы за хвіліну",
    "Souls Timer": "Таймер душ",
    "Spanish": "Іспанская",
    "Special Thanks": "Асаблівая падзяка",
    "Speed": "Хуткасць",
    "Speed number tracker.": "Трэкер хуткасці.",
    "Spinny Map": "Круцячаяся карта",
    "Spinny Mode": "Рэжым кручэння",
    "Spirit Power: --": "Спірытычная моц: --",
    "Stamina": "Вынослівасць",
    "Stand": "Стойка",
    "Stat Bonuses": "Бонусы паказчыкаў",
    "Statistics": "Статыстыка",
    "Statlocker": "Statlocker",
    "Stats": "Статы",
    "Streak:": "Серыя:",
    "Stretch the compass horizontally.": "Расцягнуць компас гарызантальна.",
    "Stretch the compass vertically.": "Расцягнуць компас вертыкальна.",
    "Strings may sometimes break between mod versions.": "Радкі часам могуць ламацца паміж версіямі мода.",
    "success": "поспех",
    "Support": "Падтрымка",
    "Support development": "Падтрымаць распрацоўку",
    "Support development by commissioning features or presets.": "Падтрымай распрацоўку, заказваючы функцыі або прэсеты.",
    "SUPPORT THE MOD": "ПАДТРЫМАЙ МОД",
    "Support the mod - donate via Ko-fi (kofi) to help fund continued development": "Падтрымай мод — задонать праз Ko-fi (kofi), каб дапамагчы фінансаваць далейшую распрацоўку",
    "Supporting and Feature Requests": "Падтрымка і запыты функцый",
    "Swap": "Замяніць",
    "Switch to the advanced item cooldown mode with in-menu filters.": "Пераключыцца на прасунуты рэжым кулдаунаў прадметаў з фільтрамі ў меню.",
    "Switching to Skyrunner...": "Пераключэнне на Skyrunner...",
    "Tab Zoom": "Tab Zoom",
    "Test": "Тэст",
    "Test Announcer": "Тэставы дыктар",
    "Text": "Тэкст",
    "The circle countdown for when you are reloading.": "Кругавы адлік падчас перазарадкі.",
    "The click hitbox of your pings or clicks, this can help make pings more accurate.": "Хітбокс кліку тваіх пінгоў або клікаў, гэта можа дапамагчы зрабіць пінгі больш дакладнымі.",
    "The cosmetic ability on your default 5 key, like posters and snowballs.": "Касметычнае уменне на тваёй стандартнай клавішы 5, як постэры і сняжкі.",
    "The damage dealt to Trooper minions.": "Урон, нанесены мініёнам трупераў.",
    "The displayed language of the settings menu.": "Адлюстроўваная мова меню налад.",
    "The distance threshold in which icons will start shrinking. Lower is more accurate positions, higher is easier visibility.": "Парог адлегласці, пры якім іконкі пачнуць памяншацца. Ніжэй — больш дакладныя пазіцыі, вышэй — лепшая бачнасць.",
    "The hero you automatically switch to on launch or after saving..": "Герой, на якога ты аўтаматычна пераключаешся пры запуску або пасля захавання.",
    "The icon that replaces your crosshair when reloading.": "Іконка, якая замяняе твой крыжык падчас перазарадкі.",
    "The interval in which the sound plays in seconds.": "Інтэрвал, з якім гук прайграваецца, у секундах.",
    "The item buying auto queue system in the shop menu.": "Сістэма аўтаматычнай чэргі куплі прадметаў у меню магазіна.",
    "The large cumulative damage number.": "Вялікая кумулятыўная лічба ўрону.",
    "The line has been reset (": "Радок быў скінуты (",
    "The majority of issues are caused by improper installation or conflicting mods.": "Большасць праблем выкліканы няправільнай усталёўкай або канфліктуючымі модамі.",
    "The mod is <font color=\"#66cc99\">fully functional</font> and <font color=\"#66cc99\">free</font> for all users.": "Мод з'яўляецца <font color=\"#66cc99\">поўнасцю функцыянальным</font> і <font color=\"#66cc99\">бясплатным</font> для ўсіх карыстальнікаў.",
    "The popup signifying you are too low on stamina to cast another movement input.": "Папап, які сігналізуе, што ў цябе занадта мала вынослівасці для яшчэ аднаго руху.",
    "The popups that appear when getting a kill or CCing an enemy or healing an ally": "Папапы, якія з'яўляюцца пры забойстве, кантролі ворага або лячэнні саюзніка",
    "The size of other players on the minimap.": "Памер іншых гульцоў на міні-карце.",
    "The size of yourself on the minimap.": "Памер цябе самога на міні-карце.",
    "The small incremental damage numbers.": "Малыя інкрэментальныя лічбы ўрону.",
    "The small visual icon.": "Малая візуальная іконка.",
    "The thickness of the Zipline lines across the map.": "Таўшчыня ліній Зіплайна па ўсёй карце.",
    "The unsecured text.": "Незабяспечаны тэкст.",
    "The world background blur effect behind the shop menu.": "Эфект размыцця фону свету за меню магазіна.",
    "The world blur and backing strip behind player names in the top bar.": "Размыццё свету і фонавая паласа за імёнамі гульцоў у верхняй панэлі.",
    "The world blur behind player names in the top bar.": "Размыццё свету за імёнамі гульцоў у верхняй панэлі.",
    "Theme": "Тэма",
    "These are easy access to common console commands and are not included in QOL settings.": "Гэта зручны доступ да агульных каманд кансолі і не ўваходзяць у QOL налады.",
    "This is a lightweight version with significant FPS improvements but requires a seperate file for filters.": "Гэта лёгкая версія са значным паляпшэннем FPS, але патрабуе асобны файл для фільтраў.",
    "This is a mod designed to give you complete freedom over your game.": "Гэта мод, распрацаваны, каб даць табе поўную свабоду над сваёй гульнёй.",
    "This is a way for me to give something back to the supporters.": "Гэта спосаб аддзячыць прыхільнікам.",
    "This is to switch to the Skyrunner hero (looks like Paradox), your settings are saved in the shop builds. To troubleshoot you can delete these and do a fresh save to fix any settings saving issues.": "Гэта для пераключэння на героя Skyrunner (выглядае як Paradox), твае налады захаваны ў білдах магазіна. Для ліквідацыі непаладак ты можаш выдаліць іх і зрабіць новае захаванне, каб выправіць любыя праблемы з захаваннем налад.",
    "This line is already on by default.": "Гэты радок ужо ўключаны па змаўчанні.",
    "This section is already on by default.": "Гэта секцыя ўжо ўключана па змаўчанні.",
    "Tier 1": "Узровень 1",
    "Tier 2": "Узровень 2",
    "Tier 3": "Узровень 3",
    "Time before the announcement happens in seconds.": "Час да абвяшчэння ў секундах.",
    "Time:": "Час:",
    "Timed audio reminders from Deadlock For Dummies.": "Часавыя гукавыя напаміны ад Deadlock For Dummies.",
    "TIMEOUT": "ТАЙМ-АУТ",
    "Timer": "Таймер",
    "Toggle the hitmarkers when attacking enemies.": "Уключыць/выключыць хітмаркеры пры атацы ворагаў.",
    "Tools for showing and sharing item purchase notifications.": "Інструменты для адлюстравання і абмену апавяшчэннямі аб куплі прадметаў.",
    "Tools for tracking recent item purchases.": "Інструменты для адсочвання апошніх пакупак прадметаў.",
    "Top Bar": "Верхняя панэль",
    "Top Bar Background": "Фон верхняй панэлі",
    "Top Bar Plus": "Верхняя панэль Plus",
    "Total": "Агульнае",
    "Total ammo amount.": "Агульная колькасць боезапасу.",
    "Total Size": "Агульны памер",
    "Total:": "Агульнае:",
    "Total: --": "Агульнае: --",
    "Tracked cooldowns near crosshair": "Адсочваемыя кулдауны каля крыжыка",
    "Translators": "Перакладчыкі",
    "Trooper Damage": "Урон трупера",
    "Troubleshoot": "Ліквідацыя непаладак",
    "Type": "Тып",
    "UI": "Інтэрфейс",
    "UI Controls": "Кіраванне інтэрфейсам",
    "Ukrainian": "Украінская",
    "Ult Cooldowns": "Кулдауны ульта",
    "Ult Indicator": "Індыкатар ульта",
    "Unsecured Plus": "Незабяспечаны Plus",
    "Unsecured Souls": "Незабяспечаныя душы",
    "Unsecured Souls Timer": "Таймер незабяспечаных душ",
    "Unsecured Timer": "Незабяспечаны таймер",
    "Unspent Souls": "Нявыдаткаваныя душы",
    "Urn Colors": "Колеры урны",
    "Urn Difference": "Розніца урны",
    "Use autoexec or other methods to load these automatically.": "Выкарыстоўвай autoexec або іншыя метады для аўтаматычнай загрузкі.",
    "V2 enemy healthbar enhancements.": "V2 HP-бара ворага.",
    "Vertical Offset": "Вертыкальнае зрушэнне",
    "Vertical Stretch": "Вертыкальнае расцяжэнне",
    "View a cooldown timer for reloading time.": "Паказвае таймер кулдауна для часу перазарадкі.",
    "View an enhanced minimap on opening ability menu.": "Паказвае палепшаную міні-карту пры адкрыцці меню уменняў.",
    "View an enhanced minimap on opening scoreboard menu.": "Паказвае палепшаную міні-карту пры адкрыцці меню табліцы вынікаў.",
    "View the cooldown time of player ultimates.": "Паказвае час кулдауна ультымейтаў гульцоў.",
    "View updates": "Прагляд абнаўленняў",
    "Visual": "Візуал",
    "Visual indicator of your current ammo.": "Візуальны індыкатар бягучага боезапасу.",
    "Voice": "Голас",
    "Voice Actor:": "Акцёр агучкі:",
    "Volume": "Гучнасць",
    "Volume for Deadlock For Dummies reminder audio.": "Гучнасць гукавых напамінаў Deadlock For Dummies.",
    "warning": "папярэджанне",
    "Weapon Damage %: --": "Урон зброі %: --",
    "Welcome to QOL Lock": "Вітаем у QOL Lock",
    "Which events cause a sound to play. Camps are one time, Buff is every 5 minutes.": "Якія падзеі выклікаюць прайграванне гуку. Лагеры — адзін раз, Руна — кожныя 5 хвілін.",
    "Without them QOL Lock would not be possible.": "Без іх QOL Lock быў бы немагчымы.",
    "Wraithjack": "Wraithjack",
    "Writing settings string to build...": "Запіс радка налад у білд...",
    "XQC": "XQC",
    "yoshii pls hire me": "yoshii калі ласка вазьмі мяне на працу",
    "You can download custom announcer packs, just download the correct one for the slot you want to replace.": "Ты можаш спампаваць кастомныя пакеты дыктара, проста спампуй патрэбны для слота, які хочаш замяніць.",
    "You can support development by commissioning features or presets.": "Ты можаш падтрымаць распрацоўку, заказваючы функцыі або прэсеты.",
    "You win.": "Ты перамог.",
    "Zerggy Mania": "Zerggy Mania",
    "ZIP BOOST": "ZIP BOOST",
    "Zip Boost": "Zip Boost",
    "Zip Thickness": "Zip Thickness",
    "Zipline Boost": "Zipline Boost",
    "Ability Duration": "Працягласць здольнасцей",
    "Ability Range": "Далькасць здольнасцей",
    "Bullet Evasion": "Ухіленне ад куль",
    "Bullet Lifesteal": "Вампірызм ад куль",
    "Bullet Resist": "Супраціў кулям",
    "Clip Size": "Памер абоймы",
    "Damage Amp": "Узмацненне ўрону",
    "Fire Rate": "Скарастрэльнасць",
    "Healing Amp": "Узмацненне лячэння",
    "Health Regen": "Аднаўленне здароўя",
    "Move Speed": "Хуткасць перамяшчэння",
    "Spirit Lifesteal": "Вампірызм ад духу",
    "Spirit Power": "Сіла духу",
    "Spirit Resist": "Супраціў духу",
    "Visible Stats": "Бачныя характарыстыкі",
    "Weapon Power": "Сіла зброі",
    "25%": "25%",
    "65%": "65%",
    "75%": "75%",
    "Active Stats": "Актыўныя статы",
    "Alert Threshold": "Парог апавяшчэння",
    "Automatically selects 'With Party' in lane preference. Requires the party screen to be open.": "Аўтаматычна выбірае «З групай» у перавазе лініі. Патрабуе адкрытага экрана групы.",
    "Console alert when any feature exceeds this ms threshold.": "Апавяшчэнне ў кансолі, калі любая функцыя перавышае гэты парог у мс.",
    "Controls how many enhanced quickbuy preview items are shown.": "Кіруе тым, колькі прадметаў паказваецца ў папярэднім праглядзе палепшанай хуткай куплі.",
    "Customize the position of the Player Stats panel, or hide it completely.": "Наладзіць становішча панэлі статаў гульца або цалкам яе схаваць.",
    "Damage Impact": "Уздзеянне ўрону",
    "Detailed Console": "Падрабязная кансоль",
    "Dev": "Распрацоўка",
    "Diagnostics": "Дыягностыка",
    "Enable performance tracking (required for overlay).": "Уключыць адсочванне прадукцыйнасці (патрэбна для налажэння).",
    "Enhanced": "Палепшаны",
    "Enhanced Count": "Колькасць у палепшаным",
    "Estimated Active Reload Timer": "Прыблізны таймер Active Reload",
    "Feature Test": "Тэст функцый",
    "Hide in normal view": "Схаваць у звычайным выглядзе",
    "Hide on scoreboard (TAB)": "Схаваць на табліцы вынікаў (TAB)",
    "Hide the bottom-left active stats block during normal play. It stays in the HUD (just made invisible), so the Crosshair Active Stats mirror keeps working.": "Хавае блок актыўных статаў у левым ніжнім куце падчас звычайнай гульні. Ён застаецца ў HUD (проста становіцца нябачным), таму адлюстраванне актыўных статаў каля прыцэла працягвае працаваць.",
    "Hide the detailed stats list that appears while the scoreboard / TAB is held.": "Хавае падрабязны спіс статаў, які з'яўляецца, пакуль зацiснута табліца вынікаў / TAB.",
    "Hint Size": "Памер падказкі",
    "Item Buy Notifications": "Апавяшчэнні аб куплі прадметаў",
    "Items": "Прадметы",
    "Left": "Злева",
    "MOG": "MOG",
    "MOGLOCK": "MOGLOCK",
    "Minimalistic Pause": "Мінімалістычная паўза",
    "Mirror active buffs/debuffs vertically next to the crosshair so they are visible mid-fight.": "Адлюстроўвае актыўныя бафы/дэбафы вертыкальна каля прыцэла, каб яны былі бачныя падчас бою.",
    "On Bridge": "На мосце",
    "On Mid Boss": "На мід босе",
    "Only simplifies the shop stats display.": "Спрашчае толькі адлюстраванне статаў у магазіне.",
    "Opacity of the performance overlay panel.": "Празрыстасць панэлі налажэння прадукцыйнасці.",
    "Overlay Opacity": "Празрыстасць налажэння",
    "Per-Hero Popups": "Папапы па героях",
    "Perf Debug": "Адладка прадукцыйнасці",
    "Performance": "Прадукцыйнасць",
    "Pin the stats panel to the left (default, like vanilla) or right side of the screen.": "Замацаваць панэль статаў злева (па змаўчанні, як у ванілі) або справа экрана.",
    "Player Stats": "Статы гульца",
    "Preset Cycle": "Цыкл прэсетаў",
    "Recent Purchases": "Апошнія пакупкі",
    "Rejuvenator": "Рэжувенатар",
    "Remind when urn, bridge buffs, and gold statue upgrades are spawning.": "Нагадвае, калі адраджаюцца урна, Руны і апгрэйды залатой статуі.",
    "Right": "Справа",
    "Rotate Magazine": "Павярнуць абойму",
    "Rotate the ammo magazine visualiser.": "Павярнуць візуалізатар абоймы боезапасу.",
    "Scoreboard": "Табліца вынікаў",
    "See your view angle.": "Паказвае вугал агляду.",
    "Settings": "Налады",
    "Show Buffs": "Паказаць бафы",
    "Show Build ID": "Паказаць ID білда",
    "Show Debuffs": "Паказаць дэбафы",
    "Show Overlay": "Паказаць налажэнне",
    "Show Player Ranks": "Паказаць рангі гульцоў",
    "Show active buffs/debuffs (firerate, slow, antiheal...) vertically next to the crosshair": "Паказвае актыўныя бафы/дэбафы (скарастрэльнасць, запаволенне, антыхіл...) вертыкальна каля прыцэла",
    "Show full feature breakdown in console every 5s.": "Паказваць поўную разбіўку функцый у кансолі кожныя 5 с.",
    "Show negative modifiers (slow, antiheal, fire rate reduction...) next to the crosshair.": "Паказвае адмоўныя мадыфікатары (запаволенне, антыхіл, зніжэнне скарастрэльнасці...) каля прыцэла.",
    "Show positive modifiers (resistances, fire rate, lifesteal...) next to the crosshair.": "Паказвае станоўчыя мадыфікатары (супраціўленні, скарастрэльнасць, вампірызм...) каля прыцэла.",
    "Show purchase notifications under each hero's portrait instead of in the center.": "Паказвае апавяшчэнні аб куплі пад партрэтам кожнага героя замест цэнтра.",
    "Show rank prediction badges on top bar and escape menu player list.": "Паказвае значкі прагнозу рангу на верхняй панэлі і ў спісе гульцоў меню ESC.",
    "Show rank prediction badges on top bar player panels (requires Show Player Ranks).": "Паказвае значкі прагнозу рангу на панэлях гульцоў верхняй панэлі (патрабуе «Паказаць рангі гульцоў»).",
    "Show standalone movement speed.": "Паказвае асобную хуткасць перамяшчэння.",
    "Show the performance overlay HUD in-game.": "Паказвае HUD налажэння прадукцыйнасці ў гульні.",
    "Shows a countdown timer in the top bar for the next urn spawn or relocation.": "Паказвае зваротны адлік у верхняй панэлі да наступнага адраджэння або перамяшчэння урны.",
    "Side": "Бок",
    "Souls": "Душы",
    "Urn Timer": "Таймер урны",
    "Use the compact minimalistic pause screen instead of the default large one.": "Выкарыстоўваць кампактны мінімалістычны экран паўзы замест стандартнага вялікага.",
    "Whack a Rem": "Whack a Rem",
    "Amber": "Бурштынавы",
    "Big Camps + Sinners": "Буйныя лагеры + Sinner's",
    "Black": "Чорны",
    "Blue": "Сіні",
    "Brown": "Карычневы",
    "Charcoal": "Вугальны",
    "Coral": "Каралавы",
    "Crimson": "Малінавы",
    "Cyan": "Блакітны",
    "Gold": "Залаты",
    "Green": "Зялёны",
    "Ice": "Ледзяны",
    "Indigo": "Індыга",
    "Lane Guardian Weak": "Гвардыян лэйна аслаблены",
    "Lavender": "Лавандавы",
    "Lime": "Лаймавы",
    "Magenta": "Маджэнта",
    "Medium Camps": "Сярэднія лагеры",
    "Mint": "Мятны",
    "Orange": "Аранжавы",
    "Pink": "Ружовы",
    "Poison": "Атрутны",
    "Purple": "Пурпурны",
    "Red": "Чырвоны",
    "Rose": "Ружа",
    "Rune + Fast Troopers": "Руна + Хуткія труперы",
    "Rune + Gold Buffs": "Руна + Залатыя бафы",
    "Rune + Melee Troopers": "Руна + Мілішныя труперы",
    "Rune + Troopers 20s HP": "Руна + Труперы 20с HP",
    "Silver": "Срэбны",
    "Sky": "Нябесны",
    "Small Camps + Boxes": "Малыя лагеры + Скрыні",
    "Teal": "Бірузовы",
    "Urn + Gold Rune": "Урна + Залатая руна",
    "Violet": "Фіялетавы",
    "Void": "Пустэча",
    "Walker Weak": "Воукер аслаблены",
    "White": "Белы",
    "Yellow": "Жоўты"
};
})();
