#!/usr/bin/env python3
"""
build_locale_lookup.py — Parse Deadlock localization files and generate
a reverse-lookup JS module for QOLLock's language-agnostic hero/ability detection.

Reads:  citadel_gc_hero_names/citadel_gc_hero_names_*.txt
        citadel_heroes/citadel_heroes_*.txt
Writes: panorama/scripts/ql_locale_lookup.js

Usage:  python3 scripts/build_locale_lookup.py
"""

import json, os, re, sys

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STEAM_DEADLOCK = os.path.expanduser(
    "~/.local/share/Steam/steamapps/common/Deadlock/game/citadel/resource/localization"
)
OUTPUT = os.path.join(WORKSPACE, "panorama", "scripts", "ql_locale_lookup.js")

HERO_NAMES_DIR = os.path.join(STEAM_DEADLOCK, "citadel_gc_hero_names")
HEROES_DIR = os.path.join(STEAM_DEADLOCK, "citadel_heroes")

TOKEN_RE = re.compile(r'"([^"]+)"\s+"([^"]*)"')
HERO_KEY_RE = re.compile(r'^hero_([a-z0-9_]+):n$')
# Only base ability names (not _desc, _quip, _lore, etc.)
ABILITY_KEY_RE = re.compile(r'^(?:ability_|citadel_ability_)([a-z0-9_]+)$')
ABILITY_EXCLUDE_RE = re.compile(
    r'_(?:desc|description|quip|lore|search|sort|playstyle|guide|'
    r'video|gameplay|overview|tooltip|info|flavor|modifier|'
    r'upgrade|t\d|cast|cooldown|cost|duration|radius|damage|'
    r'heal|shield|speed|range|charge|ammo|reload|fire|clip|'
    r'buff|debuff|slow|stun|root|disarm|silence|'
    r'label|prevalue|postvalue|prevalue_label|postvalue_label|'
    r'postfix|prefix|suffix)$'
)


def parse_loc_file(filepath, key_pattern, strip_prefix=False):
    """Parse a Valve localization .txt file.
    Returns dict: {localized_text_lower: internal_key}"""
    lookup = {}
    try:
        with open(filepath, "r", encoding="utf-8-sig") as f:
            content = f.read()
    except FileNotFoundError:
        return lookup

    for match in TOKEN_RE.finditer(content):
        key = match.group(1).strip()
        value = match.group(2).strip()
        if not value or len(value) > 120:  # Skip long description strings
            continue
        m = key_pattern.match(key)
        if not m:
            continue
        internal = m.group(1) if strip_prefix else key
        
        # Exclude description/lore/etc variants
        if key_pattern == ABILITY_KEY_RE and ABILITY_EXCLUDE_RE.search(internal):
            continue
            
        internal_id = internal.lower()
        lookup_key = value.lower()
        if lookup_key not in lookup:
            lookup[lookup_key] = internal_id
    return lookup


def extract_language(filename):
    base = os.path.splitext(filename)[0]
    parts = base.rsplit("_", 1)
    if len(parts) == 2:
        return parts[1]
    return "unknown"


def main():
    hero_lookups = {}
    if os.path.isdir(HERO_NAMES_DIR):
        for fname in sorted(os.listdir(HERO_NAMES_DIR)):
            if not fname.endswith(".txt"):
                continue
            lang = extract_language(fname)
            fpath = os.path.join(HERO_NAMES_DIR, fname)
            lookup = parse_loc_file(fpath, HERO_KEY_RE, strip_prefix=True)
            if lookup:
                hero_lookups[lang] = lookup

    ability_lookups = {}
    if os.path.isdir(HEROES_DIR):
        for fname in sorted(os.listdir(HEROES_DIR)):
            if not fname.endswith(".txt"):
                continue
            lang = extract_language(fname)
            fpath = os.path.join(HEROES_DIR, fname)
            lookup = parse_loc_file(fpath, ABILITY_KEY_RE, strip_prefix=True)
            if lookup:
                ability_lookups[lang] = lookup

    if not hero_lookups:
        print(f"WARNING: No hero name lookups. Check: {HERO_NAMES_DIR}")

    # Build JS using json.dumps for safe string encoding
    hero_json = json.dumps(hero_lookups, ensure_ascii=False, indent=2, sort_keys=True)
    ability_json = json.dumps(ability_lookups, ensure_ascii=False, indent=2, sort_keys=True)

    js = f"""// ql_locale_lookup.js — Auto-generated locale reverse-lookup for QOLLock
// Maps localized hero/ability names → internal IDs.
// Generated by: scripts/build_locale_lookup.py
// DO NOT EDIT MANUALLY — regenerate with the build script.
(function() {{
    'use strict';

    // Localized hero name → internal hero_id (e.g. 'gök yürüyen' → 'skyrunner')
    var LOCALE_HERO = {hero_json};

    // Localized ability name → internal ability_id (e.g. 'hayat İpliği' → 'skyrunner_swingline')
    var LOCALE_ABILITY = {ability_json};

    /**
     * Try to resolve a localized hero name to its internal hero_id.
     * Language-agnostic: tries all locale tables until a match is found.
     * @param {{string}} text - The localized hero name (e.g. 'Gök Yürüyen')
     * @returns {{string}} Internal hero ID (e.g. 'hero_skyrunner') or empty string
     */
    function LookupLocaleHero(text) {{
        if (!text) return '';
        var key = String(text).replace(/\\s+/g, ' ').replace(/^\\s+|\\s+$/g, '').toLowerCase();
        if (!key) return '';
        for (var lang in LOCALE_HERO) {{
            if (LOCALE_HERO.hasOwnProperty(lang)) {{
                var table = LOCALE_HERO[lang];
                if (table.hasOwnProperty(key)) return 'hero_' + table[key];
            }}
        }}
        return '';
    }}

    /**
     * Try to resolve a localized ability name to its internal ability_id.
     * Language-agnostic: tries all locale tables until a match is found.
     * @param {{string}} text - The localized ability name (e.g. 'Hayat İpliği')
     * @returns {{string}} Internal ability ID (e.g. 'ability_skyrunner_swingline') or empty string
     */
    function LookupLocaleAbility(text) {{
        if (!text) return '';
        var key = String(text).replace(/\\s+/g, ' ').replace(/^\\s+|\\s+$/g, '').toLowerCase();
        if (!key) return '';
        for (var lang in LOCALE_ABILITY) {{
            if (LOCALE_ABILITY.hasOwnProperty(lang)) {{
                var table = LOCALE_ABILITY[lang];
                if (table.hasOwnProperty(key)) return 'ability_' + table[key];
            }}
        }}
        return '';
    }}

    /**
     * Extract a hero token from label text like "Gök Yürüyen's Recommended Mods".
     * Strips possessive/qualifier suffixes, then looks up in locale tables.
     * @param {{string}} labelText - Full label text (e.g. "Gök Yürüyen's Recommended Mods")
     * @returns {{string}} Internal hero ID or empty string
     */
    function ExtractHeroFromLabelText(labelText) {{
        if (!labelText) return '';
        var text = String(labelText).replace(/\\s+/g, ' ').replace(/^\\s+|\\s+$/g, '');
        if (!text) return '';
        // Strip possessive/qualiifier suffixes
        var heroName = text.replace(/(?:'s?\\s+(?:Recommended\\s+)?(?:Mods|Builds?|Items?|Guide)).*$/i, '');
        heroName = heroName.replace(/\\s+/g, ' ').replace(/^\\s+|\\s+$/g, '');
        if (!heroName || heroName === text) heroName = text;
        return LookupLocaleHero(heroName);
    }}

    // Publish to QOL namespace
    if (typeof QOL !== 'undefined') {{
        QOL.lookupLocaleHero = LookupLocaleHero;
        QOL.lookupLocaleAbility = LookupLocaleAbility;
        QOL.extractHeroFromLabelText = ExtractHeroFromLabelText;
    }}
    try {{ if (typeof window !== 'undefined') {{
        window.LookupLocaleHero = LookupLocaleHero;
        window.LookupLocaleAbility = LookupLocaleAbility;
        window.ExtractHeroFromLabelText = ExtractHeroFromLabelText;
    }} }} catch(e) {{}}
}})();
"""

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(js)

    hero_count = sum(len(t) for t in hero_lookups.values())
    ability_count = sum(len(t) for t in ability_lookups.values())
    print(f"Generated: {OUTPUT}")
    print(f"  Languages (hero):    {len(hero_lookups)} ({hero_count} entries)")
    print(f"  Languages (ability): {len(ability_lookups)} ({ability_count} entries)")


if __name__ == "__main__":
    main()
